-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 10, 2014 at 05:20 AM
-- Server version: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `cs174`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE IF NOT EXISTS `fun_video` (
`id` int(11) NOT NULL,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=161 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(9, 'Yang style tai chi 85 form Part1', 'https://www.youtube.com/watch?v=kcl0o-Q7qpM', 11, '480', 'Master David Bao, Hua Ying Wushu & Tai Chi Academy www.davidbao.com', 'English', 84827, 'Tutorial', 'http://i.ytimg.com/vi/kcl0o-Q7qpM/mqdefault.jpg', 'Yang style, tai chi, demo, 85 forms'),
(14, 'Tai Chi Application in Traditional Yang Long Form ', 'https://www.youtube.com/watch?v=nuvLWEsw_hw', 4, '480', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong) meditation for internal energy healing, bio-energy, Shaolin and Wudang Taoist Kung-fu martial arts, Taiji Power Release (fajin), Taiji application, Bagua, Xingyi application. Tai Chi Health Ways host annual workshop with the top masters. See photos or videos of Chen Zhenglei, Li Deyin, Zhu Tiancai, Chen Xiaowang, Dan Lee, Su Zifang, Abraham Liu .... In this video, you will learn the fighting aspects of Traditional Yang Style Tai Chi. The principles are based on Tai Chi Classics: to redirect or borrow an opponent''s force first, then strike his weak point. Tai Chi was originally a Chinese martial art for self-defense.', 'English', 114254, 'Application', 'http://i.ytimg.com/vi/nuvLWEsw_hw/mqdefault.jpg', 'application, self defense, fight, kungfu'),
(21, 'Tai Chi 24 Form, with English Titles', 'http://www.youtube.com/watch?v=-ZtpwmjMC7Q', 6, '240', 'Tai Chi 24 Form with English titles inserted between postures; edited version of video copied from www.taiji.de. The performer is Gao Jiamin. According to Kungfu Magazine (July 2000 issue) she was born in Fuzhou City, Fujian Province, China June 26, 1966.', 'English', 428712, 'Tutorial,Application', 'http://i.ytimg.com/vi/-ZtpwmjMC7Q/mqdefault.jpg', 'Tai Chi,Tutorial, demo, 24 forms'),
(22, 'Yang Style Tai Chi 108 Form 3 of 3', 'http://www.youtube.com/watch?v=01TOLg40F14', 7, '360', 'Yang style Taijiquan at Wudangshan. Part 3 of 3\r\n"BEYOND THE FORM" to purchase complete 2 DVD set, 2 Subtitled 108 forms & Fast (Fa-Jin)Set, click on http://taijihawaii.com/contact.html\r\nBeyond just learning an external form or forms, a students emphasis "must" also focus on applying the "essential" internal principles of Taijiquan as specified by the Taiji classics, such as.....sinking , roundness , using the mind and not force, applying of the "Yi" (heart/mind), "Qi" (energy) & "Shen" (spirit) in ones form.\r\nMindfulness to body alignment, raising the spirit, coordinating upper and lower parts of the body, etc. is demanded.\r\nThe achievement of "stillness in motion", "moving as one" distinguishing clearly between full & empty ", gathering & releasing, opening & closing and making the energy flow evenly thru all the meridian channels is always the challenge for everyone regardless of level..\r\nThis discipline of "internal work" with careful" intention" and "attention to detail" with cons', 'English', 77673, 'Others', 'http://i.ytimg.com/vi/01TOLg40F14/mqdefault.jpg', 'yan style, tai chi, 108 forms'),
(24, 'Classical Yang Tai Chi Chuan', 'http://www.youtube.com/watch?v=2FbASDzC3bU', 8, '240', 'The Traditional Long Form as Performed by Master Lu Guo Ming', 'English', 129146, 'Entertainment', 'http://i.ytimg.com/vi/2FbASDzC3bU/mqdefault.jpg', 'yan style, demo, tai chi'),
(25, 'Yang Style Taijiquan 108 form 1 of 3', 'http://www.youtube.com/watch?v=2IlhW5UIu_U', 7, '360', 'Yang Style Tai Chi 108 form, Sifu Peter Tam Hoy at Wudangshan "BEYOND THE FORM" to purchase complete 2 DVD set, 2 Subtitled 108 forms & Fast (Fa-Jin) Set, click on http://taijihawaii.com/contact.html Beyond just learning an external form or forms, a students emphasis "must" also focus on applying the "essential" internal principles of Taijiquan as specified by the Taiji classics, such as.....sinking , roundness , using the mind and not force, applying of the "Yi" (heart/mind), "Qi" (energy) & "Shen" (spirit) in ones form. Mindfulness to body alignment, raising the spirit, coordinating upper and lower parts of the body, etc. is demanded. The achievement of "stillness in motion", "moving as one" distinguishing clearly between full & empty ", gathering & releasing, opening & closing and making the energy flow evenly thru all the meridian channels is always the challenge for everyone regardless of level.. This discipline of "internal work" with careful" intention" and "attention to detail"', 'Non-English', 178835, 'Tutorial', 'http://i.ytimg.com/vi/2IlhW5UIu_U/mqdefault.jpg', 'yan style, tai chi, 108 applications'),
(26, 'Tai Chi 16 Form Yang Style', 'http://www.youtube.com/watch?v=2OEc8kPVn_Y', 3, '240', 'Tai Chi 16 Form Yang Style with movement names.', 'Non-English', 67718, 'Tutorial', 'http://i.ytimg.com/vi/2OEc8kPVn_Y/mqdefault.jpg', 'yan style, tai chi, demo, 16 form'),
(27, 'Yang Tai Chi combat tutorial', 'http://www.youtube.com/watch?v=3jCpU5oVKqM', 4, '240', '"Can this ancient exercise lets you have less doctor visit and makes you feel 10 years younger?" Visit http://goo.gl/hK5Ot\r\n\r\nTai Chi combat tutorial, teached by Yang Tai Chi Chuan official successor, very useful!', 'Non-English', 387955, 'Tutorial,Application,Others', 'http://i.ytimg.com/vi/3jCpU5oVKqM/mqdefault.jpg', 'yan style, demo, tutorial, tai chi'),
(28, 'Cheng Man Ching san sau é„­æ›¼é’æ•£æ‰‹', 'http://www.youtube.com/watch?v=3WjaFNue7tE&feature=youtube_gdata', 2, '480', 'We have seen a lot of Cheng Man Ching demonstrating fa-jing and push hands.Here is rare footage of Cheng demonstrating san sau.', 'English', 88000, 'Entertainment', 'http://i.ytimg.com/vi/3WjaFNue7tE/0.jpg', 'demo'),
(29, 'Yang Tai Chi Chuan Part One', 'http://www.youtube.com/watch?v=5fTAA-M4GkY', 2, '240', 'This videotape teaches you the essential building blocks for a strong foundation in Tai Chi Chuan. It will guide you through the first section of the Yang style long form. Proper understanding of this first section is crucial, since it teaches you the fundamental movements for the rest of your form. This tape also includes basic footwork, meditation stance, and some stretches and exercises that are basic to Tai Chi.', 'English', 103307, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/5fTAA-M4GkY/mqdefault.jpg', 'tutorial, demo, tai chi, chuan style'),
(30, 'Tai Chi 37-Style - Barry Lin', 'http://www.youtube.com/watch?v=6JHZLeFfmvw', 7, '240', 'Tai Chi 37 Style Competition in Taiwan in 2000\r\nBarry Lin', 'English', 51093, 'Tutorial', 'http://i.ytimg.com/vi/6JHZLeFfmvw/mqdefault.jpg', 'Tai Chi,Tutorial, 37 styles'),
(31, 'Yang style Tai Chi for Health Short Form 1 of 5', 'http://www.youtube.com/watch?v=6KSsMWOJfK8', 3, '240', 'This is the first section of the 24 movement short form.\r\n\r\nInstructional DVDs Now Available.\r\nPlease check\r\nwww.internalkungfu.org\r\nwww.shenlongpub.com\r\nDVDs are also available at Amazon.com\r\n\r\nYang style Tai Chi for Health: Volume One, Fundamentals\r\n2 disk set\r\nDisk One (Approximate Running Time: 81 Minutes)\r\nConcepts and Principles\r\nHand Positions\r\nStances\r\nWarm Up Exercises (12 exercises)\r\nQi Gong (3 exercises)\r\nStanding Meditation (3 postures)\r\n\r\nDisk Two (Approximate Running Time: 58 Minutes)\r\nShifting the Weight\r\nTai Chi Walking\r\nSingle Posture Practice\r\n\r\n\r\nYang style Tai Chi for Health: Volume Two: 24 Movement Short Form\r\nInstruction in the Complete 24 Movement Yang style Short Form\r\nAlso contains a demonstration of the Complete Form done at Practice Speed\r\n(Approximate Running Time: 62 Minutes)\r\n\r\nYang style Tai Chi for Health Volume Three: Traditional Long Form\r\n2 Disk Set\r\nInstruction in the Complete Traditional Yang style Long Form\r\nAlso contains a demonstration of the Com', 'English', 154686, 'Application', 'http://i.ytimg.com/vi/6KSsMWOJfK8/mqdefault.jpg', 'yang style, demo, tai chi'),
(32, 'YMAA Taiji Applications (Yang taijiquan) tai chi f', 'http://www.youtube.com/watch?v=6NagW6BImF8', 4, '240', 'Taijiquan (Tai Chi Chuan) is an ancient internal Chinese martial art which has gained widespread popularity for its many health benefits. Today, most people practice taiji slowly to develop their balance, strength, and vitality, and the martial applications of the art are often ignored. Taijiquan, or Grand Ultimate Fist, is a highly effective form of combat specializing in short and middle-range fighting.\r\n\r\nThis program offers practical martial applications for each of the 37-postures of traditional Taiji, based on the forms passed down by Yang, Ban-Hou. Once the viewer has a basic understanding of these universal principles, you may use them to devise further applications for every movement no matter which style of Taiji you practice.\r\n\r\nLearn the Basic Concepts of Taiji and Taijiquan.\r\nUnderstand the purpose of every Taiji movement.\r\nOver 50 effective applications for any Taijiquan style.', 'Non-English', 450819, 'Group demo', 'http://i.ytimg.com/vi/6NagW6BImF8/mqdefault.jpg', 'yan style, group demo, tai chi'),
(33, 'Yang Style Tai Chi Long Form 108 Taiji 1', 'http://www.youtube.com/watch?v=6tLC9KslCo4', 4, '480', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Tai Chi Health Ways host annual workshop with the top masters', 'Non-English', 91559, 'Tutorial', 'http://i.ytimg.com/vi/6tLC9KslCo4/mqdefault.jpg', 'yan style, tai chi, demo, 108 form, tutorial'),
(34, 'Yang Tai Chi Chuan Applications', 'http://www.youtube.com/watch?v=6y-vqsQGX9M', 1, '240', 'To the untrained eye, Tai Chi Chuan seems too slow for combat. However, these soft movements conceal effective self-defense techniques', 'Non-English', 76008, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/6y-vqsQGX9M/mqdefault.jpg', 'Tai Chi,Tutorial, chuan style'),
(35, '1. æ­£å®—æ¥Šæ°85å¼å¤ªæ¥µæ‹³å‚…æ¸…æ³‰ Authentic Y', 'http://www.youtube.com/watch?v=7cAzhoxXdDw', 63, '240', '', 'Non-English', 91798, 'Entertainment,Application', 'https://i.ytimg.com/vi/7cAzhoxXdDw/mqdefault.jpg', 'Education, Information, History'),
(36, 'From BodyWisdoms Tai Chi for Beginners with Chris ', 'http://www.youtube.com/watch?v=7D7qAQ720x8', 85, '1080', 'TAI CHI FOR BEGINNERS is the perfect Tai Chi exercise video to explore and experience the numerous benefits of Tai Chi, no matter what shape you are in. This ancient, physical & meditative practice of the Yang style 24 posture form tai chi video is designed to build strength, improve health & flexibility, reduce stress, increase energy flow, promote health & wellness and relax your mind. These 8 easy-to-follow lessons teach the Tai Chi postures with clear, step-by-step instructions. The routines are low-impact with modifications taught for less-flexible people. No other tai chi exercise dvd offers so much quality and value.\r\n\r\nWorld-renowned Tai Chi master Chris Pei leads you through customized lessons ranging from 10 to 30 minutes. This safe and effective fitness DVD is suitable for every body, all ages and schedules.', 'English', 420286, 'Application', 'http://i.ytimg.com/vi/7D7qAQ720x8/mqdefault.jpg', 'yan style, tai chi, information, demo'),
(37, 'Yang Taiji, Master Yang Jun, 1 part, 103 form', 'http://www.youtube.com/watch?v=7pna9ajZHKY', 5, '240', 'Yang Taiji, Master Yang Jun, 1 part, 103 form', 'Non-English', 181997, 'Others', 'http://i.ytimg.com/vi/7pna9ajZHKY/mqdefault.jpg', 'yan style, demo, tai chi'),
(38, 'Tai Chi: Exercise for Lifelong Health and Well-Bei', 'http://www.youtube.com/watch?v=8Fz5U2uznZE&feature=youtube_gdata', 7, '240', 'http://www.beyou.tv/videos/Tai-Chi-Exercise-for-Lifelong-Health-and-Well-Being brings you Tai Chi: Exercise for Lifelong Health and Well-Being', 'English', 201875, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/8Fz5U2uznZE/0.jpg', 'tai chi, exercise, health'),
(39, 'Combat Tai Chi', 'http://www.youtube.com/watch?v=93wy9FBFP24&feature=youtube_gdata', 1, '360', 'Tai Chi CombatThis video can instantly be downloaded on Payloadz. Follow this link http://store.payloadz.com/results/results.asp?m=104410', 'English', 1448415, 'Tutorial,Application', 'http://i.ytimg.com/vi/93wy9FBFP24/0.jpg', 'tai chi, combat, tutorial, demo'),
(40, 'simple fouet tai chi chuan style yang', 'http://www.youtube.com/watch?v=9eRZaSsyVnU', 10, '240', 'simple fouet tai chi chuan style yang', 'Non-English', 53581, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/9eRZaSsyVnU/mqdefault.jpg', 'Tai Chi, Demo,Tutorial, chuan style'),
(41, 'Taiji: Traditional Yang Tai Chi Sword', 'http://www.youtube.com/watch?v=9VYw1WbpmG8', 7, '240', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts.', 'English', 137751, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/9VYw1WbpmG8/mqdefault.jpg', 'Tai,Chi,Tutorial, Demo, Music'),
(42, 'Tai Chi Yang Style (XIN) Fast Forms by Agilceed Bo', 'http://www.youtube.com/watch?v=9X5Dyzj4NKU', 5, '240', 'Yang Style Tai Ji (XIN) can be performed in a fast pace. Yang style tai chi hand form (long forms 115), in a normal pace, should be performed between 20 and 50 minutes.', 'English', 74358, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/9X5Dyzj4NKU/mqdefault.jpg', 'Tai Chi,Tutorial, yang style, fast form'),
(43, 'Traditional Yang Style Tai Chi Chuan', 'http://www.youtube.com/watch?v=a6pJf2otwv8', 9, '240', 'Traditional Yang style Taiji /Sifu Peter Tam Hoy "BEYOND THE FORM" to purchase complete 2 DVD set, subtitled 108 form & Fast (Fa-Jin) Set click on http://taijihawaii.com/contact.html', 'English', 335626, 'Tutorial', 'http://i.ytimg.com/vi/a6pJf2otwv8/mqdefault.jpg', 'yang style, demo, tutorial'),
(45, 'Yang Style Tai Chi Short Form (Part 1)', 'http://www.youtube.com/watch?v=AJaTRmtTark', 9, '144', 'Mark Sheppard demonstrates the Yang Style Tai Chi Short Form in Hyde Park, London', 'English', 54432, 'Entertainment', 'http://i.ytimg.com/vi/AJaTRmtTark/mqdefault.jpg', 'Tai Chi, Music, Demo, short form'),
(46, 'Yang Style 48 Form Tai Chi Chuan', 'http://www.youtube.com/watch?v=AK5XDZN-t74', 8, '240', 'Sifu Amin Wu - www.aminwutaichi.com Original Tai Chi instructional VCD video by Sifu Amin Wu (in Chinese version) available on website', 'Non-English', 427736, 'Tutorial', 'http://i.ytimg.com/vi/AK5XDZN-t74/mqdefault.jpg', 'yan style, demo, tutorial, tai chi'),
(47, 'Learn Tai Chi', 'http://www.youtube.com/watch?v=ARyIqrUD2rY', 6, '480', 'taichic.com', 'Non-English', 128874, 'Tutorial,Application', 'http://i.ytimg.com/vi/ARyIqrUD2rY/mqdefault.jpg', 'tutorial, demo, tai chi'),
(48, 'Tai Chi Leque Yang 18 movimentos_em grupo_18', 'http://www.youtube.com/watch?v=BLLeQHgNmYc', 2, '720', '+ info:\r\nhttp://oqueemeuenosso.blogspot.com/20...\r\n\r\nDVD:\r\nhttp://www.taichidepot.com/shopping/y...', 'English', 53453, 'Group demo', 'http://i.ytimg.com/vi/BLLeQHgNmYc/mqdefault.jpg', 'yan style, tai chi, demo, 18 moves'),
(49, 'Tai-Chi Yang em 88 movimentos - Parte 2', 'http://www.youtube.com/watch?v=Bm7e3HfEEfI', 5, '480', 'Rotina em 88 Movimentos da Escola Yang - segunda parte.', 'Non-English', 52303, 'Tutorial', 'http://i.ytimg.com/vi/Bm7e3HfEEfI/mqdefault.jpg', 'Tai Chi,Tutorial, Demo, music'),
(50, 'Yangjia Michuan Taiji æ¥Šå®¶ç§˜å‚³å¤ªæ¥µæ‹³ç¬¬ä¸€æ', 'http://www.youtube.com/watch?v=bnT3f-wrAfI&feature=youtube_gdata', 9, '480', 'George C. Lin of Taiwan demonstrates Yangjia Michuan Taiji Section 1.  George has been a student of the late Master Wang Yen Nien for over 50 years. This form can be used not only for health, but for self-defense. For more exclusive videos of this "Secret Style", go to http://www.taiji-yangmi.com/.', 'Non-English', 59741, 'Tutorial', 'http://i.ytimg.com/vi/bnT3f-wrAfI/0.jpg', 'defense, secret, demo'),
(51, 'å¤ªæ¥µæ‹³å¥—æ‹³å‹•ä½œç¤ºç¯„  æ¥Šå®ˆä¸­  Yang Sau C', 'http://www.youtube.com/watch?v=Bze07WyY0C0&feature=youtube_gdata', 9, '480', 'YÃ¡ng ShÇ’uzhÅng\r\nYang, Sau Chung (1910-1985), was the  eldest son of Grandmaster Yang Cheng Fu. He started learning his family style when he was 8 years old under the strict supervision of his father. At 14, he started to assist his father in teaching Tai chi chuan.  By the age of 19, he was travelling throughout China with his father to assist in teaching Tai chi. \r\nIn truth, many people who have claimed to learned from Yang, Cheng Fu actually learned from Yang, Sau Chung. In 1949, he moved to Hong Kong, and he taught privately at his home until his death in 1985. \r\nHis dedication to Yang Family Tai Chi Chuan was as equally committed as his father, grandfather Yang Chien Hou, and his great grandfather Yang Lu Chan; and, as a result, he achieved one of the highest levels. \r\nYang Sau Chung passed on the family transmission to his First Disciple, Ip Tai Tak, (1958) and his three daughters, Amy - Tai Yee, Mary - Ma Lee and Agnes -- Yee-Li. He also accepted two other Disciples - Chu Gin ', 'Non-English', 54170, 'Entertainment,Others', 'http://i.ytimg.com/vi/Bze07WyY0C0/0.jpg', 'tai chi, information, English sub, history'),
(52, 'Tai Chi Qigong Shibashi (1 of 2)', 'http://www.youtube.com/watch?v=c60u6WfChmM', 15, '480', 'http://www.taichi18.com Tai Chi Qigong Shibashi is a Qigong which based on the philosophy of Tai Chi and extracts some of the best movements from the Yang style Tai Chi Chuan. It places emphasis on synchronizing the 18 movements with proper breathing techniques. It is a gentle, beautiful and flowing Qigong exercise routine that is both a joy to do and deeply relaxing. Instruction manual and other resources of this qigong available at www.taichi18.com for free download.', 'English', 450502, 'Tutorial,Others', 'http://i.ytimg.com/vi/c60u6WfChmM/mqdefault.jpg', 'yan style, tutorial, demo, tai chi'),
(53, 'Tai Chi 42 Forms Part 1 - Teach', 'http://www.youtube.com/watch?v=cgcPYr9etlI', 8, '240', 'Tai Chi 42 Forms Part 1 - Teach\r\n\r\nTai Chi: An Exercise in Anti-aging\r\nTai chi, the choreographed meditative exercises that have been a healing art in China for thousands of years, is practiced by over 100 million people worldwide and owes its popularity to a sim', 'Non-English', 258235, 'Application', 'http://i.ytimg.com/vi/cgcPYr9etlI/mqdefault.jpg', 'yan style, tutorial, tai chi'),
(54, 'Tai chi for beginners - Yang Style Form Lessons 2', 'http://www.youtube.com/watch?v=cNWEVeHc54g', 7, '720', 'Learn the basics of Tai chi for beginners from a real tai chi master. Master Wong tai chi available in Ipswich, Suffolk and online offers instruction with the best quality music and HD video. Yang style and Chen style form. Click here http://www.taichicombat.com/', 'English', 79728, 'Application', 'http://i.ytimg.com/vi/cNWEVeHc54g/mqdefault.jpg', 'yang style, tai chi, beginner '),
(56, 'Tai Chi Movements & Exercises : Tai Chi Ball Exerc', 'http://www.youtube.com/watch?v=DHN8fHZxBA8&feature=youtube_gdata', 3, '720', 'One of the benefits of tai chi balls is that they reinforce principles, such as breathing. Discover how tai chi balls can be used to set up resistance in movements with help from a tai chi instructor in this free video on tai chi ball exercises.\n\nExpert: Bob Waers\nContact: www.youhealthcenter.com/\nBio: Bob Waers trained directly with Grand Master Chan Pui of the Wah Lum kung fu system for 12 years.\nFilmmaker: Suzie Vigon', 'English', 52261, 'Tutorial', 'http://i.ytimg.com/vi/DHN8fHZxBA8/0.jpg', 'tai chi, exercise, demo, tutorial'),
(57, 'MASTERS OF HEAVEN & EARTH - Official Trailer by Em', 'http://www.youtube.com/watch?v=dwNXaQwjEr4', 3, '240', 'This is the trailer for Masters of Heaven and Earth. If you thought Tai Chi was old folks in the park moving slowly you will be shocked. Come with us on a journey across China to explore real Tai chi chuan. Featuring Chen style, Wudang tai chi and Yang styles. Chen Xiaowang and Chen Xiaoxing with yang style master Cui Zhongzan. Also features Wudang masters Priest Zhong Yun Long and Yuan. Available on DVD and HD download at http://emptymindfilms.com', 'Non-English', 690324, 'Entertainment', 'http://i.ytimg.com/vi/dwNXaQwjEr4/mqdefault.jpg', 'yan style, tai chi, trailer, movie'),
(58, 'Yang Style Tai Chi Applications Fighting Technique', 'http://www.youtube.com/watch?v=ecjnoijaOyg', 8, '480', 'http://www.kungfu4u.net/', 'Non-English', 63345, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/ecjnoijaOyg/mqdefault.jpg', 'yan style, fight, tai chi'),
(60, 'Yang Taiji, Master Yang Jun, 2 part, 103 form', 'http://www.youtube.com/watch?v=Ek_LjYWaveo', 11, '144', 'Yang Taiji, Master Yang Jun, 2 part, 103 form', 'English', 124381, 'Tutorial', 'http://i.ytimg.com/vi/Ek_LjYWaveo/mqdefault.jpg', 'yan style, demo, tai chi'),
(61, 'Tai chi for beginners - Yang Basic 8 step', 'http://www.youtube.com/watch?v=EOPHsY0FnlE', 3, '720', 'Learn the basics of Tai chi for beginners from a real tai chi master. Master Wong tai chi available in Ipswich, Suffolk and online offers instruction with the best quality music and HD video. Yang style and Chen style form. Click here http://www.taichicombat.com/', 'English', 125702, 'Others', 'http://i.ytimg.com/vi/EOPHsY0FnlE/mqdefault.jpg', 'yan style, demo, tai chi'),
(64, 'Tai Chi Chin Na (YMAA Qin Na) Dr. Yang, Jwing-Ming', 'http://www.youtube.com/watch?v=Etvn0wmBkaU', 3, '480', 'Control Any Opponent with Simple, Powerful Joint Locks\r\n\r\nChin Na (Qin Na) is the art of seizing and controlling an opponent. It is a fast, effective way to subdue an attacker using joint locks, cavity press, bone misplacement, muscle grabbing, and artery sealing. Taijiquan is a traditional martial art, and Chin Na is an important part of your complete Taiji (Tai Chi) training. Taiji Chin Na are smooth, flowing techniques that are simple to execute and difficult to escape.\r\n\r\nDr. Yang discusses, demonstrates, and teaches you his Chin Na techniques up-close and in detail. All these techniques are hidden inside the Yang style postures, but can be applied to all Taiji styles.', 'English', 102582, 'Group demo', 'http://i.ytimg.com/vi/Etvn0wmBkaU/mqdefault.jpg', 'yan style, demo, tai chi'),
(65, 'Tai Ji Sword (Yang Style 54 forms), Agilceed books', 'http://www.youtube.com/watch?v=f-GydPcL-Yc', 5, '240', 'This is Tai Chi Sword - Yang style (Xin) 54 forms performed by Master Li Guang Qi.\r\n\r\nMy 24 simplified tai chi form book is just listed in Amazon.com under the author name: Cheng Zhao\r\n', 'English', 50048, 'Entertainment', 'http://i.ytimg.com/vi/f-GydPcL-Yc/mqdefault.jpg', 'Sports, sword'),
(66, 'Yang Tai Chi 24 Form Back View', 'http://www.youtube.com/watch?v=F6rf5KdAKdE', 6, '480', 'International Tai Chi Champion Dr. Pauline Bao Performs Yang Tai Chi 24 Form Back View (Taiji 24 Form Posterior View) at Lakeside Park in Nelson, British Columbia (BC), Canada.\r\n\r\nThe Bao ACADEMY of Tai Chi & Kung Fu located in Nelson, BC, Canada offers Tai Chi and Kung Fu classes taught by Master Pauline Bao.', 'Non-English', 233884, 'Others', 'http://i.ytimg.com/vi/F6rf5KdAKdE/mqdefault.jpg', 'yan style, tai chi, 24 form'),
(67, 'Tai Chi Chuan style Yang - 8 portes', 'http://www.youtube.com/watch?v=fKFw45hhP-s', 4, '240', 'Tai Chi Chuan style Yang - 8 portes', 'Non-English', 59150, 'Tutorial', 'http://i.ytimg.com/vi/fKFw45hhP-s/mqdefault.jpg', 'Tai Chi,Tutorial, demo'),
(68, 'Chen Manching Yang taichi shot form (full set)', 'http://www.youtube.com/watch?v=Fl2mvyjHYS0', 7, '240', '37 posture Yang form developed by Master Chen Manching, student of Master Yang Chenfu.', 'Non-English', 353102, 'Others', 'http://i.ytimg.com/vi/Fl2mvyjHYS0/mqdefault.jpg', 'yang style, demo, short form, tai chi'),
(69, 'Yang Style 40 Form Tai Chi Chuan', 'http://www.youtube.com/watch?v=FowwENJg1xU', 5, '360', 'Sifu Amin Wu - www.aminwutaichi.com Original Tai Chi instructional VCD video by Sifu Amin Wu (in Chinese version) available on website', 'Non-English', 59907, 'Tutorial', 'http://i.ytimg.com/vi/FowwENJg1xU/mqdefault.jpg', 'yan style, tai chi, 40 form'),
(70, 'tai chi yang 16 forms', 'http://www.youtube.com/watch?v=Fyl7_xkyzv8', 3, '240', 'taichi for beginners', 'English', 159903, 'Others', 'http://i.ytimg.com/vi/Fyl7_xkyzv8/mqdefault.jpg', 'yan style, beginners, demo, tai chi'),
(71, 'å…«å¼å¤ªæ¥µæ‹³  8-form Tai Chi', 'http://www.youtube.com/watch?v=FzEQc7UjmM4&feature=youtube_gdata', 3, '240', 'å…«å¼å¤ªæ¥µæ‹³æ˜¯ä¸­åœ‹æ­¦è¡“æ®µä½åˆ¶åˆæ®µä½æŠ€è¡“çš„ä¸€æ®µå¤ªæ¥µæ‹³,å…±æœ‰8å€‹å‹•ä½œ,æ˜¯æ¥Šå¼å¤§æž¶å¤ªæ¥µæ‹³,å‹•ä½œæŸ”å’Œå¹³ç©©,å‡å‹»ç·©æ…¢,è¡Œé›²æµæ°´,é€£ç¶¿ä¸æ–·....\nEight-form Tai Chi, which is Yang Style Tai Chi, has a total of eight steps. Its movements are softly, smoothly, uniformly, slowly, continuously, and naturally.\n8ã‚¹ã‚¿ã‚¤ãƒ«å¤ªæ¥µæ‹³ã€8ã¤ã®å‹•ãã€ãƒ¤ãƒ³ã‚¹ã‚¿ã‚¤ãƒ«ã®å¤ªæ¥µæ‹³ã€ç©ã‚„ã‹ãªå‹•ãæ»‘ã‚‰ã‹ã§ã€å‡ä¸€ãªã€æ»‘ã‚‰ã‹ã§ã€é€£ç¶šä½Žé€Ÿã®åˆè¨ˆã€‚\n8 ìŠ¤íƒ€ì¼ íƒœê·¹ê¶Œ, 8 ì›€ì§ìž„ ì–‘ì”¨ ìŠ¤íƒ€ì¼ íƒœê·¹ê¶Œ, ë¶€ë“œëŸ¬ìš´ ì›€ì§ìž„ì´ ë¶€ë“œëŸ½ê³ , ìœ ë‹ˆí¼, ë¶€ë“œëŸ½ê³  ì§€ì†ì ì¸ ëŠë¦° ì´.\nÐ’Ð¾ÑÐµÐ¼ÑŒ Ñ„Ð¾Ñ€Ð¼Ñ‹ Tai Chi, Ñ‡Ñ‚Ð¾ Ð¯Ð½ ÑÑ‚Ð¸Ð»Ñ Ð¢Ð°Ð¹ Ð§Ð¸, Ð¸Ð¼ÐµÐµÑ‚ Ð² Ð¾Ð±Ñ‰ÐµÐ¹ ÑÐ»Ð¾Ð¶Ð½Ð¾ÑÑ‚Ð¸ Ð²Ð¾ÑÐµÐ¼ÑŒ ÑˆÐ°Ð³Ð¾Ð². Ð•Ð³Ð¾ Ð´Ð²Ð¸Ð¶ÐµÐ½Ð¸Ñ Ð¼ÑÐ³ÐºÐ¾, Ð¿Ð»Ð°Ð²Ð½Ð¾, Ñ€Ð°Ð²Ð½Ð¾Ð¼ÐµÑ€Ð½Ð¾, Ð¼ÐµÐ´Ð»ÐµÐ½Ð½Ð¾, Ð½ÐµÐ¿Ñ€ÐµÑ€Ñ‹Ð²Ð½Ð¾ Ð¸ ÐµÑÑ‚ÐµÑÑ‚Ð²ÐµÐ½Ð½Ð¾.\nÐ’Ñ–ÑÑ–Ð¼ Ñ„Ð¾Ñ€Ð¼Ð¸ Tai Chi, Ñ‰Ð¾ Ð¯Ð½ ÑÑ‚Ð¸Ð»ÑŽ Ð¢Ð°Ð¹ Ð§Ð¸, Ð¼Ð°Ñ” Ð² ', 'English', 71621, 'Entertainment', 'http://i.ytimg.com/vi/FzEQc7UjmM4/0.jpg', 'tai chi, demo, 8 form'),
(72, 'Apprendre facilement le vrai Tai Chi', 'http://www.youtube.com/watch?v=G4tUTpJV-so&feature=youtube_gdata', 1, '360', 'Apprendre facilement le vrai Tai Chi sur http://www.imineo.com/sante-bien-etre/bien-etre/tai-chi-qi-gong/tai-chi-authentique-facile-video-1687.htm\n\nLa mÃ©thode de Tai Chi par Zhang Xiao Yan championne de Chine\n\nL''art de la santÃ© n''a plus de secret pour Zhang Xiao Yan, multiple championne de Chine dans diffÃ©rents styles de kung-fu. Elle prÃ©sente maintenant une synthÃ¨se des nombreuses variantes de sa pratique inspirÃ©e du Tai Chi Chuan. Cette mÃ©thode permet ainsi d''aborder trÃ¨s facilement, chez soi ou en groupe, les aspects Ã©nergÃ©tiques et d''auto-dÃ©fense en pratiquant une gymnastique adaptÃ©e pour tous. La grande expÃ©rience de Zhang Xiao Yan dans l''enseignement de haut niveau favorise l''assimilation des principes Ã©lÃ©mentaires ainsi que la progression rapide dans l''apprentissage de l''art millÃ©naire du bien-Ãªtre.', 'Non-English', 133755, 'Tutorial', 'http://i.ytimg.com/vi/G4tUTpJV-so/0.jpg', 'tai chi, demo, tutorial '),
(74, 'Taiji quan yang style 108 application', 'http://www.youtube.com/watch?v=GtQXLjmDJVg', 3, '240', 'http://famedia.fr\r\nLes applications martiales de la forme des 108 mouvements de l''école Yang, avec aussi de très belles images réalisés sur le combat Taiji ou Sanshou.', 'Non-English', 172728, 'Tutorial,Application,Group demo', 'http://i.ytimg.com/vi/GtQXLjmDJVg/mqdefault.jpg', 'tai chi, demo, group, 108 applications'),
(76, 'tai chi 24 forms posterior view', 'http://www.youtube.com/watch?v=H9OWQMGRSlw', 6, '240', 'http://taichivideos.blogspot.com/', 'Non-English', 638042, 'Entertainment', 'http://i.ytimg.com/vi/H9OWQMGRSlw/mqdefault.jpg', 'yan style, tai chi, 24 forms'),
(77, 'Tai chi for beginners - Chen Style 1 Part 1', 'http://www.youtube.com/watch?v=HC-uJ10OWqw', 7, '720', 'Learn the basics of Tai chi for beginners from a real tai chi master. Master Wong tai chi available in Ipswich, Suffolk and online offers instruction with the best quality music and HD video. Yang style and Chen style form. Click here http://www.taichicombat.com/', 'English', 145843, 'Others', 'http://i.ytimg.com/vi/HC-uJ10OWqw/mqdefault.jpg', 'yang style, tai chi, demo, beginner '),
(79, 'Yang Style 24 Tai Chi Chuan', 'http://www.youtube.com/watch?v=hou57TxCvCo', 4, '240', 'Sifu Amin Wu - www.aminwutaichi.com Original Tai Chi instructional VCD video by Sifu Amin Wu (in Chinese version) available on website', 'Non-English', 214640, 'Others', 'http://i.ytimg.com/vi/hou57TxCvCo/mqdefault.jpg', 'yan style, tai chi, 24 form'),
(80, '32å¼å¤ªæ¥µåŠ (èƒŒå‘æ¼”ç·´ - é™³æ€å¦) / Taiji ', 'http://www.youtube.com/watch?v=hs96nNzRG6c&feature=youtube_gdata', 3, '240', '', 'Non-English', 68312, 'Tutorial', 'http://i.ytimg.com/vi/hs96nNzRG6c/0.jpg', 'demo, tutorial, tai chi'),
(81, 'Yang Tai Chi 42-Form', 'http://www.youtube.com/watch?v=HYGePdlaTEo', 6, '480', 'http://drpaulinebao.com Traditional Chinese Medical Doctor and International Tai Chi Champion Dr. Pauline Bao Performs Yang Tai Chi 42-Form.', 'English', 139037, 'Entertainment', 'http://i.ytimg.com/vi/HYGePdlaTEo/mqdefault.jpg', 'yan style, tai chi, demo, 42 form'),
(82, 'Tai Chi Taiji Self-defense Application Traditional', 'http://www.youtube.com/watch?v=I_bTr-aPnKY&feature=youtube_gdata', 4, '480', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong) meditation for internal energy healing, bio-energy, Shaolin and Wudang Taoist Kung-fu martial arts, Taiji Power Release (fajin), Taiji application, Bagua, Xingyi application. Tai Chi Health Ways host annual workshop with the top masters. See photos or videos of Chen Zhenglei, Li Deyin, Zhu Tiancai, Chen Xiaowang, Dan Lee, Su Zifang, Abraham Liu .... In this video, you will learn the fighting aspects of Traditional Yang Style Tai Chi.  The principles are based on Tai Chi Classics: to redirect or borrow an opponent''s force first, then strike his weak point.', 'English', 92860, 'Group demo', 'http://i.ytimg.com/vi/I_bTr-aPnKY/0.jpg', 'tai chi, defense, fight'),
(83, 'Master Daniel Tan Tai Chi Quan 24 Steps Yang Style', 'http://www.youtube.com/watch?v=ib2SNVjlbgQ', 8, '480', 'I bought the demonstration VCD on this during the 90s but only watched it last week. The 42 form Yang Style Taichi was modified from the original by a guy called Li De Yin, chief coriographer of Tang Taichi for the 11th Asian Game, chief judge for Chinese National Taiji quan and jian', 'Non-English', 92828, 'Tutorial,Application', 'http://i.ytimg.com/vi/ib2SNVjlbgQ/mqdefault.jpg', 'Tai Chi,Tutorial, Demo, Music'),
(85, 'tai chi yang style', 'http://www.youtube.com/watch?v=IFZUIgaxlsI', 9, '240', 'this is a short clip of a lady going through the yang tai chi 48 form (steps), tai chi is split into 3 different forms n this is just one of them', 'English', 650268, 'Tutorial', 'http://i.ytimg.com/vi/IFZUIgaxlsI/mqdefault.jpg', 'yan style, demo'),
(86, 'Cheng Man Ching Punches é„­æ›¼é’å‡ºæ‹³', 'http://www.youtube.com/watch?v=J02ryTop7V8&feature=youtube_gdata', 1, '480', 'This clip shows CMC how to get rid of holding and then punch.', 'English', 159539, 'Entertainment', 'http://i.ytimg.com/vi/J02ryTop7V8/0.jpg', 'demo, punches'),
(87, 'Build Your Chi Energy - An Introduction Martial Ar', 'http://www.youtube.com/watch?v=J2AqqB9NUW4&feature=youtube_gdata', 1, '360', 'My Natural Health Book on Amazon: http://goo.gl/3ILiqS\nMy Healthy Recipe DVD on Amazon: http://goo.gl/DJrXAo\nMy Natural Living Website: http://goo.gl/eXCpiK\nMy Autism Recovery Website: http://goo.gl/CsuatG\nHost Zoe Simpson explains how the development of your internal chi energy will increase your personal power.  Based on Chapter 9 from The Beginners Guide to Natural Living by Larry Cook.  \n\n\nqigong\ntaichi\ntaiji\nqi gong\nthai boxing\ntai chi chuan\nchi kung\nthai chi\nchi gong\ntai chi master\ntaijiquan\nyang chi\ntai chi yang\nchen chi\nthai kickboxing\ntao chi\nyang style\nwu chi\ntai chi classes\nkung fu school\ntaoist tai chi\nyang style tai chi', 'English', 62705, 'Entertainment,Others', 'http://i.ytimg.com/vi/J2AqqB9NUW4/0.jpg', 'tai chi, secret, energy'),
(88, 'Real Combat Tai Chi ..... Awesome!', 'http://www.youtube.com/watch?v=J45xOW9-CXI&feature=youtube_gdata', 10, '720', 'COMBAT TAI CHI DVD - Now Available! Click Here to Order:\nhttp://jakemace.com/kungfu/DVDs.html\n\nReal Combat Tai Chi.  Tai Chi Chuan is really said "Tai Ji Quan".  Tai Chi is Meditation in Motion.  In this video Jake Mace teaches you some Tai Chi Fighting Applications which will be best suited against a striking opponent.  Tai Chi or Tai Ji can be used in real fighting with throws, strikes, joint locks, joint manipulation, and knockouts!  Enjoy!\n\nHit "SUBSCRIBE", Click "Like", Leave a Comment Below, Enjoy:\n\n***"LIKE" Our Facebook Page Here: https://www.facebook.com/JakeMace.TaiChi\n***"Follow"  Jake Mace on INSTAGRAM at "JakeMaceTaiChi"\n***"Follow"  Jake Mace on Twitter at "KungFuUniverse"\n \n***Order a DVD Below!  Thanks! :)\n\nORDER JAKE''S YANG TAI CHI DVD HERE, (Free Shipping in USA):\nhttp://www.shaolinarizona.com/Site_2/DVDs.html\n\nORDER JAKE''S IRON BONE DVD Here (Free Shipping in USA):\nhttp://www.shaolinarizona.com/Site_2/DVDs.html\n\nPlease subscribe to my channel and my vlog channel! I m', 'English', 832772, 'Tutorial', 'http://i.ytimg.com/vi/J45xOW9-CXI/0.jpg', 'tai chi, combat, demo, tutorial'),
(89, 'L APPEL D ENERGIE 1er mouvement du tai chi', 'http://www.youtube.com/watch?v=J9rK1MzUiCk&feature=youtube_gdata', 19, '720', 'Tai Chi Chuan Yang Apprendre dÃ©tails du mouvement de la 1Ã¨re partie des 108 postures leÃ§on gratuite en video et musique - Par Maitre SHAO-BIN Champion D''Europe 2002 - Ecole Tai Chi Jade Ã®le de la Reunion - RÃ©alisation : Baltazhar Samilor, 2011 -  "L''Appel d''Energie", tel un rappel Ã  Soi-MÃªme est le 1er Mouvement du Tai Chi - PrÃ©cÃ©dÃ© d''une profonde immobilitÃ©, ce Mouvement se remplit de lui-mÃªme...Ecouter, ne rien chercher, ne rien forcer, pratiquer.... observer.... pratiquer..... RELAXATION GARANTIE', 'English', 90996, 'Entertainment,Others', 'http://i.ytimg.com/vi/J9rK1MzUiCk/0.jpg', 'tai chi, music'),
(90, 'Tai Chi - the 24 Forms', 'http://www.youtube.com/watch?v=JIZVuFr9SAM&feature=youtube_gdata', 34, '720', 'The most popular Tai Chi set\nTAI CHI - THE 24 FORMS \nDR PAUL LAM (service@taichiproductions.com)\nFind more information and place your order for the instructional DVD at: http://www.taichiproductions.com/\n\nTAI CHI - THE 24 FORMS \nThe ancient practice of tai chi is clinically proven to be one of the most effective exercises to improve health, fitness and relaxation. The 24 Forms is the most widely practiced tai chi set. Following an introduction to tai chi and its benefits, Dr Lam teaches unique qigong exercises and foundation movements which will enhance your energy.\n\nGIVE IT A TRY!\nYou will find out how easy it is to learn from Dr Lam''s virtual lesson format. He will guide you, step-by-step, through each movement of the 24 Forms. The forms will be taught from different angles â€” with close ups, repetitions and diagrammed illustrations. Each form will be divided into small sections so you can follow him with ease. Throughout the lessons, Dr Lam will explain the tai chi principles and h', 'English', 295903, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/JIZVuFr9SAM/0.jpg', 'tai chi, exercise, demo'),
(91, 'Tai Chi Yang style long form', 'http://www.youtube.com/watch?v=jJCz9tzWp5s', 10, '240', 'None', 'Non-English', 82030, 'Tutorial', 'http://i.ytimg.com/vi/jJCz9tzWp5s/mqdefault.jpg', 'yan style, long form, tai chi'),
(93, 'Yang Zhenduo - Forma de 13 posturas estilo Yang Tr', 'http://www.youtube.com/watch?v=Jrd7iEXln5I&feature=youtube_gdata', 2, '240', 'Esta forma fue creada por el Maestro Yang Zhen Duo, y en el siguiente pÃ¡rrafo, explica varios aspectos respecto a la creaciÃ³n de la misma:\r\n\r\n"En una gran cantidad de lugares, en el extranjero por ejemplo, mucha gente quiere practicar tai chi chuan pero cuando ven cuan larga es la forma tradicional sienten que es muy difÃ­cil. Han Hoong Wang de Michigan una vez me dijo que muchos de sus estudiantes no podÃ­an practicar la forma porque era muy larga y muy difÃ­cil para ellos. AsÃ­ es que luego, para hacer que mÃ¡s gente aÃºn practique tai chi chuan, y para reclutar mÃ¡s estudiantes, hice el "Tai Chi de Trece Posturas".\r\nOtros estilos ya crearon una forma de trece posturas, pero otras personas se habÃ­an rehusado previamente a arreglar una forma corta para el estilo Yang tradicional. Consistiendo de solo 13 movimientos, es muy simple.\r\nEn esta forma de trece posturas no hay movimientos de pararse en una pierna, ni de agacharse. De manera que es mÃ¡s simple para la gente mayor. AdemÃ¡s,', 'English', 52400, 'Entertainment', 'http://i.ytimg.com/vi/Jrd7iEXln5I/0.jpg', 'tai chi, demo, 13 moves'),
(94, 'Tai Chi Fighting......Awesome!', 'http://www.youtube.com/watch?v=Jw5mn15xv5o', 8, '480', 'COMBAT TAI CHI DVD - Now Available! Click Here to Order:\r\nhttp://jakemace.com/kungfu/DVDs.html\r\n\r\nORDER OUR YANG TAI CHI DVD BY CLICKING THE LINK BELOW:\r\nhttp://phoenixlongevityarts.com/Site_...\r\nIn this video lesson learn three meditative Tai Chi sequences and the self defense techniques that go along with them! Enjoy.\r\n\r\nThere are multiple levels of learning a skill and/or sport like Tai Chi or lets say golf!\r\nThe applications in this video are practical, they work, and they\re cut directly from the Yang Family Tai Chi Style! Very easy for beginners! Later we practice push hands, use more softness, practice fa jing, and use our opponents energy against them! :)\r\n\r\nHit "SUBSCRIBE", Click "Like", Leave a Comment Below, Enjoy:\r\n\r\n***"LIKE" Our Facebook Page Here: https://www.facebook.com/JakeMace.TaiChi\r\n***"Follow" Jake Mace on INSTAGRAM at "JakeMaceTaiChi"\r\n***"Follow" Jake Mace on Twitter at "KungFuUniverse"\r\n\r\n***Order a DVD Below! Thanks! :)', 'English', 555281, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/Jw5mn15xv5o/mqdefault.jpg', 'yan style, demo, tai chi'),
(95, 'Tai Chi Chuan.Forme "Yang". Partie 1, "La Terre".', 'http://www.youtube.com/watch?v=jYA_3BMF2d4', 3, '480', 'Tai Chi Chuan, Long Form Yang. 108 mouvements. Partie 1, la terre.', 'English', 192054, 'Entertainment', 'http://i.ytimg.com/vi/jYA_3BMF2d4/mqdefault.jpg', 'yan style, tai chi'),
(96, 'TaÃ¯ Chi Chuan, "Rassembler" puis "Parer d''une mai', 'http://www.youtube.com/watch?v=k53ltT3VVSM&feature=youtube_gdata', 4, '480', 'DÃ©tail d''un mouvement de la 1Ã¨re partie de la forme Yang.\r\nExtrait d''un DVD Ã©ditÃ© par HervÃ© GÃ©rard, enseignant diplÃ´mÃ© fÃ©dÃ©ral de niveau 4 en Tai Chi Chuan Qi gong, style Yang traditionnel.\r\nPlus d''informations sur www.taichi-hervegerard.com', 'English', 68690, 'Tutorial', 'http://i.ytimg.com/vi/k53ltT3VVSM/0.jpg', 'tai chi, demo, chuan style, tutorial'),
(97, 'æ¨æ°85å¼å¤ªæžæ‹³ï¼ˆYang style tai chi 85 form ', 'http://www.youtube.com/watch?v=kcl0o-Q7qpM', 10, '480', 'Master David Bao, Hua Ying Wushu & Tai Chi Academy\r\nwww.davidbao.com', 'Non-English', 84848, 'Entertainment,Application', 'https://i.ytimg.com/vi/ooL4Ej4utWw/mqdefault.jpg', 'Tai chi, demo, music'),
(99, '42 forms Yang Style Taiji Quan', 'http://www.youtube.com/watch?v=KKpXqi_DBTw&feature=youtube_gdata', 6, '480', 'I bought the demonstration VCD on this during the 90s but only watched it last week. The 42 form Yang Style Taichi was modified from the original by a guy called Li De Yin, chief coriographer of Tang Taichi for the 11th Asian Game, chief judge for Chinese National Taiji quan and jian. He was also a famous judge for Yang style Taichi internationally and a lecturer in China People University. The person demonstrating is Chen Si Tan, Taichi champion for 1993 International Wushu competition and 1990 Beijing 11th Asian Games. He won over 30 gold medals for Taiji Quan and known as Taiji prince.\r\n\r\nThe strokes were elegance for display, and it ends there.', 'English', 82024, 'Tutorial', 'http://i.ytimg.com/vi/KKpXqi_DBTw/0.jpg', 'yang style, demo, music'),
(100, 'Tai Chi Fighting! Taijiquan Martial Applications (', 'http://www.youtube.com/watch?v=kp2jWeaKrqI', 4, '720', 'Dr. Yang''s tai chi lineage can be traced back to the Yang family through Grandmaster Kao, Tao', 'English', 62969, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/kp2jWeaKrqI/mqdefault.jpg', 'Tai Chi,News, Tutorial'),
(101, 'Yang Style Taijiquan 103 form - Part 1', 'http://www.youtube.com/watch?v=kUnXFvDeGII', 116, '240', 'Yang Style Taijiquan 103 form part 1 by grandmaster Yang Zhenduo and master Yang Jun', 'Non-English', 231736, 'Tutorial', 'http://i.ytimg.com/vi/kUnXFvDeGII/mqdefault.jpg', 'yan style, demo, tutorial, tai chi'),
(102, 'Tai Chi Chuan Yang Style, Great San Shou', 'http://www.youtube.com/watch?v=l777Vq4q5zc', 2, '240', 'Made in a very systematic and detailed manner, this film shows the codified fight system of Yang style, the "Great San Shou", or more precisely "Dui Da" (the word San Shou concerns the free Chinese boxing).\r\n\r\nIn this dvd, you will enjoy the details of each sequence of both solo forms (Pao-chui or "forms of the cannonball bullet fist") slow and swift.\r\n\r\nThis work is follows with an application work with the partner, so that this wonderful combination can be complete. The author presents --after all the detailed sequences, a few applications on targets .', 'Non-English', 67128, 'Group demo', 'http://i.ytimg.com/vi/l777Vq4q5zc/mqdefault.jpg', 'yan style, tai chi, chuan style'),
(105, 'Wu Amin--Taichi Yang Style form 24 å´é˜¿æ•æ¨æ°', 'http://www.youtube.com/watch?v=lEXuQnBjTlY', 125, '240', 'None', 'Non-English', 56110, 'Tutorial', 'http://i.ytimg.com/vi/lEXuQnBjTlY/mqdefault.jpg', 'Sports, yang style, 24 form'),
(106, 'Two people mirror Tai Chi form 8', 'http://www.youtube.com/watch?v=lH4JZ6aqCbA', 4, '480', 'Two people mirror Tai Chi form 8', 'Non-English', 92453, 'Group demo', 'http://i.ytimg.com/vi/lH4JZ6aqCbA/mqdefault.jpg', 'yan style, group demo, tai chi'),
(107, 'Yang Family tai chi push hands', 'http://www.youtube.com/watch?v=LiQu_EroF-k', 11, '480', 'Push Hands talk and demonstration from the Open House on 10/13/2007 of the Yang Chengfu Tai Chi Center Seattle. Featuring Master Yang Jun and Lance Lu. yangfamilytaichi.com Part 2 of 2.', 'Non-English', 65091, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/LiQu_EroF-k/mqdefault.jpg', 'Tai Chi,Tutorial, Demo, push hand'),
(108, 'Yang Tai Chi for Beginners', 'http://www.youtube.com/watch?v=m4ccN_yYKlA', 11, '720', 'DVD available: http://ymaa.com/publishing/internal/t... This is a 11-minute clip from the DVD "Yang Tai Chi ro Beginners". It includes a section of the introduction, and a brief instructional segment.\r\n\r\nIn this five-hour DVD, Dr. Yang gives step-by-step instruction of the 108-movement Yang tai chi form, and explains the purpose of each movement. English subtitles.\r\n\r\nDVD available here:\r\nhttp://ymaa.com/publishing/internal/t...', 'English', 200132, 'Tutorial,Others', 'http://i.ytimg.com/vi/m4ccN_yYKlA/mqdefault.jpg', 'yan style, tai chi, beginner'),
(109, 'Tai Chi Chuan stile Yang: la forma 10', 'http://www.youtube.com/watch?v=mfw7rKKY6TU', 3, '240', 'Tai Chi Chuan stile Yang: la forma 10.\r\n\r\nPer scaricare i video di Tai Chi:\r\nhttp://taiji.de/taiji/head4e/index.htm', 'Non-English', 266080, 'Tutorial,Application', 'http://i.ytimg.com/vi/mfw7rKKY6TU/mqdefault.jpg', 'yan style, demo, tutorial, tai chi'),
(111, '8-form Tai Chi Demo (Back)', 'http://www.youtube.com/watch?v=MhWIIdVyWVs', 4, '360', '8-form Tai Chi Demo (Back)', 'English', 199075, 'Entertainment', 'http://i.ytimg.com/vi/MhWIIdVyWVs/mqdefault.jpg', 'yan style, tai chi, demo, music'),
(112, 'Taiji: Sun Style Tai Chi', 'http://www.youtube.com/watch?v=MQsxy5z-zxE', 6, '240', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts.', 'English', 128430, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/MQsxy5z-zxE/mqdefault.jpg', 'Tai Chi,Tutorial, sun style'),
(113, 'FREE Tai Chi Lesson 1', 'http://www.youtube.com/watch?v=MXbwIfqSq_Q', 4, '480', 'Bill Douglas provides a free Tai Chi lesson of the Guang Ping Yang Style long forms 1st movement, Strike Palm.', 'English', 82713, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/MXbwIfqSq_Q/mqdefault.jpg', 'Tai Chi,Tutorial, lesson'),
(114, 'Tai Chi Sword Form 32 Yang Taiji Jian', 'http://www.youtube.com/watch?v=MxhAjv3YneM', 4, '240', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Tai Chi Health Ways host annual workshop with the top masters. See photos or videos of Chen Zhenglei, Li Deyin, Zhu Tiancai, Chen Xiaowang, Dan Lee, Su Zifang, Abraham Liu ... This is a simplified sword routine from the classic Yang Style Tai Chi Sword. Master Tsao teaches in detail with front and back view demonstrations.', 'Non-English', 634567, 'Weapon', 'http://i.ytimg.com/vi/MxhAjv3YneM/mqdefault.jpg', 'yan style,tai chi, 32 forms, sword'),
(116, 'Yang Style Tai Chi', 'http://www.youtube.com/watch?v=NKox-uJu6bo', 7, '480', 'http://www.taichidaily.com\r\nComplete Yang style tai chi chuan.', 'English', 212460, 'Others', 'http://i.ytimg.com/vi/NKox-uJu6bo/mqdefault.jpg', 'yan style, tai chi, demo'),
(118, 'Yang Style 32 Form Sword', 'http://www.youtube.com/watch?v=nrGZXgTP-ZA', 4, '240', 'Sifu Amin Wu - www.aminwutaichi.com Other original Tai Chi instructional VCD video by Sifu Amin Wu (in Chinese version) available on website', 'Non-English', 207209, 'Weapon', 'http://i.ytimg.com/vi/nrGZXgTP-ZA/mqdefault.jpg', 'yan style, tai chi, 32 form, sword'),
(119, 'ä¼ ç»Ÿæ¨å¼å¤ªæžæ‹³å…«åäº”å¼ï¼ˆ1ï¼‰Yang Style', 'http://www.youtube.com/watch?v=ooL4Ej4utWw', 8, '240', 'æ‰Žè¥¿\r\nhttp://www.56.com/u41/v_NTQ0NzU5OTA.html', 'Non-English', 214508, 'Entertainment,Application', 'https://i.ytimg.com/vi/ooL4Ej4utWw/default.jpg', 'tai chi, demo, yang style'),
(120, 'Tai Chi 10 Form, with English Titles', 'http://www.youtube.com/watch?v=P4Z4sQNQtJM', 3, '240', 'Tai Chi 10 Form (or 8 Form) with English titles inserted between postures; edited version of video copied from www.taiji.de. The performer is Gao Jiamin. According to Kungfu Magazine (July 2000 issue) she was born in Fuzhou City, Fujian Province, China June 26, 1966. At the time of the article she had "won 32 gold medals, a record that has never been achieved by any other competitor". She is (or was) a chief instructor at "US Wushu Center" in Portland, OR. The background music is "Willow in the Spring Breeze" from "Master of Traditional Chinese Music: Collection of Liu Beimaos Famous Pieces." The MP3 can be purchased from Amazon at http://www.amazon.com/gp/product/B000....', 'English', 414019, 'Tutorial', 'http://i.ytimg.com/vi/P4Z4sQNQtJM/mqdefault.jpg', 'yan style, tai chi, demo'),
(121, 'Daily Tai Chi - join in this 8-minute exercise', 'http://www.youtube.com/watch?v=PNtWqDxwwMg', 9, '480', 'TaiChiHealthProducts.org and VibrantHealthHappiness.com present an 8-minute "Easy Tai Chi" to do daily. We NO LONGER HAVE THE FREE DVD - but put an "Exercise" tab on our TaiChiHealthProducts website with all sorts of exercises to follow.\r\nJoin in with Don Fiore and see how you feel afterwards. Great for a senior fitness routine and home workout. Helps with balance, coordination, circulation, and strengthening bones and muscles. The movements come from our "Easy TaiChi-Qigong" DVD that can be ordered on TaiChiHealthProducts.org - a website for Holistic Health Tips and Exercises.\r\n\r\nIf you copy this video, you must include our entire description - and we do not allow people to use our videos for making money by placing advertising on them. Copyright 2012.\r\n\r\nThank you to all who "Like" this and "Subscribe" to our Channel.', 'English', 567216, 'Tutorial', 'http://i.ytimg.com/vi/PNtWqDxwwMg/mqdefault.jpg', 'yan style, tai chi, demo, tutorial'),
(123, 'Tai Chi Yang style 8-form.', 'http://www.youtube.com/watch?v=PWw-DAcSszM', 3, '240', 'Tai Chi Yang style 8-form (Chen Sitan).', 'Non-English', 250073, 'Tutorial', 'http://i.ytimg.com/vi/PWw-DAcSszM/mqdefault.jpg', 'yan style, tutorial, demo, tai chi'),
(124, 'Part 4 Tai Chi: Learn it Here Free: Yang Cheng-fu ', 'http://www.youtube.com/watch?v=qrdoP3ax4Ng', 5, '240', 'To the untrained eye, Tai Chi Chuan seems too slow for combat. However, these soft movements conceal effective self-defense techniques', 'English', 74898, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/qrdoP3ax4Ng/mqdefault.jpg', 'Tai Chi,Tutorial');
INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(125, 'Wu Tai Chi Taiji', 'http://www.youtube.com/watch?v=QSqfKRJotW4', 7, '240', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Tai Chi Health Ways host annual workshop with the top masters. See photos or videos of Chen Zhenglei, Li Deyin, Zhu Tiancai, Chen Xiaowang, Dan Lee, Su Zifang, Abraham Liu ... Master Tsao teaches the original Wu Style, from the Beijing area, also known as the Northern (Bei) Wu. He teaches step-by-step with full front and back view demonstrations. For higher-quality downloads and more videos, please see www.taichihealthways.com.', 'Non-English', 405481, 'Tutorial,Others', 'http://i.ytimg.com/vi/QSqfKRJotW4/mqdefault.jpg', 'yang style, demo, tutorial, tai chi'),
(126, 'Taiji: Chen Tai Chi Cannon Fist (Pao Chui)', 'http://www.youtube.com/watch?v=r6I9gf-Clac', 6, '240', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. ', 'Non-English', 137348, 'Entertainment', 'http://i.ytimg.com/vi/r6I9gf-Clac/mqdefault.jpg', 'Tai Chi,Tutorial, Demo, Music'),
(127, 'TAI CHI YANG STYLE - SLOW', 'http://www.youtube.com/watch?v=r7BRcfw98mk', 10, '480', 'http://www.silentthundercenter.org\r\nMaster Mokurai performing. Modified Yang style, done very slowly\r\nwith slow breathing.', 'Non-English', 110037, 'Tutorial', 'http://i.ytimg.com/vi/r7BRcfw98mk/mqdefault.jpg', 'yan style, demo, tai chi, slow motion'),
(128, 'Tai Chi Classic Yang Style', 'http://www.youtube.com/watch?v=rZHm-eNePI8', 3, '480', 'Tai Chi Classic Yang Style 1st part by Tung Huling', 'Non-English', 100438, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/rZHm-eNePI8/mqdefault.jpg', 'Tai Chi,Tutorial, yang style'),
(130, 'Tai Chi Chuan-The Complete Short Form', 'http://www.youtube.com/watch?v=SBIZciSHPgA', 6, '480', 'Renown Tai Chi Chuan teacher Paul Crompton demonstrates Yang Style Tai Chi Short Form from his Tai Chi Chuan-The Complete Short Form.', 'English', 97666, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/SBIZciSHPgA/mqdefault.jpg', 'yan style, demo, tai chi'),
(132, 'Cheng Man Ching Tai Chi Form', 'http://www.youtube.com/watch?v=sjV9bx9unxQ', 5, '240', 'Cheng Man Ching demonstrates his "simplified" Yang Style Tai Chi form', 'Non-English', 71706, 'Others', 'http://i.ytimg.com/vi/sjV9bx9unxQ/mqdefault.jpg', 'yan style, tai chi'),
(133, 'Tai chi for beginners - Chen style 2 Lesson 1', 'http://www.youtube.com/watch?v=sjzfA4dYMfg', 8, '720', 'Learn the basics of Tai chi for beginners from a real tai chi master. Master Wong tai chi available in Ipswich, Suffolk and online offers instruction with the best quality music and HD video. Yang style and Chen style form. Click here http://www.taichicombat.com/', 'English', 226344, 'Entertainment', 'http://i.ytimg.com/vi/sjzfA4dYMfg/mqdefault.jpg', 'yan style, demo, tai chi, beginer'),
(135, 'Master Heg Robinson - Telekinesis Demonstration | ', 'http://www.youtube.com/watch?v=sYW4yeBxMKA&feature=youtube_gdata', 5, '144', 'Telekinesis Master Heg Robinson (Boston, MAS.) \n\nHeg Robinson is my teacher''s teacher!', 'English', 56964, 'Tutorial', 'http://i.ytimg.com/vi/sYW4yeBxMKA/0.jpg', 'tai chi, demo, tutorial'),
(136, 'Tai Chi 24-form', 'http://www.youtube.com/watch?v=TBvF6r6DOvc', 4, '240', 'Tai Chi 24-form...\r\nIts a great martial art style. You should try it.', 'Non-English', 6001233, 'Tutorial', 'http://i.ytimg.com/vi/TBvF6r6DOvc/mqdefault.jpg', 'yan style, tutorial, demo, tai chi'),
(138, 'Tai Chi Application for Self-defense Fight in Chen', 'http://www.youtube.com/watch?v=tEbupVWZ6mk', 3, '480', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong) meditation for internal energy healing, bio-energy, Shaolin and Wudang Taoist Kung-fu martial arts, Taiji Power Release (fajin), Taiji application, Bagua, Xingyi application. Tai Chi Health Ways host annual workshop with the top masters. See photos or videos of Chen Zhenglei, Li Deyin, Zhu Tiancai, Chen Xiaowang, Dan Lee, Su Zifang, Abraham Liu .... The martial aspect of Tai Chi is a hidden value of the ancient art. There are not enough references of Tai Chis applications in self-defense today because it has been de-martialized from its original fighting purpose to make its way into the general population. Master Tsao shares with you his research and 30 years of teaching experience in the major applications for Push Hands and self-defense in Chen Old Frame Routine One. Most of them are from Chen Zhenglei and Zhu Tiancais teachin', 'English', 737520, 'Group demo', 'http://i.ytimg.com/vi/tEbupVWZ6mk/mqdefault.jpg', 'yan style, group demo, tai chi'),
(139, 'Yang Taijiquan, 24 form', 'http://www.youtube.com/watch?v=tLxJsqV6qcM', 3, '144', 'This is full 24 form of Taijiquan Yang.', 'English', 558644, 'Entertainment', 'http://i.ytimg.com/vi/tLxJsqV6qcM/mqdefault.jpg', 'yan style, demo, tai chi, 24 forms'),
(140, 'Tai Chi Secret Movements, Applications & Peng, Lu,', 'http://www.youtube.com/watch?v=TsHek6oZYXU&feature=youtube_gdata', 2, '480', 'Check out his book How to Master Tai Chi Chuan''s Internal Secret at http://www.taichisecretmovements.com\n\nJoin him at Facebook Fan Page; http://www.facebook.com/#!/pages/Tai-Chi-Secret-Movements/147514718592749. \n\nTraining with Master Hiu who shares hidden methods on Internal Strength in his new book who sincerely hope that Tai Chi Chuan as precious gift from the Chinese to mankind can be spread far and wide to people all around the world.', 'English', 137508, 'Group demo', 'http://i.ytimg.com/vi/TsHek6oZYXU/0.jpg', 'tai chi, secret, demo'),
(141, 'Tai Chi Chuan - Chen Style Full Form', 'http://www.youtube.com/watch?v=U_yctN4uTQM&feature=youtube_gdata', 4, '720', 'Learn the moves from the movie tai chi zero! Master Wong offers training for beginners in Ipswich, Suffolk and online so you can learn to fight like a tai chi master! Click here http://www.taichicombat.com/', 'English', 53493, 'Application', 'http://i.ytimg.com/vi/U_yctN4uTQM/0.jpg', 'tai chi, demo, chen style, full form'),
(142, 'Yang Style Tai Chi Chuan - Great Grandmaster Hu Yu', 'http://www.youtube.com/watch?v=us5Teds_n_Y', 4, '720', 'Yang Style Tai Chi Chuan performed by Hu Yuen Chou. Master Hu was a personal student of Yang Cheng Fu, one of the most famous Tai Chi teachers of all time.', 'Non-English', 62381, 'Entertainment,Application', 'http://i.ytimg.com/vi/us5Teds_n_Y/mqdefault.jpg', 'Sports, demo, chuan style'),
(144, '42 positions form tai ji quan', 'http://www.youtube.com/watch?v=V58I502J86M', 6, '240', 'This is the Tai Chi Yang style 2nd form, also known as the competition form, which has 42 positions drawn mainly from Yang style, but also from Wu and Chen.\r\nIt is very nice, but complicated to learn', 'Non-English', 72251, 'Entertainment', 'http://i.ytimg.com/vi/V58I502J86M/mqdefault.jpg', 'yan style, tai chi, 42 positions'),
(145, 'Tai CHi: Old Yang Style: Part 1: Learn for Free: M', 'http://www.youtube.com/watch?v=vgtsr_KomDs', 9, '240', 'http://www.taijiworld.com I will be slowly putting up the first third of the Old Yang Style free to learn from.\r\nThis video teaches the Old Yang Style of Yang Lu-Chan. This is the Yang style before it was changed by Yang Cheng-fu to what we know today. The movements are not all slow. There are fa-jing (explosive energy) movements all through this form. It is quite energetic with leaping kicks and explosive punches. This style was taught to Erle Montaigue by Chang Yiu-chun, one of the main students of Yang Shou-hou, the Brother of Yang Cheng-fu. Shou-hou did not change his grandfathers style. This video, because it is quite long does not include the basic qigong. It teaches both the martial art of Taijiquan\r\nand the healing art. www.taijiworld.com', 'English', 72191, 'Others', 'http://i.ytimg.com/vi/vgtsr_KomDs/mqdefault.jpg', 'yan style, tai chi, old style'),
(146, 'Tai Chi (Chen style) -- First Routine, Montreal', 'http://www.youtube.com/watch?v=vMAjEsWaZ1s', 10, '240', 'Chen style Tai Chi.\r\nVisit: internalstyle.com from Montreal, Canada', 'English', 65218, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/vMAjEsWaZ1s/mqdefault.jpg', 'Tai Chi ,Tutorial, Demo, chen style'),
(147, 'Chen Man-Ching Short Tai Chi Form', 'http://www.youtube.com/watch?v=vsDPy7zMrA4', 9, '1080', 'This is a rare video of Chen Man-Ching performing the style of Tai Chi Chuan that we practice in our system. This is a short form of the Yang style Tai Chi Chuan. Im fifth generation down from Chen Man-Ching.', 'English', 365449, 'Tutorial', 'http://i.ytimg.com/vi/vsDPy7zMrA4/mqdefault.jpg', 'yan style, demo, short form'),
(149, 'Tai Chi self defense fight application Yang Style ', 'http://www.youtube.com/watch?v=W1ZkHc5xpmk', 2, '480', 'The martial application of Tai Chi. Internal Strength Qi Energy applied in self defense fighting. Fu Zhongwen student Xie Bingcan Yang style Tai Chi', 'Non-English', 80474, 'Group demo', 'http://i.ytimg.com/vi/W1ZkHc5xpmk/mqdefault.jpg', 'yan style, tai chi, demo, self defense'),
(151, 'Learn The Yang Cheng-fu Tai Chi Form Here Free', 'http://www.youtube.com/watch?v=w6NdsyK8zPE', 5, '240', 'http://www.taijiworld.com I will be putting up the whole of the Yang Cheng-fu form step by step leaning free of charge over the next few days.\r\nThis video is the beginners video. It is the basic Yang Cheng-fu Taiji form taught in a step by step way so that one is able to literally teach oneself. This is the one that most people buy first of all regardless of how advanced they are. Every movement is gone over, stopping and starting to show important parts. Also included on this tape is the all important basic QIGONG, which is the most integral part of anyones Tai Chi training. This basic form is comprised of around 300 postures all linked together in an all flowing graceful whole, which when performed daily will aid in the healing of the body and mind. At an advanced stage, these movements are able to be used also for external self defence. This form is more healing than martial art, although it is said that Yang Cheng-fu changed the form only enough to leave in the internal essence of ', 'English', 362353, 'Tutorial,Others', 'http://i.ytimg.com/vi/w6NdsyK8zPE/mqdefault.jpg', 'yan style, tutorial, demo, tai chi'),
(152, 'Tai Chi Wrestling (taijiquan shuai jiao)', 'http://www.youtube.com/watch?v=WD0LH09D0Vo&feature=youtube_gdata', 1, '240', 'http://www.ymaa.com/publishing/dvd/taichi_DVD/taiji_wrestling_shuai_jiao \r\n\r\nTaijiquan Shuai Jiao Wrestling Takedowns from Push Hands', 'English', 63202, 'Entertainment,Others', 'http://i.ytimg.com/vi/WD0LH09D0Vo/0.jpg', 'Tai chi, information, Wrestling'),
(153, 'Tai Chi Übungen/Yang Stil Tai Chi 103er Form (Taij', 'http://www.youtube.com/watch?v=XEbEjzsc35s', 2, '480', 'Yang Tai Chi Hamburg. Yang Stil Tai Chi Chuan. Hier zur Übung die Grundfiguren des Tai Chi, Vogel am Schwanz packen.', 'English', 94826, 'Tutorial,Application', 'http://i.ytimg.com/vi/XEbEjzsc35s/mqdefault.jpg', 'Tai Chi,Tutorial, Demo'),
(154, 'Tai chi for beginners - Yang style Form Lesson 1', 'http://www.youtube.com/watch?v=xlHGjYHyjmM', 7, '720', 'Learn the basics of Tai chi for beginners from a real tai chi master. Master Wong tai chi available in Ipswich, Suffolk and online offers instruction with the best quality music and HD video. Yang style and Chen style form. Click here http://www.taichicombat.com/', 'English', 391054, 'Tutorial', 'http://i.ytimg.com/vi/xlHGjYHyjmM/mqdefault.jpg', 'yang style, demo, tutorial'),
(156, 'Yang Tai Chi for Beginners - Dr. Yang, Jwing-Ming ', 'http://www.youtube.com/watch?v=YonmpJvwmKM', 4, '720', 'See the DVD: http://ymaa.com/publishing/internal/t... \r\nLearn Tai Chi step by step with Yang, Jwing-Ming. Master Yang instructs the complete Tai Chi form from the front, and shows each movement one-by-one from multiple angles. There is also a rear view of the form that you can simply follow-along with once you''re familiar with the movements. \r\n\r\nDr. Yang''s tai chi lineage can be traced back to the Yang family through Grandmaster Kao, Tao (&#39640;&#28644;) and his teacher Yue, Huanzhi (&#27138;&#22864;&#20043;), an indoor disciple of Yang, Chengfu (&#26954;&#28548;&#29995;).', 'Non-English', 146257, 'Tutorial,Application,Group demo', 'http://i.ytimg.com/vi/YonmpJvwmKM/mqdefault.jpg', 'group, beginner, tutorial'),
(157, 'Become a Tai Chi Master in 5 Steps!', 'http://www.youtube.com/watch?v=Yq3guYPRYzA&feature=youtube_gdata', 15, '720', 'Become a Tai Chi Master in 5 Steps!  These are my 5 Secrets to being the Ultimate practitioner of Tai Chi, Tai Ji Quan, and Qigong:\n\n#1:  Warm up Tai Chi Postures\n#2:  Practice of Solo Form\n#3:  Qi Gong Practice\n#4:  Stillness Meditation\n#5:  Tai Chi Fighting and/or Self Defense\n\nHit "SUBSCRIBE", Click "Like", Leave a Comment Below, Enjoy:\n\n***"LIKE" Our Facebook Page Here: https://www.facebook.com/JakeMace.TaiChi\n***"Follow"  Jake Mace on INSTAGRAM at "JakeMaceTaiChi"\n***"Follow"  Jake Mace on Twitter at "KungFuUniverse"\n\n***Order a DVD Below!  Thanks! :)\n\nORDER JAKE''S YANG TAI CHI DVD HERE, (Free Shipping in USA):\nhttp://www.shaolinarizona.com/Site_2/DVDs.html\n\nORDER JAKE''S IRON BONE DVD Here (Free Shipping in USA):\nhttp://www.shaolinarizona.com/Site_2/DVDs.html\n\nPlease subscribe to my channel and my vlog channel! I make new videos here everyday and make vlog''s about the Martial Arts way of life. \n-Jake Mace\n\nLook me up for a friend request on Facebook:  http://www.Facebook.com/JakeM', 'English', 131238, 'Tutorial', 'http://i.ytimg.com/vi/Yq3guYPRYzA/0.jpg', 'tai chi, defense, fight, secret'),
(159, 'Fu Zhongwen Yang-style Form Part 1', 'http://www.youtube.com/watch?v=zIpKW6AnKYw', 8, '240', 'Fu Zhongwen Yang-style Form Tai Chi.\r\n\r\nFu Zhongwen (1903-1994) was a respected Tai Chi Chuan teacher from China. From an early age, he had been a disciple of Yang Cheng-fu, and later a family member as he married Zou Kuei Cheng, the great-granddaughter of Yang Chien Hou.\r\n\r\nFu Zhongwen had dedicated his life to practicing and teaching Tai Chi. He was voted as one of the One Hundred Living Treasures of China and it was a great loss to the martial arts world and a greater loss to his family when he died in Shanghai on September 25, 1994 at age 92.', 'Non-English', 141141, 'Application', 'https://i.ytimg.com/vi/zIpKW6AnKYw/mqdefault.jpg', 'yang style, demo, tai chi'),
(160, 'Taiji: Chen Tai Chi Broadsword tai chi Dao', 'http://www.youtube.com/watch?v=zWhr9x5X7cM', 5, '480', 'Visit http://www.taichihealthways.com for more videos of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts.', 'English', 77378, 'Tutorial,Application', 'http://i.ytimg.com/vi/zWhr9x5X7cM/mqdefault.jpg', 'Tai Chi,Tutorial, Demo, Music, chen style');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fun_video`
--
ALTER TABLE `fun_video`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fun_video`
--
ALTER TABLE `fun_video`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=161;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
