-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 02, 2014 at 07:11 AM
-- Server version: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `cs174`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE IF NOT EXISTS `fun_video` (
`id` int(11) NOT NULL,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=291 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(2, 'judo grand slam paris 2013', 'http://www.youtube.com/v/-R_jlPDwu2I&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 26, '480', 'GRAND SLAM MATCH IN PARIS 2013!', 'English', 261224, 'Entertainment', 'http://i.ytimg.com/vi/-R_jlPDwu2I/mqdefault.jpg', 'grand, slam, judo, ippon, highlight,'),
(3, 'judo in movies', 'http://www.youtube.com/v/1BmDS8IxSaM', 9, '480', 'clips from movies with judo', 'English', 227236, 'Entertainment', 'http://i.ytimg.com/vi/1BmDS8IxSaM/mqdefault.jpg', 'movies, judo, Seoi-Nage, Motivation, Martial-Arts'),
(4, 'judo grand slam salvador 2012', 'http://www.youtube.com/v/3YIaRXkWq_M&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 26, '480', 'fun match in 2012 in salvador', 'English', 149092, 'Entertainment', 'http://i.ytimg.com/vi/3YIaRXkWq_M/mqdefault.jpg', 'match, judo, grand, slam, salvador'),
(6, 'This is why i do judo', 'http://www.youtube.com/v/6BQ8tpTN5HE', 2, '480', 'best judo matches everrrrr', 'English', 1929412, 'Entertainment', 'http://i.ytimg.com/vi/6BQ8tpTN5HE/mqdefault.jpg', 'Judo, throws, beijing, 2008, koga, nomura, choi, uchishiba'),
(7, 'world championship judo paris 2011', 'http://www.youtube.com/v/7bXLjqciH9E&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 47, '480', 'paris 2011', 'English', 126083, 'Entertainment', 'http://i.ytimg.com/vi/7bXLjqciH9E/mqdefault.jpg', 'judo, IJF, ippon, uchimata, International Judo Federation, World Judo Tour, Grand Slam'),
(8, 'world championship judo japan 2010', 'http://www.youtube.com/v/aqbG6MBcT-4&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 47, '480', 'grand slam match in tokyo', 'English', 180570, 'Entertainment', 'http://i.ytimg.com/vi/aqbG6MBcT-4/mqdefault.jpg', 'judo, IJF, ippon, japan, International Judo Federation, World Judo Tour, Grand Slam'),
(10, 'Judo Grand Slam Paris 2013', 'http://www.youtube.com/v/AYvP_d9c1ns', 9, '720', 'Judo match with Kim sung min', 'English', 984528, 'Entertainment', 'http://i.ytimg.com/vi/AYvP_d9c1ns/mqdefault.jpg', 'slam down, grandslam, judo match'),
(11, 'best of judo', 'http://www.youtube.com/v/be-BoM-WokY', 3, '360', 'best judo matches', 'English', 4175073, 'Entertainment', 'http://i.ytimg.com/vi/be-BoM-WokY/mqdefault.jpg', 'judo, kano, ippons, sport, fight'),
(12, 'this is judo 2014', 'http://www.youtube.com/v/cJTVWcOrUHs', 6, '720', 'this is the world class sport judo', 'English', 85818, 'Application', 'http://i.ytimg.com/vi/cJTVWcOrUHs/mqdefault.jpg', 'Judo , Olympic Games , Martial Arts , Self-defense,  judo'),
(15, 'judo home training', 'http://www.youtube.com/v/IfeBqlpClJo', 3, '240', 'training at home judo', 'English', 116073, 'Others', 'http://i.ytimg.com/vi/IfeBqlpClJo/mqdefault.jpg', 'judo, home'),
(16, 'This is judo ', 'http://www.youtube.com/v/Imnc1XKtRs4&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 3, '480', 'a trailer describing judo', 'English', 480496, 'Entertainment', 'http://i.ytimg.com/vi/Imnc1XKtRs4/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(17, 'highlight video judo dusseldorf grand prix 2013', 'http://www.youtube.com/v/K7VLU1ivx2g&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 26, '480', 'fun match in dusseldorf', 'English', 228956, 'Entertainment', 'http://i.ytimg.com/vi/K7VLU1ivx2g/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport, match'),
(19, 'judo vs aikido', 'http://www.youtube.com/v/KLJPcChg1T4', 1, '240', 'a throwdown between 2 martial artists. judo vs akido ', 'Non-English', 1949103, 'Application', 'http://i.ytimg.com/vi/KLJPcChg1T4/mqdefault.jpg', 'judo, akido, vs, fight, throwdown'),
(20, 'judo motivation', 'http://www.youtube.com/v/mRM-iKdcfCk', 3, '240', 'what motivates me to do judo', 'English', 81692, 'Entertainment', 'http://i.ytimg.com/vi/mRM-iKdcfCk/mqdefault.jpg', 'judo, motivation, Judo , Martial Arts , Self-defense, sport'),
(21, 'judo throws LA valley college', 'http://www.youtube.com/v/OJKBdO74ygc', 7, '480', 'This video demos 15 basic throws in judo', 'English', 113622, 'Tutorial', 'http://i.ytimg.com/vi/OJKBdO74ygc/mqdefault.jpg', 'judo, college, basic, throw, tutorial, demonstration'),
(22, ' judo dusseldorf grand prix 2012', 'http://www.youtube.com/v/oT-ZoZ5aUIs&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 26, '480', 'highlights', 'English', 177683, 'Application', 'http://i.ytimg.com/vi/oT-ZoZ5aUIs/mqdefault.jpg', 'judo, match, highlights, master, throw'),
(23, 'Judo', 'http://www.youtube.com/v/pFM-xRKbSec', 1, '240', 'Compiled video of judo matches', 'English', 2740716, 'Tutorial', 'http://i.ytimg.com/vi/pFM-xRKbSec/mqdefault.jpg', 'judo, match, compilation, throw, people'),
(24, 'Mr Bean- Judo Class', 'http://www.youtube.com/v/pRZqRjxkHpk', 3, '480', 'Mr Bean attends a judo class but doesn''t want to be thrown by the teacher. From Back to School Mr Be', 'English', 16428888, 'Entertainment', 'http://i.ytimg.com/vi/pRZqRjxkHpk/mqdefault.jpg', 'mr, bean, judo, rowan atkinson, mr bean, judo class'),
(25, ' best Uchimata in international competition Judo', 'http://www.youtube.com/v/R43op-tg-_E', 3, '480', ' best Uchimata in international competition', 'English', 760058, 'Entertainment', 'http://i.ytimg.com/vi/R43op-tg-_E/mqdefault.jpg', 'judo, competition, uchimata, Judo , Martial Arts , Self-defense, sport'),
(26, 'highlights moscow grand slam 2012', 'http://www.youtube.com/v/sZ-suyYUY3k&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 0, '480', 'grand slam in moscow', 'English', 131986, 'Entertainment', 'http://i.ytimg.com/vi/sZ-suyYUY3k/mqdefault.jpg', 'highlight, judo, ippon, moscow, grand slam'),
(27, '7 Trojan Games Judo More Adwords', 'http://www.youtube.com/v/TTXPIYbOFJo', 1, '240', '7 trojan games judo', 'English', 2716440, 'Entertainment', 'http://i.ytimg.com/vi/TTXPIYbOFJo/mqdefault.jpg', 'trojan game, judo, fun, match, throw'),
(28, 'world masters judo 2012', 'http://www.youtube.com/v/UNYm3uMpJOE&list=UUeYa3QaP2n7I8SpGSqD-kUQ', 26, '480', 'top 15 judo players', 'English', 228213, 'Entertainment', 'http://i.ytimg.com/vi/UNYm3uMpJOE/mqdefault.jpg', 'top players, 16, judo'),
(29, 'Judo Explosive Moves', 'http://www.youtube.com/v/uPLCHw9QeAA', 4, '240', 'Zenbu Judo Club Sydney Promo', 'English', 2184076, 'Entertainment', 'http://i.ytimg.com/vi/uPLCHw9QeAA/mqdefault.jpg', 'judo, throwdown, club, sydney'),
(30, 'Trojan Games- Judo', 'http://www.youtube.com/v/yLKizQoejuw', 1, '240', 'A video of a British vs France match ', 'English', 3758822, 'Entertainment', 'http://i.ytimg.com/vi/yLKizQoejuw/mqdefault.jpg', 'match, game, britian, UK, France, best, fun'),
(32, 'Judo Training - Kodokan Japan', 'http://www.youtube.com/watch?v=_OSAMkS14Q0&list=PLazdls5cGqBklDJexf9JMMIaaYNCWLYU2', 18, '720', 'Goshin Judo in Scottsdale Arizona visits the Kodokan Judo Institute in Tokyo Japan', 'English', 97460, 'Tutorial,Group demo', 'https://i.ytimg.com/vi_webp/_OSAMkS14Q0/mqdefault.webp', 'judo, united states, group, throw, arizona'),
(33, 'Isao Okano - A Passion For Judo', 'http://www.youtube.com/watch?v=-2ip_gSTiUM', 46, '360', 'Isao Okano - amazing judoka', 'Non-English', 114940, 'Others', 'http://i.ytimg.com/vi/-2ip_gSTiUM/default.jpg', 'judo, documentary '),
(34, 'legends of judo', 'http://www.youtube.com/watch?v=-5OmdTaPzd8', 6, '480', 'the best judokas of the history : Koga, Jeon, Nomura, Inoue, Yamashita and Douillet\r\n', 'English', 741355, 'Entertainment', 'http://i.ytimg.com/vi/-5OmdTaPzd8/mqdefault.jpg', 'judo, best, history, historical'),
(35, 'CIRCUIT TRAINING JUDO OTHIS 1', 'http://www.youtube.com/watch?v=-5wMaosdLkk', 3, '480', '  Judo Tutorials', 'English', 134693, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/-5wMaosdLkk/mqdefault.webp', ' Judo, Fights, tutorial'),
(36, 'NAOHISA TAKATO - THE YOUNGSTER - JUDO COMPILATION', 'http://www.youtube.com/watch?v=-e9bjigFcvE', 6, '720', 'http://www.facebook.com/SushynatorPro...\r\n\r\nNaohisa Takato -60kg Japan', 'English', 66265, 'Entertainment,Others', 'https://i.ytimg.com/vi_webp/-e9bjigFcvE/mqdefault.webp', 'naohisa, takato, judo, compilation'),
(37, 'Part2: Newaza (ground grappling) techniques in Jud', 'http://www.youtube.com/watch?v=0_egtCExKt4', 42, '240', 'techniques in Judo ', 'English', 85399, 'Tutorial', 'http://i.ytimg.com/vi/0_egtCExKt4/mqdefault.jpg', 'Ground, Grappaling, Judo'),
(38, 'Human Weapon - Judo - Okuri eri jime', 'http://www.youtube.com/watch?v=0BSuwwOccf8', 21, '240', 'This is a Breakdown of a Move shown on the Tv show Human Weapon', 'English', 1378218, 'Entertainment', 'https://i.ytimg.com/vi/0BSuwwOccf8/mqdefault.jpg', 'Judo, Human Weapon Judo'),
(39, '''Judo Knight'' Putin shows off martial arts skills ', 'http://www.youtube.com/watch?v=0lxMglj8LuM', 2, '480', 'Prime Minister Vladimir Putin has taken another step to boost his charisma by holding a wrestling session with members of', 'Non-English', 911122, 'Application,Others', 'http://i.ytimg.com/vi/0lxMglj8LuM/mqdefault.jpg', 'vladimir putin judo,putin fighting,martial arts,black belt,training,MM'),
(40, 'TADAHIRO NOMURA é‡Žæ‘å¿ å® - THE WARRIOR - JUDO ', 'http://www.youtube.com/watch?v=0TSRWpatboc', 4, '720', 'http://www.facebook.com/SushynatorPro...\r\n\r\nTADAHIRO NOMURA, japanese Judo legend up to 60kg', 'English', 290661, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/0TSRWpatboc/mqdefault.webp', 'tadahiro, warrior, compilation'),
(41, 'Yoshida Breaks Arm 2000 Olympics Judo', 'http://www.youtube.com/watch?v=0XP9ETfGgA8', 1, '240', 'Ouch', 'Non-English', 476754, 'Application,Others', 'http://i.ytimg.com/vi/0XP9ETfGgA8/mqdefault.jpg', 'Judo,Yoshida,Honorato,Olympics,2000'),
(43, 'Judo and Gracie Barra BJJ Meet in San Jose State', 'http://www.youtube.com/watch?v=1dt-HYmMLOU', 4, '1080', 'Olympian Judoka Mike Swain and BJJ World Champion Flavio Almeida from Gracie Barra\r\n\r\nwww.dollamur.com', 'English', 73110, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi_webp/1dt-HYmMLOU/mqdefault.webp', 'sjsu, judo, bjj'),
(45, 'How To Throw People In Judo', 'http://www.youtube.com/watch?v=1M0jd8vw1E4', 3, '480', 'This guide shows you How To Throw People In Judo\r\n', 'English', 62430, 'Tutorial', 'http://i.ytimg.com/vi/1M0jd8vw1E4/mqdefault.jpg', 'judo, tutorial '),
(46, 'BJJ Purple Belt having fun with Judo Black Belt', 'http://www.youtube.com/watch?v=1oN6bqB0Ooo&list=PLIQ1WkUaRXqgIXmJgIcWZxdYIdYsSSuHD', 2, '720', 'A fun DEMONSTRATION for the kids to show them the importance of hard work and focus. The judokas in the blue kimonos are both Olympic hopefuls that train with Jason Morris Judo in NY. ', 'English', 76201, 'Tutorial,Entertainment,Application', 'https://i.ytimg.com/vi_webp/1oN6bqB0Ooo/mqdefault.webp', 'Olympic,work,focus'),
(47, 'Kodokan Judo: NAGE-NO-KATA', 'http://www.youtube.com/watch?v=1S8I76aPW7s', 43, '360', 'Kodokan Judo', 'English', 52310, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/1S8I76aPW7s/mqdefault.jpg', 'Kodokan, Judo'),
(49, 'Kyokushin vs Judo', 'http://www.youtube.com/watch?v=1Yn93MdJTUs', 7, '480', 'Andrews Nakahara (Kyokushin Mogi Dojo) vs Dong Sik Yoon (Judo)', 'English', 341418, 'Tutorial,Application', 'https://i.ytimg.com/vi_webp/1Yn93MdJTUs/mqdefault.webp', 'Judo , Martial Arts , Self-defense, sport'),
(51, 'Modern judo compilation by Garyants Gor', 'http://www.youtube.com/watch?v=2PTM964fh0Q', 4, '480', 'Another video by me! Hope you like it! watch and commenT!!!', 'English', 304244, 'Entertainment,Others', 'http://i.ytimg.com/vi/2PTM964fh0Q/mqdefault.jpg', 'compilation, the state of massachusetts'),
(52, 'Basic Judo - Trips and Throws to the Front', 'http://www.youtube.com/watch?v=31lUAp-PIrg', 5, '480', 'Basic Judo - Trips and Throws to the Front', 'English', 168160, 'Tutorial', 'http://i.ytimg.com/vi/31lUAp-PIrg/mqdefault.jpg', 'judo, tutorial, demo'),
(53, 'Leg breaking Judo throw, used in an MMA type fight', 'http://www.youtube.com/watch?v=3AsqR0Aw210', 1, '480', 'warning graphic....Judo fighter Breaks opponents leg throwing Kerry Saggers in UMAF (ultimate martial arts founder & competitor) as a fundraiser for lifeline. ', 'English', 556659, 'Application,Others', 'http://i.ytimg.com/vi/3AsqR0Aw210/mqdefault.jpg', 'JUDO,Kerry,Saggers,UMAF,Ultimate,martial,arts,fight,night,throw,Koshi,Guruma,MMA,Hip,Wheel,Boxing,shiai,broken,leg,break,cage,breaks,KO,knock,out,knockout,Martial Arts (Sport),Combat Sports,Wrestling,Belt,mixed,Submission,Tournament,Vale,Arm,Team,Pain,Sna'),
(54, 'Judo Lessons for Beginners : How to Do a Judo Big ', 'http://www.youtube.com/watch?v=3g4bl_QRF2g', 1, '480', 'Learn how to do a big hip throw in this free martial arts video from master Judo instructor Richard Acuna\r\n\r\nExpert: Richard Acuna', 'English', 268831, 'Tutorial', 'http://i.ytimg.com/vi/3g4bl_QRF2g/mqdefault.jpg', 'judo, teaching'),
(55, 'Allianz Judo Masterclass - Teaser', 'http://www.youtube.com/watch?v=3iTR-YlB2P0', 22, '480', 'Allianz félicite Loïc Pietri, sacré champion du monde de Judo dans la catégorie des - 81 kg., Loïc Pietri présente son Judo Master Class et vous guide jusquà la ceinture noire., Venez jouer avec lui sur :', 'Non-English', 1426512, 'Entertainment', 'https://i.ytimg.com/vi/3iTR-YlB2P0/mqdefault.jpg', 'allianz, judo, masterclass, teaser'),
(57, 'JUDO World Championships Teams - Salvador 2012', 'http://www.youtube.com/watch?v=3YIaRXkWq_M', 26, '480', 'JUDO World Championships Teams - Salvador 2012', 'English', 149479, 'Entertainment,Application', 'http://i.ytimg.com/vi/3YIaRXkWq_M/mqdefault.jpg', 'Championships, team, judo, salvador, 2012'),
(58, 'Mifune - The Essence of Judo (subbed)', 'http://www.youtube.com/watch?v=46veLgINFjU', 63, '480', 'I''m uploading this cuz it''s 50 years old and awesome.  His unthrowability sections at 25:25 and 56:45, and ne waza at 30:45 minutes may be some of the most important footage for judo ', 'Non-English', 326216, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/46veLgINFjU/mqdefault.jpg', 'judo,essence,of,mifune,aikido,ukemi,throw,martial,arts,10th,dan,master'),
(59, 'Judo White and Yellow Belt Requirements', 'http://www.youtube.com/watch?v=4SOLLf0efNQ', 8, '480', 'Judo White and Yellow Belt Requirements\r\n', 'Non-English', 59591, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/4SOLLf0efNQ/mqdefault.jpg', 'judo, demo'),
(60, 'Judo Newaza Grappling International Fights', 'http://www.youtube.com/watch?v=4u41omoNO4U', 7, '240', 'Highlights of Judo Newaza from International competitions. Link to full footage, http://www.fightingfilms.com/', 'English', 1665575, 'Entertainment', 'https://i.ytimg.com/vi/4u41omoNO4U/mqdefault.jpg', 'Judo Newaza Grappling, International Fights'),
(61, 'IPPON/JUDO HL', 'http://www.youtube.com/watch?v=5zEEZSbAk4o', 7, '240', 'Judo comp. of ippons.', 'English', 790974, 'Entertainment,Application,Others', 'http://i.ytimg.com/vi/5zEEZSbAk4o/mqdefault.jpg', 'Judo,Ippon,Throws'),
(62, 'Amazing OLD JUDO Throw Defense Mifune accepts chal', 'http://www.youtube.com/watch?v=63xMDIy3Xic', 6, '480', 'Amazing Old Judo throw defense mifune accepts challenges from high level students!', 'English', 1455965, 'Entertainment', 'https://i.ytimg.com/vi_webp/63xMDIy3Xic/mqdefault.webp', 'judo, mifune, old judo'),
(64, 'Judo Lessons for Beginners ', 'http://www.youtube.com/watch?v=6MLWUMrOYiA', 1, '480', 'Learn Knee Sweep of Judo  ', 'English', 142600, 'Tutorial', 'http://i.ytimg.com/vi/6MLWUMrOYiA/mqdefault.jpg', ' Judo, lessons'),
(65, 'El oso Berni - 1x48 - Judo', 'http://www.youtube.com/watch?v=7Bfsc2PLDho', 3, '240', 'BERNI el oso del CSD transmite valores deportivos a travÃ©s de sus aventuras', 'Non-English', 578917, 'Entertainment,Others', 'http://i.ytimg.com/vi/7Bfsc2PLDho/mqdefault.jpg', 'Oso,Berni,CSD,Consejo,superior,deportes,tve,educacion,fisica,educacionfisica'),
(66, 'How To Throw Someone At The Waist In Judo', 'http://www.youtube.com/watch?v=7klWd_tS_JE', 3, '480', 'This guide shows you How To Throw Someone At The Waist In Judo\r\n', 'English', 67487, 'Tutorial', 'http://i.ytimg.com/vi/7klWd_tS_JE/default.jpg', 'tutorial, Judo , Martial Arts , Self-defense, sport'),
(67, 'Classic Judo Gi Fold', 'http://www.youtube.com/watch?v=8mEHhsW_eYA', 3, '240', 'This is a video for our beginner judo players. It shows how to fold a judo uniform or judo gi. This is one way to fold it to keep the uniform nice and neat.', 'English', 58471, 'Tutorial', 'http://i.ytimg.com/vi/8mEHhsW_eYA/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport, demo'),
(68, 'JUDO vs TAEKWONDO - Real Fight 2014', 'http://www.youtube.com/watch?v=8pBOS8U9Fq8', 3, '360', 'Watch the best Martial Videos here►►► http://www.TaeSpeed.it', 'Non-English', 105092, 'Entertainment,Group demo', 'https://i.ytimg.com/vi/8pBOS8U9Fq8/mqdefault.jpg', 'fight,comparison'),
(69, 'Basic Judo - Arm Lock', 'http://www.youtube.com/watch?v=9gHQLT42Fl0', 3, '480', 'Basic Judo - Arm Lock', 'English', 102404, 'Tutorial', 'http://i.ytimg.com/vi/9gHQLT42Fl0/mqdefault.jpg', 'judo, tutorial, demo'),
(70, 'Judo(Yoshida) vs. Jujitsu(Royce Gracie)', 'http://www.youtube.com/watch?v=9pwMnKNNuDM', 11, '240', 'In this match, Royce Gracie decided the rules. No punch and kick on ground. and pulling opponent into ground work is prohibited.', 'Non-English', 2293737, 'Entertainment', 'https://i.ytimg.com/vi/9pwMnKNNuDM/mqdefault.jpg', 'Judo, Yoshida, Jujitsu, Royce Gracie'),
(71, 'Judo vs. Wrestling', 'http://www.youtube.com/watch?v=9UwxDGGcEIc', 2, '240', 'Judoka vs. Pro Wrestler\r\nBill Simpson is the Judoka vs. Frank Trigg is the Wrestler at Dale Cook''s 1995 ACE World Series of Martial Arts.\r\n\r\nWatch my other "vs" videos.', 'English', 791997, 'Application,Others', 'http://i.ytimg.com/vi/9UwxDGGcEIc/mqdefault.jpg', 'Judo,wrestling,jujitsu,bjj,submission,luta,livre,grappling,stefan,buben'),
(72, 'MONGOLIAN JUDO - JudoHeroes', 'http://www.youtube.com/watch?v=a4gz4c5bGj8', 5, '360', 'MONGOLIAN JUDO - JudoHeroes\r\n', 'English', 118864, 'Entertainment,Others', 'http://i.ytimg.com/vi/a4gz4c5bGj8/mqdefault.jpg', 'Mongolian, judo, application, variation'),
(73, 'JUDO MOTIVATION', 'http://www.youtube.com/watch?v=A5MhxPwU1Q8', 4, '720', 'Hey judokas! It has been a while since IÂ´ve uploaded a judo video last time! I know that you may be angry about that but there are few things and problems about making judo-based videos.\r\n', 'English', 56521, 'Entertainment', 'http://i.ytimg.com/vi/A5MhxPwU1Q8/mqdefault.jpg', 'judo, montage, motivation, application'),
(75, 'Judo vs. Aikido', 'http://www.youtube.com/watch?v=AssByvGVx6s', 5, '720', ' Staniszewski (Judo) X Barry B. (Aikido)', 'English', 870400, 'Entertainment', 'http://i.ytimg.com/vi/AssByvGVx6s/mqdefault.jpg', 'Judo, Aikido'),
(76, 'One love. Judo motivation', 'http://www.youtube.com/watch?v=AxtWtv8UI8Y', 5, '480', '"I want to represent possibilities. I want to represent an idea." - Will Smith', 'English', 56680, 'Others', 'http://i.ytimg.com/vi/AxtWtv8UI8Y/mqdefault.jpg', 'judo, motivation, weird, love'),
(78, 'Little Britain, Lou & Andy - Judo', 'http://www.youtube.com/watch?v=b0DvK7saV0I', 1, '240', 'lou is learning judo ', 'English', 1309871, 'Entertainment', 'https://i.ytimg.com/vi/b0DvK7saV0I/mqdefault.jpg', 'Judo, Little Britain, Lou & Andy'),
(80, 'The Art Of Judo (Highlights) | Olympics', 'http://www.youtube.com/watch?v=BhsBSmrTB-U', 3, '1080', 'Judo made its very first appearance at the Olympic Games in 1964 in Tokyo.', 'English', 71986, 'Tutorial,Entertainment', 'https://i.ytimg.com/vi/BhsBSmrTB-U/mqdefault.jpg', 'Games,Olympic,Tokyo'),
(81, 'Judo Training Hiroshi Katanishi', 'http://www.youtube.com/watch?v=BQQmh_kQ-Ew', 2, '480', 'Judo training and exercised', 'English', 86228, 'Tutorial', 'http://i.ytimg.com/vi/BQQmh_kQ-Ew/mqdefault.jpg', 'Exercises, Judo, Training'),
(82, 'Masahiko Kimura - judo techniques', 'http://www.youtube.com/watch?v=BVE82gH-v-g', 10, '360', 'Masahiko Kimura demonstrating judo techniques.He was over 60 that time, still in good shape.', 'Non-English', 1799108, 'Entertainment', 'https://i.ytimg.com/vi/BVE82gH-v-g/mqdefault.jpg', 'judo, masahiko kimura, judo techniques'),
(83, 'Crazy Judo throw!', 'http://www.youtube.com/watch?v=bZGTAVATPoI', 1, '480', 'Get Judo Fashion T-Shirts for free:\n\nhttp://www.judofashion.com/news/10/Judo-T%252dShirts-for-free.html', 'English', 465536, 'Entertainment,Others', 'http://i.ytimg.com/vi/bZGTAVATPoI/mqdefault.jpg', 'judo sport,sport,judo,judo videos,self defense,daily judo videos,combat sports,judo techniques,fighting,judo throws,martial arts,how to learn judo,judo lessons,fighting lessons,self defense lessons,fight,judo competitions,competitions'),
(84, 'defi mettre au tapis un champion de judo', 'http://www.youtube.com/watch?v=c3H3B5LL-Z0', 1, '240', 'attention qui si frotte si pique !', 'Non-English', 475665, 'Entertainment', 'http://i.ytimg.com/vi/c3H3B5LL-Z0/mqdefault.jpg', 'defi, judo, application, champion'),
(85, 'Judo Extreme', 'http://www.youtube.com/watch?v=cBaq5z6-eNQ', 3, '480', 'Judo Extreme', 'English', 575109, 'Entertainment', 'http://i.ytimg.com/vi/cBaq5z6-eNQ/mqdefault.jpg', 'judo, extreme, application, throw'),
(87, 'bolek i lolek judo', 'http://www.youtube.com/watch?v=CqKnRjd7Czg', 10, '360', '  Cartoon, Judo', 'Non-English', 107085, 'Entertainment', 'http://i.ytimg.com/vi/CqKnRjd7Czg/mqdefault.jpg', ' Cartoons, Fights, judo, animated'),
(89, 'Ronda Rousey: Armbar - Judo & MMA Highlight - Mole', 'http://www.youtube.com/watch?v=cwM5f42w8cw', 9, '1080', 'Ronda Rousey Judo, BJJ & MMA Career Highlight. Dana White, Jon Jones, Gina Carano, Nick Diaz, Nate Diaz, Randy Couture give their opinions on Ronda Rousey.', 'English', 886924, 'Entertainment,Application,Others', 'http://i.ytimg.com/vi/cwM5f42w8cw/mqdefault.jpg', 'MMA,Judo (Martial Art),WMMA,Ronda,Rousey,Highlight,Miesha,Tate,Sarah,Kaufman,Armbar,Cris,Cyborg,Strikeforce,UFC,Dana,White,Jon,Jones,Randy,Couture,Nick,Diaz,Nate,Gina,Carano,2012,HD'),
(90, 'Judo Semi-Finals Olympics 2012', 'http://www.youtube.com/watch?v=d8sFxkleXCw', 32, '1080', 'Full replay from the ExCeL ', 'English', 133074, 'Entertainment', 'http://i.ytimg.com/vi/d8sFxkleXCw/mqdefault.jpg', 'Olympics, 2012, Judo'),
(91, 'Judo for Jiu Jitsu - Basic Takedown - Dan Simmler', 'http://www.youtube.com/watch?v=DH8bPrOYBP8', 2, '720', 'In this episode of Judo for Jiu Jitsu, Dan Simmler shows us one of his favorite basic takedowns.', 'English', 68805, 'Tutorial', 'http://i.ytimg.com/vi/DH8bPrOYBP8/mqdefault.jpg', 'judo, teaching, tutorial'),
(93, 'JUDO MOTIVATION - OlympicJudo', 'http://www.youtube.com/watch?v=DKejlVKJZqQ', 3, '1080', '  Judo training for olympic', 'English', 126993, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/HCC8LpxyjpE/mqdefault.webp', ' Applications, Judo, Motivation'),
(94, 'Judo Techniques', 'http://www.youtube.com/watch?v=dygKP-25WLs', 4, '480', '\r\n\r\nThese are a few of my favorite techniques\r\n\r\n ', 'English', 953542, 'Entertainment,Application', 'http://i.ytimg.com/vi/dygKP-25WLs/mqdefault.jpg', 'Techniques, Moves'),
(95, 'MMA Judo', 'http://www.youtube.com/watch?v=dyygAG2aHW8', 5, '1080', 'MMA Surge Newsletter ', 'English', 101391, 'Tutorial', 'http://i.ytimg.com/vi/dyygAG2aHW8/mqdefault.jpg', 'MMA, Judo, Throws'),
(97, 'Brazilian Jiu-Jitsu VS Judo', 'http://www.youtube.com/watch?v=E5kFU9LrZH8', 1, '240', 'a fight between a black belt judo fighter and a blue belt BJJ fighter', 'Non-English', 1280587, 'Entertainment', 'https://i.ytimg.com/vi/E5kFU9LrZH8/mqdefault.jpg', 'Brazilian Jiujitsu vs Judo, Judo'),
(98, 'Advanced Judo Techniques : How to do a Directional', 'http://www.youtube.com/watch?v=e7q7vWRWOTc', 1, '480', 'Learn tips on doing this advanced Judo technique in this free martial arts video from master Judo instructor Richard Acuna', 'English', 183635, 'Tutorial', 'http://i.ytimg.com/vi/e7q7vWRWOTc/mqdefault.jpg', 'judo, teaching, tutorial'),
(99, 'Karo Parisyan, Judo For Mixed Martial Arts - Uchi-', 'http://www.youtube.com/watch?v=EdTVTObWeGs', 5, '240', 'http://www.groundfighter.com/ - UFC veteran Karo Parisyan demonstrates this traditional powerful Judo throw, the Uchi-Mata, mmodified for Mixed Martial Arts competition. ', 'English', 418786, 'Tutorial,Group demo', 'https://i.ytimg.com/vi/EdTVTObWeGs/mqdefault.jpg', 'UFC,Mixed Martial Arts,competition'),
(100, 'JUDO - Highlight Tokyo Grand Slam 2012', 'http://www.youtube.com/watch?v=EeXTu8mFFxo', 26, '480', 'Highlight of Tokyo Grand Slam 2012\r\n', 'Non-English', 184115, 'Entertainment,Others', 'http://i.ytimg.com/vi/EeXTu8mFFxo/mqdefault.jpg', 'judo, tournament'),
(101, 'Judo - Hairi Kata (sweep) - Kashiwazaki', 'http://www.youtube.com/watch?v=eVfHKSz4toQ', 4, '480', 'Some hairi kata (sweep) from Kashiwazaki video SHOW MORE', 'Non-English', 128697, 'Tutorial,Application', 'https://i.ytimg.com/vi/eVfHKSz4toQ/mqdefault.jpg', 'sports,application,fun,learn'),
(103, 'Top 10 Ippons', 'http://www.youtube.com/watch?v=fCo-VymBfkk', 3, '480', 'Top 10 Ippons', 'English', 1336923, 'Entertainment', 'https://i.ytimg.com/vi_webp/fCo-VymBfkk/mqdefault.webp', 'Judo, Top 10 Ippons'),
(104, 'Competitive Judo Training : Leg Sweep for Competit', 'http://www.youtube.com/watch?v=fjppdwr6tPE', 1, '480', 'How to take down judo opponent. Learn how to do a leg sweep drill in competitive judo in this free video clip on marital arts', 'English', 137566, 'Tutorial', 'http://i.ytimg.com/vi/fjppdwr6tPE/mqdefault.jpg', 'judo, teaching, tutorial'),
(105, 'Extreme Judo (HQ) - High Quality', 'http://www.youtube.com/watch?v=FlkAeYbNjEg', 4, '240', 'Wonderfull ippon collection...Olimpyc Games and World Championship is the base of this great video!!! ', 'Non-English', 797415, 'Tutorial,Entertainment,Others', 'https://i.ytimg.com/vi/FlkAeYbNjEg/mqdefault.jpg', 'judo, extreme, high quality, tutorial, ippon'),
(106, 'Street judo USA', 'http://www.youtube.com/watch?v=fMLDQ-FSKxM', 2, '360', '  Judo street fight in USA', 'English', 107018, 'Application', 'http://i.ytimg.com/vi_webp/fMLDQ-FSKxM/mqdefault.webp', ' Judo, USA'),
(107, 'Jigoro Kano', 'http://www.youtube.com/watch?v=FoFwE8pX2js', 3, '240', 'Kanō Jigorō was the founder of judo. Judo was the first Japanese martial art to gain widespread international recognition, and the first to become an official Olympic sport. ', 'English', 157036, 'Entertainment,Others', 'https://i.ytimg.com/vi_webp/FoFwE8pX2js/mqdefault.webp', 'history, founder, original, Judo , Martial Arts , Self-defense, sport'),
(108, 'girls betters boys in Bjj, Judo, MMA....!!', 'http://www.youtube.com/watch?v=fOofFfyeecc', 7, '240', 'Ooh poor boys...!! Humiliated, embarrassed and in tears....!?! The presence of the specatators also, increases their shame and their impotence...', 'English', 351723, 'Application,Others', 'http://i.ytimg.com/vi/fOofFfyeecc/mqdefault.jpg', 'boy,humiliated!, application, funny, fight'),
(109, 'Politician - Judo Fight in Parlament', 'http://www.youtube.com/watch?v=frMJjSstOXQ', 0, '240', 'This was a quite well done tomoe nage and a failed Taiotoshi.', 'English', 5571812, 'Entertainment,Others', 'http://i.ytimg.com/vi/frMJjSstOXQ/mqdefault.jpg', 'Politician,Politician Fight,Judo Fight,Parlament'),
(110, '67 Judo Throws of the Kodokan (1 of 3)', 'http://www.youtube.com/watch?v=fSwW7YRwvRk', 9, '360', '67 Judo Throws of the KodokanPart 1:http://www.youtube.com/watch?v=fSwW7YRwvRkPart 2:http://www.youtube.com/watch?v=geFk9opS_q8Part 3:http://www.youtube.com/watch?v=2DOYKwp5HzQ', 'English', 661123, 'Tutorial,Application', 'http://i.ytimg.com/vi/fSwW7YRwvRk/mqdefault.jpg', 'judo,throw,kodokan'),
(111, 'Tiago Camilo (BRA) x Jorge Benavides (CUB) Judo Pa', 'http://www.youtube.com/watch?v=fxgMS7Q6sa4', 2, '240', 'Tiago Camilo (BRA) x Jorge Benavides (CUB) Masc. até 90kg.', 'Non-English', 94273, 'Entertainment', 'https://i.ytimg.com/vi/fxgMS7Q6sa4/mqdefault.jpg', 'Judo, Tiago Camilo, Jorge Benavides'),
(112, 'DEFENSES EN JUDO DEBOUT', 'http://www.youtube.com/watch?v=G_nDtdqh-6Q', 7, '480', 'Par Maître René NAZARET 7ème dan de Judo\r\n(Directeur technique du Judo club de chassieu)', 'Non-English', 125695, 'Tutorial,Group demo', 'https://i.ytimg.com/vi/G_nDtdqh-6Q/mqdefault.jpg', 'defense,demo,grouptutorial'),
(113, 'Mongolian Judo training', 'http://www.youtube.com/watch?v=g-PZCMyubWg', 1, '240', '  Judo Training', 'English', 203274, 'Tutorial,Weapon,Group demo', 'http://i.ytimg.com/vi_webp/g-PZCMyubWg/mqdefault.webp', ' Judo, Mangolian, Trianing'),
(114, 'Powerful judo takedown', 'http://www.youtube.com/watch?v=GF-qtKkcyHU', 2, '240', '  Powerful Judo Takedown', 'Non-English', 319610, 'Application', 'http://i.ytimg.com/vi/GF-qtKkcyHU/mqdefault.jpg', ' Takedown, Judo'),
(115, 'Judo ippon', 'http://www.youtube.com/watch?v=gT-V8ZWJnuk', 4, '240', 'a video about judo\r\n', 'English', 564716, 'Entertainment', 'https://i.ytimg.com/vi/gT-V8ZWJnuk/mqdefault.jpg', 'fun,song,match'),
(117, 'æŸ”é“ JUDO - FIGHTING SPIRIT - JudoAttitude', 'http://www.youtube.com/watch?v=H-L-zspe5lQ', 5, '360', 'FIGHTING SPIRIT\r\n', 'Non-English', 58303, 'Entertainment,Others', 'http://i.ytimg.com/vi/H-L-zspe5lQ/mqdefault.jpg', 'judo, fighting, spirit, foreign, entertainment'),
(118, 'Judo Men 60 kg Final - Beijing 2008 Paralympic Gam', 'http://www.youtube.com/watch?v=hDrfmvfhR00', 1, '480', 'Judo Men 60 kg Final - Beijing 2008 Paralympic Games\r\nSHOW MORE\r\n', 'English', 252402, 'Entertainment,Others', 'http://i.ytimg.com/vi/hDrfmvfhR00/mqdefault.jpg', 'judo, tournament, final, beijing, 2008'),
(119, 'Judo - The Ultimate Martial Art', 'http://www.youtube.com/watch?v=Hglkf_xGdYM', 4, '480', 'a great judo movie\r\n', 'English', 113312, 'Entertainment', 'http://i.ytimg.com/vi/Hglkf_xGdYM/mqdefault.jpg', 'judo, movie, ultimate, martial, art'),
(120, 'K1 Finals 2006 Manhoef vs. Akiyama', 'http://www.youtube.com/watch?v=hNttRJ40QZE', 3, '360', 'Halbschwergewicht Finale im K1 zwischen Yoshihizo Akiyama (Judo) und Melvin Mandhoef (Kickboxing).', 'English', 1661854, 'Entertainment', 'https://i.ytimg.com/vi/hNttRJ40QZE/mqdefault.jpg', 'judo, kickboxing'),
(121, 'Judo Throw - MMA Surge, Episode 11', 'http://www.youtube.com/watch?v=Hoy9Eezydvo', 6, '1080', 'How to Pull It Off: 1. Hook your right arm under his left and put your hand on his left shoulder. 2. Grab his right tricep with your left hand. Youre now in over-under position.', 'English', 91845, 'Tutorial', 'https://i.ytimg.com/vi/Hoy9Eezydvo/mqdefault.jpg', 'Judo, Judo Throw'),
(122, 'female vs male judo (http://www.mixedmartialarts.e', 'http://www.youtube.com/watch?v=hqqho_rIvg8', 2, '480', 'female judoka beats a male in ajudo fight.\r\nTrailer from: http://www.mixedmartialarts.eu.com', 'English', 483117, 'Application,Others', 'http://i.ytimg.com/vi/hqqho_rIvg8/mqdefault.jpg', 'mixed,judo,wrestling,martial,arts,female,girl,women,lady,gi,fight'),
(123, 'judo chop pass out', 'http://www.youtube.com/watch?v=HstOX2dAuII', 1, '480', 'SIENA!', 'English', 347132, 'Others', 'http://i.ytimg.com/vi/HstOX2dAuII/mqdefault.jpg', 'college,funny,pain,prank'),
(124, '101 JUDO IPPONS 2009-2010', 'http://www.youtube.com/watch?v=HzfSzU8QIbY', 2, '480', 'DOWNLOAD NOW: http://www.fightingfilms.tv/r/x0l4w9kbg8 DVD AVAILABLE NOW:', 'Non-English', 689133, 'Entertainment,Application', 'http://i.ytimg.com/vi/HzfSzU8QIbY/mqdefault.jpg', 'DVD, advertising, 2009-2010'),
(125, 'Judo Rubber Band Training Part 1', 'http://www.youtube.com/watch?v=ib77CF4nxF0', 1, '480', 'Judo Rubber Band Training Part 1\r\n', 'English', 56418, 'Tutorial', 'http://i.ytimg.com/vi/ib77CF4nxF0/mqdefault.jpg', 'judo, demo'),
(127, 'THE TRUE STORY AND LEGEND OF JUDO', 'http://www.youtube.com/watch?v=IfW0pdd6xZ0', 52, '480', 'THE TRUE STORY AND LEGEND OF JUDO\r\n', 'English', 56727, 'Entertainment,Others', 'http://i.ytimg.com/vi/IfW0pdd6xZ0/mqdefault.jpg', 'judo, documentary '),
(128, 'Judo Flying Armbar', 'http://www.youtube.com/watch?v=ih4LJ3e4Y2g', 1, '240', 'Impressive Flying Armbar during a Judo tournament.', 'Non-English', 990877, 'Application,Others', 'http://i.ytimg.com/vi/ih4LJ3e4Y2g/mqdefault.jpg', 'Judo,Armbar,Arm,Bar,Flying,Jiu,Jitsu,Combat,Sports,Grappling,Tachi-waza,Newaza'),
(129, 'Basic Judo - Throws to a Ground Finish', 'http://www.youtube.com/watch?v=ilk3pGXgrmw', 2, '480', 'Basic Judo - Throws to a Ground Finish', 'English', 334012, 'Tutorial', 'http://i.ytimg.com/vi/ilk3pGXgrmw/mqdefault.jpg', 'judo,basic, teaching'),
(130, 'This is Judo II', 'http://www.youtube.com/watch?v=Imnc1XKtRs4', 3, '480', 'Judo Trailer', 'English', 482628, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/Imnc1XKtRs4/mqdefault.webp', 'trailer, judo  competition, epic'),
(131, 'Georgia vs Russia -Team Final - JUDO European Cham', 'http://www.youtube.com/watch?v=IMxtiU9binc', 51, '360', 'Georgia (GEO) vs Russia (RUS) - Team Final in Men - JUDO European Championships - 2014 Montpellier\r\n', 'Non-English', 138210, 'Entertainment', 'http://i.ytimg.com/vi/IMxtiU9binc/mqdefault.jpg', 'judo, tournament'),
(132, 'Judo scommetti che si caca addosso?', 'http://www.youtube.com/watch?v=IZLmooMwnKk', 1, '480', 'con http://www.williamhill.it/ si puÃ² scommettere anche sul judo, in questo video uno de 2  si caca addosso mentre schiena l''avversario. ', 'Non-English', 1260933, 'Application,Others', 'http://i.ytimg.com/vi/IZLmooMwnKk/mqdefault.jpg', 'judo,divertente,cacare,addosso,sport,video'),
(133, '101 Judo Ippons 06-08 - OUT ON DVD NOW!', 'http://www.youtube.com/watch?v=j1-HBMFVAOs', 3, '360', '  Judo Ippons', 'Non-English', 132857, 'Group demo', 'http://i.ytimg.com/vi/j1-HBMFVAOs/mqdefault.jpg', ' Judo,Ippons'),
(134, 'Judo vs Ninja', 'http://www.youtube.com/watch?v=JaO-x-wbXc8', 1, '240', 'This is from a martial arts demonstration on board the USS John C. Stennis in 2002. ', 'English', 338123, 'Application,Others', 'http://i.ytimg.com/vi/JaO-x-wbXc8/mqdefault.jpg', 'judo,vs,ninja,choke,ninjutsu,ninjitsu,randori'),
(135, 'Judo Throw: OSOTO GARI', 'http://www.youtube.com/watch?v=jcA45dsJh2w', 2, '240', '  Judo stands', 'English', 104067, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/jcA45dsJh2w/mqdefault.jpg', ' Judo, Tutorials, OSOTO GARI'),
(136, '26 Judo Techniques - Very fast, broken down', 'http://www.youtube.com/watch?v=jnM6WCMjekc', 4, '360', 'Video from a Japanese Advert, I''ve broken down each technique so that you can actually see what''s going on!', 'Non-English', 513482, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/jnM6WCMjekc/mqdefault.jpg', 'judo, demo'),
(137, 'JUDO MOTIVATION 2', 'http://www.youtube.com/watch?v=jSdXkYQEeqE', 5, '720', 'http://vimeo.com/71009926', 'English', 394338, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/jSdXkYQEeqE/mqdefault.webp', 'compilation, motivation, do not give up'),
(139, 'JUDO MOTIVATION', 'http://www.youtube.com/watch?v=jV3oXl6qJng', 4, '1080', '  Judo Triaining', 'English', 317777, 'Group demo', 'http://i.ytimg.com/vi/jV3oXl6qJng/mqdefault.jpg', ' Judo, Motivation'),
(140, 'UDO - Grand Prix 2013', 'http://www.youtube.com/watch?v=K7VLU1ivx2g', 26, '480', 'Highlight of the 2013 Dusseldorf Grand Prix', 'English', 229453, 'Entertainment', 'http://i.ytimg.com/vi/K7VLU1ivx2g/mqdefault.jpg', 'Highlights, Dusseldorf, Judo'),
(141, 'RUSSIAN JUDO - JUDO COMPILATION - OlympicJudo', 'http://www.youtube.com/watch?v=KCgdS7o_zFI', 6, '1080', 'Shinedown - Diamond Eyes\r\nhttps://www.facebook.com/olympic.judo\r\nhttp://vk.com/judoattitude', 'English', 112143, 'Entertainment,Others', 'http://i.ytimg.com/vi/KCgdS7o_zFI/mqdefault.jpg', 'shinedown, diamond, eyes, russian, judo, compilation'),
(142, 'Judo Throws & Moves : Hip Throw Judo Techniques', 'http://www.youtube.com/watch?v=kdqNzU9xZ6A', 1, '240', 'Learn how to perform the hip throw judo technique in this free Japanese martial arts training video.\r\n\r\nExpert: John T. Anderson', 'English', 163565, 'Tutorial', 'http://i.ytimg.com/vi/kdqNzU9xZ6A/mqdefault.jpg', 'judo, teaching, tutorial'),
(143, 'ronda rousey judo throwing bas rutten', 'http://www.youtube.com/watch?v=Kemcyzbz8j4', 1, '240', 'ronda rousey judo throwing bas rutten', 'English', 871244, 'Application,Others', 'http://i.ytimg.com/vi/Kemcyzbz8j4/mqdefault.jpg', 'rousey, throwing, judo, technique, ronda '),
(144, 'Judo mortal kombat', 'http://www.youtube.com/watch?v=khlXWzcaAoE', 3, '240', 'estrelas do judo com a musica mortal kombat\r\n', 'Non-English', 591003, 'Entertainment,Others', 'https://i.ytimg.com/vi/khlXWzcaAoE/mqdefault.jpg', 'tournament, Judo , Martial Arts , Self-defense, sport'),
(145, 'Judo basics: Tai otoshi tutorial', 'http://www.youtube.com/watch?v=KJ9EGSkcXnE', 2, '240', 'Matt is a 2008 Judo Olympian and Australian Purple belt Submission Grappling champion, for more info on learning more from Matt and his one on one training go to mattdaquino.com. ', 'English', 163260, 'Tutorial', 'http://i.ytimg.com/vi/KJ9EGSkcXnE/mqdefault.jpg', 'judo, teaching, tutorial'),
(147, 'Tying the judo belt', 'http://www.youtube.com/watch?v=ksKl1ptKUV8', 1, '240', 'A good way to tie your obi to keep it from coming loose easily.\r\nSHOW MORE\r\n', 'English', 520959, 'Tutorial,Others', 'http://i.ytimg.com/vi/ksKl1ptKUV8/mqdefault.jpg', 'judo, tutorial, demo'),
(148, 'HUMAN WEAPON JUDO TECHNIQUES', 'http://www.youtube.com/watch?v=KURLmHPMq8w', 2, '240', 'all about judo techniques on Human Weapon', 'English', 135763, 'Tutorial,Application', 'http://i.ytimg.com/vi/KURLmHPMq8w/mqdefault.jpg', 'Human,Weapon'),
(149, 'Judo (Budo: the art of killing)', 'http://www.youtube.com/watch?v=KViDIV1Jd6I', 8, '360', 'Judo (Budo: the art of killing)\r\n', 'English', 322946, 'Entertainment,Others', 'http://i.ytimg.com/vi/KViDIV1Jd6I/mqdefault.jpg', 'judo, variation, killing, application'),
(150, 'Karate vs Judo', 'http://www.youtube.com/watch?v=KzpMUSQIcS0', 3, '360', 'Malade !', 'English', 599764, 'Tutorial', 'https://i.ytimg.com/vi/KzpMUSQIcS0/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(151, 'The magnificent 2012. Judo', 'http://www.youtube.com/watch?v=L3zPXWMGhIc', 4, '480', 'The best moments of 2012.\r\n', 'English', 59123, 'Entertainment', 'http://i.ytimg.com/vi/L3zPXWMGhIc/mqdefault.jpg', 'judo, demo, compilation, best, 2012'),
(152, 'Judo Lessons for Beginners : Shoulder Technique fo', 'http://www.youtube.com/watch?v=LAXFKS0WrXU', 1, '480', 'Practice shoulder technique for Judo in this free martial arts video from master Judo instructor Richard Acuna', 'English', 77138, 'Tutorial', 'http://i.ytimg.com/vi/LAXFKS0WrXU/mqdefault.jpg', 'judo, teaching, tutorial'),
(153, 'Judo in the MMA', 'http://www.youtube.com/watch?v=lJ50D9sHRnM', 5, '480', 'Judo in the MMA ', 'English', 609179, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/lJ50D9sHRnM/mqdefault.jpg', 'MMA, Judo'),
(154, 'How To Do Judo Sweeps', 'http://www.youtube.com/watch?v=lOEa4f0AW0c', 2, '480', 'This guide shows you How To Do Judo Sweeps\r\n', 'English', 150104, 'Tutorial', 'http://i.ytimg.com/vi/lOEa4f0AW0c/default.jpg', 'judo, tutorial '),
(155, 'all 2012 story - London 2012, judo Korea Team Figh', 'http://www.youtube.com/watch?v=LYVaq-n8sV0', 2, '240', 'adidas korea all 2012 story \r\n\r\nLondon 2012, judo Korea Team Fighting!!!', 'English', 74541, 'Entertainment', 'http://i.ytimg.com/vi/LYVaq-n8sV0/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(156, 'Slick Judo Arm Bar', 'http://www.youtube.com/watch?v=M0oyerVmwTM', 1, '240', ' judo arm bar', 'Non-English', 1334441, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/M0oyerVmwTM/mqdefault.jpg', ' judo, demonstration, teacher, tutorial'),
(157, 'æŸ”é“ JUDO | No Sweet Without Sweat | JudoAttitud', 'http://www.youtube.com/watch?v=M5G-qAlPjSI', 5, '720', 'æŸ”é“ l No Sweet Without Sweat l JudoAttitude', 'English', 169031, 'Entertainment,Others', 'http://i.ytimg.com/vi/M5G-qAlPjSI/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(158, 'training at the korean judo team weightlifting roo', 'http://www.youtube.com/watch?v=m9mWr1MRE7U', 15, '480', 'can anybody put translation for the important parts', 'Non-English', 475006, 'Others', 'http://i.ytimg.com/vi/m9mWr1MRE7U/mqdefault.jpg', 'South Korea (Country),Judo (Martial Art),Training,Weight Training (Hobby),Martial Arts (Sport),Korea National Training Center (Building),Strength,Power,Workout,Exercise,íƒœë¦‰ì„ ìˆ˜ì´Œ'),
(159, 'SAMBO/Judo throws for MMA', 'http://www.youtube.com/watch?v=MbvPl4MCUys', 6, '240', '  Judo throws for MMA', 'English', 156883, 'Tutorial', 'http://i.ytimg.com/vi_webp/MbvPl4MCUys/mqdefault.webp', ' judo,throws, mma'),
(160, 'Judo', 'http://www.youtube.com/watch?v=MkuTkdzVb_0', 4, '240', 'Kyoto University', 'English', 1139896, 'Entertainment', 'http://i.ytimg.com/vi/MkuTkdzVb_0/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(161, 'GOLDBERG getting tossed by US Olympic...', 'http://www.youtube.com/watch?v=MqUMa99geyY', 1, '720', '  goldberg and olympoc judo expert', 'English', 918644, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/MqUMa99geyY/mqdefault.webp', ' Judo, Olympic, Goldberg,WWE'),
(162, 'judo vs karate', 'http://www.youtube.com/watch?v=mvWUC4SKlNg', 1, '360', 'judo efficiency: useful judo technics in karate competition', 'English', 754594, 'Entertainment,Application', 'http://i.ytimg.com/vi/mvWUC4SKlNg/mqdefault.jpg', 'useful, karate, efficiency'),
(163, 'Olympic Judo Goldmedalist', 'http://www.youtube.com/watch?v=N57od3JigUg', 3, '480', '2006 DOHA Asian Olympic Game \r\n-72kg Judo goldmedalist\r\nS.Korea Lee, wonhee\r\nHe won 2004 Olympic, world judo championship, and Asian Olympic.\r\nThis is grand slam in Judo', 'Non-English', 422165, 'Application,Others', 'http://i.ytimg.com/vi/N57od3JigUg/mqdefault.jpg', 'judo,olympic,gold,meldalist,grand,slam,korea,lee,won,hee'),
(164, 'Basic Judo - Falling', 'http://www.youtube.com/watch?v=NFPPrhxPFR4', 4, '480', 'Basic Judo - Falling', 'English', 107783, 'Tutorial', 'http://i.ytimg.com/vi/NFPPrhxPFR4/mqdefault.jpg', 'judo. tutorial '),
(165, 'Judoka: Judo Documentary, Doug Rogers, Part 1', 'http://www.youtube.com/watch?v=nkNkr0HuXlc', 10, '480', 'Judo Documentary, Doug Rogers a Canadain Judoka trains with Kimura in Japan\r\n', 'English', 86879, 'Others', 'http://i.ytimg.com/vi/nkNkr0HuXlc/mqdefault.jpg', 'documentary, history, judo'),
(166, 'Judo Throw Of Robber 001', 'http://www.youtube.com/watch?v=NmT9TGilEUc', 1, '240', 'Judo Throw Of  A Thief!  Hilarious!  Harai-Goshi is the name of the throw.  Foster''s Martial Arts FREE 30 Day Trial!  FREE Private Lesson!  www.MississippiBjj.com', 'English', 749986, 'Application,Others', 'http://i.ytimg.com/vi/NmT9TGilEUc/mqdefault.jpg', 'Judo Throw Robber Thief,Ocean,Springs,BJJ,MMA,Mississippi,Mixed Martial Arts'),
(167, 'Know Your Sport - Judo', 'http://www.youtube.com/watch?v=nqTDZDlHdrk', 1, '1080', 'Know Your Sport is a series of videos giving brief factoids about the Sports Played in Olympics -- Judo\r\n', 'English', 60507, 'Entertainment', 'http://i.ytimg.com/vi/nqTDZDlHdrk/mqdefault.jpg', 'judo, music'),
(168, 'æŸ”é“ JUDO - THE ORCHESTRA OF THROWS', 'http://www.youtube.com/watch?v=NsjPksu1juA', 6, '720', 'Tournament : Grand Slam Moscow 2012', 'English', 88498, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/NsjPksu1juA/mqdefault.webp', 'epic, throw down, of, judo, throws'),
(169, 'Judo Counters and Combinations Throws', 'http://www.youtube.com/watch?v=NUq8TPxk1GU', 5, '720', 'Judo Counter and Combination Throws by Grand Master George Logan From CT School of Survival A student of DR. Moses Powell [ EYE TO EYE..HEART TO HEART] ', 'English', 56274, 'Tutorial', 'http://i.ytimg.com/vi/NUq8TPxk1GU/mqdefault.jpg', 'judo, teaching, tutorial'),
(172, 'SAMURAI SPIRIT JUDO 2/5', 'http://www.youtube.com/watch?v=O_Ei3vMEsnU', 10, '720', 'samurai spirit cap judo parte 2', 'English', 67778, 'Tutorial,Entertainment,Others', 'http://i.ytimg.com/vi_webp/O_Ei3vMEsnU/default.webp', 'samurai, judo, documentary, info'),
(173, 'MAGIC JUDO 2012', 'http://www.youtube.com/watch?v=O_wOSGFjp0o', 6, '480', '  Magic judo ', 'English', 440326, 'Group demo', 'http://i.ytimg.com/vi_webp/O_wOSGFjp0o/mqdefault.webp', ' judo, 2012,magic'),
(174, 'Ronda Rousey Olympic Judo Champ', 'http://www.youtube.com/watch?v=O-L8YNut5zY', 8, '240', 'Hit me up on Facebook! http://www.facebook.com/#!/pages/Paulie-G/415263905162502', 'Non-English', 572164, 'Application,Others', 'http://i.ytimg.com/vi/O-L8YNut5zY/mqdefault.jpg', '70kg,Ronda,Rousey,USA,Mayra,Aguiar,BRA,United States,America,Judo'),
(175, 'Kids Judo Training', 'http://www.youtube.com/watch?v=o1__w7AF2Ig', 2, '360', 'Kids Judo Training\r\n\r\nChristchurch Judo School', 'English', 90765, 'Entertainment,Others', 'http://i.ytimg.com/vi/o1__w7AF2Ig/mqdefault.jpg', 'Judo ,kids,  Self-defense, training'),
(176, 'best of judo compilations', 'http://www.youtube.com/watch?v=O4UXvFeAkm0', 3, '720', 'best of judo\r\n', 'English', 273610, 'Entertainment', 'http://i.ytimg.com/vi/O4UXvFeAkm0/mqdefault.jpg', 'judo,compilation, best, entertainment'),
(177, '15 BASIC JUDO THROWS - LA VALLEY COLLEGE', 'http://www.youtube.com/watch?v=OJKBdO74ygc', 7, '480', 'Judo Class Demonstration (Skill Review Session) at LA Valley College on May 1st, 2013. ', 'English', 115007, 'Tutorial', 'http://i.ytimg.com/vi/OJKBdO74ygc/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(179, 'Advanced Judo Study - Kodokan Throws', 'http://www.youtube.com/watch?v=omycfCjQaaQ', 10, '480', 'USJA-USJF Grassroots Study Program based on "Kodokan Judo Throwing Techniques" by Toshiro Daigo, 10th Dan. volved from a 10 year study of modern throws used in competition, including the evolution from Jujutsu.', 'English', 191419, 'Tutorial', 'http://i.ytimg.com/vi/omycfCjQaaQ/mqdefault.jpg', 'judo, tutorial, demo'),
(180, 'demonstraÃ§Ã£o alguns golpes de judo', 'http://www.youtube.com/watch?v=Oqzfp8z3kdA', 10, '240', 'none', 'English', 258096, 'Tutorial', 'http://i.ytimg.com/vi_webp/Oqzfp8z3kdA/mqdefault.webp', 'Judo , Martial Arts , Self-defense, sport, demo'),
(181, 'Human Weapon - Judo - Juji Gatame', 'http://www.youtube.com/watch?v=oRWaVjrAjng', 1, '240', 'This is a Breakdown of a Move shown on the Tv show '' Human Weapon '' \r\nIf This has struck your interest, check out the show fridays on the History Channel', 'English', 1735468, 'Tutorial,Application', 'http://i.ytimg.com/vi/oRWaVjrAjng/mqdefault.jpg', 'Human,Weapon,Judo,Jason,Chambers,Bill,Duff,Jiu,Jitsu,Grappling,History,Channel,Uchi,Mata,Throw,Tapout,instrucion,takedow'),
(182, '74 Judo Throws in 2 Minutes', 'http://www.youtube.com/watch?v=OWW2pr04JUY', 2, '720', 'This video showcased Judo Olympian Matt D Aquino who is the creator of the Workouts For Judo. You can learn how Olympian get fit for Judo in his ground breaking book called Workouts For Judo', 'English', 73313, 'Entertainment', 'http://i.ytimg.com/vi/OWW2pr04JUY/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(183, 'Differences between Judo and BJJ Groundwork', 'http://www.youtube.com/watch?v=oZ3dtX5MNzQ', 5, '1080', 'Mike Lee (http://www.h2oma.com/) and Stephan Kesting (http://www.grapplearts.com) talk about the differences between BJJ groundwork and Judo newaza at', 'English', 179502, 'Tutorial,Application,Group demo', 'http://i.ytimg.com/vi/oZ3dtX5MNzQ/mqdefault.jpg', 'judo, vs, bjj, mike, lee, demonstration, learn '),
(184, 'Judo Kid Fights 10 kids and wins', 'http://www.youtube.com/watch?v=P0Sjb6fa2Gc', 9, '144', 'Noah fought in 2 divisions and won all 10 fights.', 'English', 62865, 'Entertainment,Others', 'http://i.ytimg.com/vi/P0Sjb6fa2Gc/mqdefault.jpg', 'home video, noah, wins'),
(185, 'TV reporter gets judo slammed ROFL', 'http://www.youtube.com/watch?v=P9_J04cVEeQ', 1, '480', 'gangsterserver.com | I dont think thats what she wanted when she asked the other girl to show her a move lol', 'Non-English', 370976, 'Entertainment', 'http://i.ytimg.com/vi/P9_J04cVEeQ/mqdefault.jpg', 'owned,judo,japanese,tv,reporter,funny,blooper'),
(188, 'Judo Fight', 'http://www.youtube.com/watch?v=piUKS6aiUGE', 4, '360', ' Judo Fight', 'English', 1052411, 'Entertainment,Application', 'http://i.ytimg.com/vi/piUKS6aiUGE/mqdefault.jpg', 'Judo Fight, application, entertainment, application'),
(190, 'Jiu-Jitsu (Team Mirza) vs. Judo (Black Belt)', 'http://www.youtube.com/watch?v=QdAgx-jRHo8', 48, '240', 'MoMirza blue belt for Team Mirza runs-over a Judo Black Belt in a BJJ Tournament in Amman, Jordan 2005., Team Mirza or Team Jordan has been competing since 2004. ', 'English', 1784018, 'Entertainment', 'https://i.ytimg.com/vi/QdAgx-jRHo8/mqdefault.jpg', 'judo, Jiu-Jitsu, team mirza, black belt'),
(191, 'Judo Lessons for Beginners : How to Do a Judo Back', 'http://www.youtube.com/watch?v=qq2ph1hgAM0', 1, '480', 'Learn how to do a back roll with this online Judo lesson for beginners in this free martial arts video from master Judo instructor Richard Acuna', 'English', 52196, 'Tutorial', 'http://i.ytimg.com/vi/qq2ph1hgAM0/mqdefault.jpg', 'judo, learn, tutorial, beginner, back'),
(192, 'Judo Uchi Mata', 'http://www.youtube.com/watch?v=QQjMkHGU_Ic', 1, '240', '  Judo Uchi Mata', 'English', 130682, 'Tutorial', 'http://i.ytimg.com/vi_webp/QQjMkHGU_Ic/mqdefault.webp', 'Uchi Mata, Judo\r\n'),
(193, 'Judo en la vida real', 'http://www.youtube.com/watch?v=QTdN750zAjU', 1, '240', 'Aplicando un poco de Judo.', 'Non-English', 53945, 'Application,Others', 'https://i.ytimg.com/vi/QTdN750zAjU/mqdefault.jpg', 'Judo , Martial Arts , Self-defense, sport'),
(194, 'Judo Vs Muay Thai', 'http://www.youtube.com/watch?v=QvXjF1oadgk', 4, '480', 'David Fernandez is not a BJJ practitioner. In the video its says he is a Judoka, and look at his Gi.. ', 'English', 1964875, 'Entertainment', 'https://i.ytimg.com/vi_webp/QvXjF1oadgk/mqdefault.webp', 'judo, muay thai, vs'),
(195, 'SAMURAI SPIRIT JUDO 1/5', 'http://www.youtube.com/watch?v=qXHXgLDEQEw', 11, '720', 'samurai spirit cap judo parte 1', 'English', 144425, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/qXHXgLDEQEw/mqdefault.webp', 'samurai, judo, documentary, info, victory, birth, of, judo'),
(196, 'Judo Lessons for Beginners : How to Do a Judo Fron', 'http://www.youtube.com/watch?v=rizlP_I0E6c', 1, '480', 'Learn how to do a front fall with a roll in this free martial arts video from master Judo instructor Richard Acuna', 'English', 107986, 'Tutorial', 'http://i.ytimg.com/vi/rizlP_I0E6c/mqdefault.jpg', 'judo, learn, tutorial, front, fall, roll');
INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(197, 'Judo Lessons for Beginners : How to Do a Judo Hip ', 'http://www.youtube.com/watch?v=RLM6C9ICQo8', 1, '480', 'Learn how to do a hip throw in this free martial arts video from master Judo instructor Richard Acuna', 'English', 72992, 'Tutorial', 'http://i.ytimg.com/vi/RLM6C9ICQo8/mqdefault.jpg', 'judo, learn, tutorial, hip, throw'),
(198, 'Judo Olympic Preparation', 'http://www.youtube.com/watch?v=rLSFY-zyAmc', 10, '480', 'Aurelien Broussal Derval is thinking about 3 years of Strength and conditioning at BJPI for London Olympics with Judo GB', 'English', 201387, 'Entertainment,Others', 'http://i.ytimg.com/vi/rLSFY-zyAmc/mqdefault.jpg', 'preparation, olympic, training, workout'),
(199, 'SAMURAI SPIRIT JUDO 3/5', 'http://www.youtube.com/watch?v=rPS3X9v9siY', 9, '720', 'samurai spirit cap judo parte 3', 'English', 54733, 'Tutorial,Entertainment,Others', 'http://i.ytimg.com/vi_webp/rPS3X9v9siY/default.webp', 'samurai, judo, documentary, info'),
(200, 'JAPANESE JUDO - JUDO COMPILATION - OlympicJudo ', 'http://www.youtube.com/watch?v=rrfdHBxK6iI', 3, '1080', 'Japanese Judo recompilation ', 'Non-English', 236342, 'Entertainment', 'https://i.ytimg.com/vi/rrfdHBxK6iI/mqdefault.jpg', 'japan, Japanese, compilation, olympic'),
(201, 'Harai Goshi knock out from throw', 'http://www.youtube.com/watch?v=rRNHFuNL0mc', 7, '360', 'MMA fight Cory Devela vs Joe Riggs. KO from judo throw.', 'English', 580269, 'Application,Others', 'http://i.ytimg.com/vi/rRNHFuNL0mc/mqdefault.jpg', 'Harai,Goshi,Tai,Otoshi,Judo,waza,nage,MMA,Vale,Tudo,Shooto,Japan,Brazil,Gracie,submissions,knockout,grappling,martial,arts,combat,sports,extreme,winter,action'),
(203, '10 minutes Judo knowledge of Masahiko Kimura', 'http://www.youtube.com/watch?v=s_QPTB2iEp8', 10, '240', '  Judo Knowledge of Masahiko Kimura', 'Non-English', 129345, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/s_QPTB2iEp8/mqdefault.jpg', ' Judo, Masahiko Kimura'),
(204, 'PELEA CALLEJERA GORDO CONTRA FLACO JUDO', 'http://www.youtube.com/watch?v=SvYB54feG5A', 41, '240', 'PELEAS CALLEJERAS!!', 'Non-English', 4232930, 'Entertainment', 'https://i.ytimg.com/vi/SvYB54feG5A/mqdefault.jpg', 'judo, pelea callejera'),
(205, 'Judo Turtle Attacks for BJJ', 'http://www.youtube.com/watch?v=SwCFHD48Eq4', 6, '1080', '  Judo turtle move', 'English', 94362, 'Tutorial,Group demo', 'http://i.ytimg.com/vi_webp/SwCFHD48Eq4/mqdefault.webp', ' Turtle Attack, Judo'),
(206, 'Modern Japanese Judo', 'http://www.youtube.com/watch?v=t4YlDaUYqFQ', 2, '480', '  Japanese Judo', 'English', 146684, 'Group demo', 'http://i.ytimg.com/vi_webp/t4YlDaUYqFQ/mqdefault.webp', ' Demo, Judo, Japanese'),
(208, 'I''m a Mormon, Trainer, and National Judo Champ', 'http://www.youtube.com/watch?v=U-EJYR6rdZQ', 3, '1080', 'Karina Tapia Navas does not back down from a challenge. Whether it''s the national championships or keeping this Mormon Judo master healthy, she''s ready to win. http://www.mormon.org/Karina', 'English', 13736363, 'Others', 'http://i.ytimg.com/vi/U-EJYR6rdZQ/mqdefault.jpg', 'mormon,costa rica,judo,judoka,discipline,healthy living,competition,national judo gold medalist'),
(210, 'Advanced Judo Techniques : How to Do an Arm Bar Te', 'http://www.youtube.com/watch?v=U3XCuc6_Umo', 1, '480', 'Learn what to do when your partner fails an attempt to throw in this free martial arts video from master Judo instructor Richard Acuna', 'English', 177365, 'Tutorial', 'http://i.ytimg.com/vi/U3XCuc6_Umo/mqdefault.jpg', 'judo, teaching, tutorial'),
(211, 'Judo highlight', 'http://www.youtube.com/watch?v=u8ZUhCVPFm4', 4, '1080', 'A mix of various highlights from youtube merged into one vid. No profit was made in the making of this video.', 'English', 102350, 'Entertainment', 'http://i.ytimg.com/vi/u8ZUhCVPFm4/mqdefault.jpg', 'judo, highlights, compilation, best'),
(212, 'Olympic training - Korean Judo', 'http://www.youtube.com/watch?v=ufodZ2hTO-A', 13, '240', 'Please Like this video, Share it on Facebook, Subscribe to our Channel.', 'Non-English', 208326, 'Tutorial,Group demo,Others', 'https://i.ytimg.com/vi_webp/ufodZ2hTO-A/mqdefault.webp', 'Judo , Martial Arts , Self-defense, sport'),
(215, 'Judo Lessons for Beginners : How to Do Judo Sweeps', 'http://www.youtube.com/watch?v=UNQ_0-k3jnE', 1, '480', 'Learn how to do sweeps with this online Judo lesson for beginners in this free martial arts video from master Judo instructor Richard Acuna', 'English', 166438, 'Tutorial', 'http://i.ytimg.com/vi/UNQ_0-k3jnE/mqdefault.jpg', 'judo, learn, sweeps, lesson'),
(217, 'Suicide Room - Judo Scene', 'http://www.youtube.com/watch?v=Uq2oFfTlwu8', 2, '480', '  Judo Fight Scene', 'English', 111859, 'Entertainment', 'http://i.ytimg.com/vi_webp/Uq2oFfTlwu8/mqdefault.webp', ' Judo, Movies, fight, application'),
(219, 'Judo Lessons for Beginners : How to Do a Hook to t', 'http://www.youtube.com/watch?v=uU659vSwutM', 1, '480', 'Learn how to do a hook to the side throw in this free martial arts video from master Judo instructor Richard Acuna', 'English', 140566, 'Tutorial', 'http://i.ytimg.com/vi/uU659vSwutM/mqdefault.jpg', 'judo, learn, tutorial, side, hook, throw'),
(220, 'The Gokyo (techniques in Judo) by Neil Adams', 'http://www.youtube.com/watch?v=Uy5ZMus1wNQ', 57, '240', 'The Gokyo, as selected by the Kodokan, lies at the very heart of judo and is studied throughout the world by beginners and black belts alike. ', 'English', 267238, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/Uy5ZMus1wNQ/mqdefault.jpg', 'judo, documentary , demo'),
(221, 'judo vs jujutsu', 'http://www.youtube.com/watch?v=v2wO3dHUYwQ', 4, '240', 'Kimura Masahiko vs HÃ©lio Gracie', 'Non-English', 448345, 'Application,Others', 'http://i.ytimg.com/vi/v2wO3dHUYwQ/mqdefault.jpg', 'judo,jujutsu'),
(222, 'Judo Throws - Katsuhiko Kashiwazaki', 'http://www.youtube.com/watch?v=v3HisfQ3jL8', 10, '480', 'Tomoe Nage, Uki Waza, Hikikomi Gaeshi, Ouchi Gari, combinations and more.\r\n', 'English', 119032, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/v3HisfQ3jL8/mqdefault.jpg', 'judo, demo, sports'),
(223, 'Putin practices judo - No comment', 'http://www.youtube.com/watch?v=V5z5UAtCxgE', 2, '480', ' Judo Training', 'Non-English', 353694, 'Group demo', 'http://i.ytimg.com/vi_webp/V5z5UAtCxgE/mqdefault.webp', 'Judo , Martial Arts , Self-defense, sport'),
(224, 'Aikido Judo at a Distance 1', 'http://www.youtube.com/watch?v=v63kDBfZxa0', 46, '720', 'Aikido Judo', 'English', 72474, 'Tutorial', 'http://i.ytimg.com/vi/v63kDBfZxa0/mqdefault.jpg', 'Aikido, Judo, tutorial, learn'),
(225, 'æŸ”é“ JUDO MOTIVATION', 'http://www.youtube.com/watch?v=V9uQdbHpSyM', 6, '720', 'Music "Diamond Eyes (Boom-Lay Boom-Lay Boom) [Live From Washington State]" by Shinedown ( â€¢ â€¢ )', 'English', 86783, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/V9uQdbHpSyM/mqdefault.webp', 'motivation, judo, diamond, eyes'),
(227, 'Royce Gracie v.s. Judo', 'http://www.youtube.com/watch?v=vkwCwFEPpQM', 45, '240', 'Royce Gracie enters a judo tournament', 'English', 1765202, 'Entertainment', 'http://cdn.vectorstock.com/i/composite/31,06/judo-design-elements-vector-233106.jpg', 'judo, royce gracie, vs'),
(228, 'Zantaraia Judo Training', 'http://www.youtube.com/watch?v=vR6Nhhy6IY0', 6, '720', 'Judoka Georgii Zantaraia (-66) shows his defenses.\r\nAmazing way how to avoid falling on back.', 'English', 117664, 'Group demo', 'http://i.ytimg.com/vi/vR6Nhhy6IY0/mqdefault.jpg', 'demo, judo, defense, judoka'),
(231, 'JUDO vs JUJITSU coaches KO fight', 'http://www.youtube.com/watch?v=wb3BbbKOdtw', 1, '480', 'Jujitsu & Judo coaches battle it out, under BJJ rules knockout fight Study Judo or Brazilian Jujitsu (BJJ) to learn about this.', 'English', 1413711, 'Entertainment', 'https://i.ytimg.com/vi_webp/wb3BbbKOdtw/mqdefault.webp', 'Judo, Judo vs Jujitsu, coach'),
(232, 'Kodokan Judo with Master Technician Sensei Kyuzo M', 'http://www.youtube.com/watch?v=wKYGuPNdmls', 30, '360', 'Kodokan Judo with a Master ', 'English', 142261, 'Tutorial', 'http://i.ytimg.com/vi/wKYGuPNdmls/mqdefault.jpg', 'Kodokan, Judo, Master'),
(233, '柔道 JUDO - TOMOE NAGE - JudoAttitude', 'http://www.youtube.com/watch?v=wQ41RiOcgrY', 3, '480', 'TOMOE NAGE: Judo Craig Fallon, Luwdig Paischer, Koga, etc..', 'Non-English', 94919, 'Entertainment', 'https://i.ytimg.com/vi/wQ41RiOcgrY/mqdefault.jpg', 'Judo, Tomoe Nage, JudoAttitude'),
(234, '2012 NCJA Collegiate National Judo Championships H', 'http://www.youtube.com/watch?v=WXj5cLUAXcQ', 7, '720', 'The 51st annual NCJA Collegiate National Judo Championships were held at San Jose State University on March 10th, 2012. Over 180 contestants fought fo', 'English', 135022, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/WXj5cLUAXcQ/mqdefault.webp', 'judo, highlight, competition, throws, sjsu'),
(235, 'Human Weapon Judo', 'http://www.youtube.com/watch?v=wZrrX1V9eTw', 3, '1080', 'Judo Example ', 'English', 68428, 'Tutorial', 'http://i.ytimg.com/vi/wZrrX1V9eTw/mqdefault.jpg', 'Judo, Weapon, TV'),
(236, 'Advanced Judo Techniques : How to do the Sacrifice', 'http://www.youtube.com/watch?v=x5Iguivw1GM', 1, '480', 'Learn Judo throws and moves in this free martial arts video from master Judo instructor Richard Acuna\r\n\r\nExpert: Richard Acuna', 'English', 242286, 'Tutorial', 'http://i.ytimg.com/vi/x5Iguivw1GM/mqdefault.jpg', 'judo, teaching'),
(238, 'Mens Judo -73 kg  London 2012 Olympics', 'http://www.youtube.com/watch?v=xfcCfekFGwQ', 13, '1080', 'Finals Olympics', 'English', 635044, 'Entertainment', 'http://i.ytimg.com/vi/xfcCfekFGwQ/mqdefault.jpg', 'Olympic, Russia, Japan'),
(239, 'Judo - 2006 US Open Ippons', 'http://www.youtube.com/watch?v=XhmNsdFy00U', 2, '240', '  US Ippons', 'English', 292966, 'Application', 'http://i.ytimg.com/vi/XhmNsdFy00U/mqdefault.jpg', ' US, Judo, Ippons'),
(240, 'MMA + Judo Training with UFC''s Nick + Nate Diaz, R', 'http://www.youtube.com/watch?v=xkWtQ1yRNrY', 5, '720', 'MMA H.E.A.T. was on the scene at the Throwdown Training Center in Las Vegas, NV, when the UFC''s Nick Diaz and Strikeforce''s Ronda Rousey worked out together.', 'English', 620252, 'Entertainment,Application,Others', 'http://i.ytimg.com/vi/xkWtQ1yRNrY/mqdefault.jpg', 'UFC,UFC 141,Nick Diaz,Ronda Rousey,Nate Diaz,Manny Gamburyan,Nick and Ronda,Judo,Throw,Takedown,Interview,Karyn Bryant,MMA HEAT,Throwdown Training Center,209'),
(241, 'The Most Dangerous Takedown in Judo & BJJ', 'http://www.youtube.com/watch?v=XRklGgwpbj0', 8, '720', 'Stephan Kesting teaches Kani Basami, the most dangerous throw in Judo and BJJ.  More tips, tricks and techniques at http://www.grapplearts.com/newsletter', 'English', 500703, 'Tutorial,Application', 'http://i.ytimg.com/vi/XRklGgwpbj0/mqdefault.jpg', 'Judo (Martial Art),Arts,Martial,Brazilian Jiu-jitsu (Martial Art),Martial Arts (Sport),Mma,Takedown,Mixed,Kani Basami,Throw,Stephan Kesting,Grapplearts,BJJ'),
(242, 'Entrenamiento de Judo tradicional.', 'http://www.youtube.com/watch?v=XvPMbjjRVXY', 16, '1080', 'Tipos de Entrenamiento en judo de la manera tradicional. Mas allá de las formas modernas de entrenar nunca se debe dejar de trabajar las bases. ', 'Non-English', 51458, 'Tutorial,Entertainment,Group demo', 'https://i.ytimg.com/vi/XvPMbjjRVXY/mqdefault.jpg', 'traditional,demo,interesting'),
(243, 'Georgia vs France 2014', 'http://www.youtube.com/watch?v=Y_tT74wY53M', 38, '720', 'Georgia (GEO) vs France (FRA)Team', 'English', 50616, 'Entertainment', 'http://i.ytimg.com/vi/Y_tT74wY53M/mqdefault.jpg', 'Team, Georgia, France, Judo'),
(244, 'SIME-WAZA (TÃ©cnicas de estrangulaciÃ³n). Judo', 'http://www.youtube.com/watch?v=y9RDiY1fahY', 9, '480', 'SIME-WAZA (TÃ©cnicas de estrangulaciÃ³n). Judo. RECOPILACIÃ“N\r\n', 'Non-English', 57850, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/y9RDiY1fahY/mqdefault.jpg', 'judo, demo'),
(245, 'Basic Judo - Chokes', 'http://www.youtube.com/watch?v=YJ5EhLWKXoU', 4, '480', '  Judo Chokes', 'English', 109927, 'Tutorial', 'http://i.ytimg.com/vi/YJ5EhLWKXoU/mqdefault.jpg', ' Judo, Chokes'),
(247, 'Nage No Kata Judo Instruction', 'http://www.youtube.com/watch?v=YOcVfmmMBLY', 7, '240', 'sports', 'English', 256649, 'Tutorial,Group demo', 'http://yt3.ggpht.com/-eylNBo7IhuY/AAAAAAAAAAI/AAAAAAAAAAA/HAZhZzlzeSE/s88-c-k-no/photo.jpg', 'sports,demo,learning'),
(248, 'Human Weapon - Judo - Tomoe Nage', 'http://www.youtube.com/watch?v=Z7Lnq3asIc4', 18, '240', 'This is a Breakdown of a Move shown on the Tv show  Human Weapon, If This has struck your interest, check out the show fridays on the History Channel', 'English', 1839337, 'Entertainment', 'https://i.ytimg.com/vi/Z7Lnq3asIc4/mqdefault.jpg', 'judo, human weapon'),
(249, 'JUDO WORLD CHAMPIONSHIPS RIO 2013 - OlympicJudo', 'http://www.youtube.com/watch?v=Zax4NAw-_y4', 3, '1080', '300 Violin Orchestra - Jorge Quintero \r\nhttps://www.facebook.com/olympic.judo\r\nhttp://vk.com/judoattitude', 'Non-English', 57324, 'Entertainment,Others', 'http://i.ytimg.com/vi/Zax4NAw-_y4/mqdefault.jpg', 'rio, 2013, winners, champs'),
(251, 'Tai Chi Master Wang Zhanhai vs Judo', 'http://www.youtube.com/watch?v=ZlhH0PAsaZI', 3, '720', '  Tai Chi vs Judo', 'Non-English', 262017, 'Application', 'http://i.ytimg.com/vi/ZlhH0PAsaZI/mqdefault.jpg', ' Tai Chi, Judo'),
(255, 'Georgian judo team in Korea', 'http://youtu.be/0utkzknYN1E', 9, '240', 'After 20 randori', 'Non-English', 75282, 'Entertainment', 'http://i.ytimg.com/vi/0utkzknYN1E/hqdefault.jpg', 'Georgian judo,Georgian judo federation,South Korea (Country)'),
(259, 'Basic Judo ', 'http://youtu.be/9gHQLT42Fl0', 3, '480', 'Uploaded on Oct 16, 2008', 'English', 102412, 'Tutorial', 'http://judoinfo.com/images/kansetsu/jujigatame-3.jpg', 'judo, throw, fall, trip, choke, martial, art, exercise, dojo, belt, train, compete, fight, defend, self, attack, submit'),
(260, 'Judo Nage No Kata demonstration video', 'http://youtu.be/A7hDH_KHf9o', 7, '480', ' wonderful demonstration of judo''s Nage-no-kata', 'Non-English', 229684, 'Group demo', 'http://i.ytimg.com/vi/A7hDH_KHf9o/hqdefault.jpg', 'Judo, nage, no, kata, nage-no-kata'),
(262, 'Olympic Judo training NJ', 'http://youtu.be/C0Cr2FmXEpQ', 3, '480', 'Olympic Judo performed in New Jersey Judo training facility. ', 'English', 259140, 'Tutorial', 'http://i.ytimg.com/vi/C0Cr2FmXEpQ/mqdefault.jpg', 'olympic judo NJ, SAMBO training NJ'),
(265, 'Judo training', 'http://youtu.be/dpe3w5Il5cM', 5, '480', 'Judo is fight', 'Non-English', 133477, 'Entertainment', 'https://i.ytimg.com/vi_webp/dpe3w5Il5cM/mqdefault.webp', 'Judo, michal slanař, tomáš klinec, fight, koga, nomura, trainig, litoměřicel, mělník, breakdance, mma, sport'),
(267, 'Advanced Judo Throws for Mixed Martial Arts', 'http://youtu.be/dyygAG2aHW8', 5, '1080', 'Subscribe to the MMA Surge Newsletter:', 'English', 101527, 'Tutorial', 'https://i.ytimg.com/vi/dyygAG2aHW8/mqdefault.jpg', 'combat sports, olympic sports, kayla harrison, ronda rousey, sambo, brazilian jiu-jitsu, judoka, mixed martial arts, mma, mma trainin'),
(273, 'MANSUR ISAEV - THE ANIMAL - JUDO COMPILATION', 'http://youtu.be/L0sVn5QjUss', 5, '720', 'Mansur Isaev -73kg Russia', 'Non-English', 351415, 'Entertainment', 'http://judokafighter.com/wp-content/uploads/2013/01/07.jpg', 'Judo, Compilation, Motivation, European, World, Championships, 2008, 2009, 2010, 2011, 2012, 2013, Olympia, London, Beijing, Mansur Isaev, Gold, Olympic'),
(279, 'MMA Best Judo Throws', 'http://youtu.be/PBnWgT2en1U', 4, '480', 'Various clips of MMA Judo throws', 'English', 160728, 'Entertainment', 'http://www.mmaopinion.co.uk/wp-content/uploads/2012/03/JudoThrow.jpg', 'MMA, Judo, Arts, Martial, Taekwondo, Mixed, Martial Arts, Fight, wrestling, UFC, Jiu, Jitsu, Submission, Tournament, Best, Combat, Karate, Belt'),
(290, 'RUSSIA JUDO TEAM EXTRIM', 'http://youtu.be/xTUhX7U-loE', 6, '360', 'Uploaded on Oct 16, 2011', 'Non-English', 87153, 'Entertainment', 'http://img.youtube.com/vi/xTUhX7U-loE/0.jpg', 'Мой, первый, проект');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fun_video`
--
ALTER TABLE `fun_video`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `fun_video`
--
ALTER TABLE `fun_video`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=291;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
