-- phpMyAdmin SQL Dump
-- version 2.11.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Dec 09, 2014 at 05:00 PM
-- Server version: 5.5.40
-- PHP Version: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `youthcyb_aguirre`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE `fun_video` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=103 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` VALUES(1, 'How to Use Simple Qigong to Transform Your Health ', 'http://www.youtube.com/watch?feature=player_detailpage&v=bnWspaqJ5VY', 2800, '1080', 'Lee 	Holden an international instructor', 'English', 161742, 'Tutorial,Entertainment,Group demo', 'http://i.ytimg.com/vi/bnWspaqJ5VY/mqdefault.jpg', 'demo,group,lee,holden,meditation,tai chi,qi gong');
INSERT INTO `fun_video` VALUES(2, '5 Element Qigong Practice', 'http://www.youtube.com/watch?v=_6Y8QSVyYhM', 1252, '1080', 'practices for the elements of Wood, Fire, Earth, Metal and Water', 'English', 50978, 'Tutorial', 'http://i.ytimg.com/vi/_6Y8QSVyYhM/mqdefault.jpg', 'elements,wood,fire,earth,metal,water,qigong');
INSERT INTO `fun_video` VALUES(3, 'Qigong for Beginners', 'http://www.youtube.com/watch?v=_xnsT6ukqM8', 800, '480', 'This video got a good review from Karate Illustrated in June 2000. Available on DVD at http://sal4healing.com', 'English', 111992, 'Tutorial', 'http://i.ytimg.com/vi/_xnsT6ukqM8/mqdefault.jpg', 'qigong, taichi, tai, chi, china, chikung, qi, gong, kungfu, martial, arts, kung, fu, chinese, healing, meditation');
INSERT INTO `fun_video` VALUES(4, 'Shaolin Qi Gong Energy Master Xiao', 'http://www.youtube.com/watch?v=-_C0rUBGZb4', 700, '240', 'With beautiful background music, Master Changzong Xiao demonstrates Shaolin ancient qi gong breathing energy.   http://masterxiaohealing.com/', 'English', 105037, 'Application', 'http://i.ytimg.com/vi/-_C0rUBGZb4/mqdefault.jpg', 'Shaolin, Qigong, qi, gong, tai, chi, chinese, music');
INSERT INTO `fun_video` VALUES(5, 'Primordial Qigong - Grandmaster Feng Zhiqiang', 'http://www.youtube.com/watch?v=-5X5pBx8nUE', 1500, '240', 'Tai Chi Grandmaster Feng Zhiqiang of Beijing, China was also a master of Taoist Qigong. The Primordial Qigong is a series of gentle movements that recharges you like a battery with deep breathing and full body motion.', 'English', 140029, 'Tutorial', 'http://i.ytimg.com/vi_webp/-5X5pBx8nUE/mqdefault.webp', 'healing, qi, qigong, chi, taiji, taichi, chikung, primordial, health, cancer-prevention, educational, tao, taoism, instructions, martial arts, fitness');
INSERT INTO `fun_video` VALUES(6, 'Fight Science - Qi Gong Tested', 'http://www.youtube.com/watch?v=2tb8bWbA678', 1012, '360', 'Qi Gong Tested', 'English', 531882, 'Application', 'http://www.oldtownyoga.com/wp-content/uploads/2014/11/qigong_meditation1-2.jpg', 'Fight, Science, Qi, Gong, Tested');
INSERT INTO `fun_video` VALUES(7, 'Tai Chi Nation:: 5 Element Chi Kung - Qigong', 'http://www.youtube.com/watch?v=35QER5t_luE', 751, '240', 'Tai Chi class from Tai Chi Nation', 'English', 77336, 'Tutorial', 'http://ecx.images-amazon.com/images/I/41erR0ovjVL._SL500_AA300_.jpg', 'session,lesson, tai chi, tai chi nation, element, chi kung, qigong');
INSERT INTO `fun_video` VALUES(8, 'Qigong Qi gong 18 Figuren der Harmonie, Shibashi, ', 'http://www.youtube.com/watch?v=3FbD5GRf6gw', 748, '360', 'Qigong-Harmonie in 18 Figuren (Shibashi)', 'Non-English', 204992, 'Application', 'http://i.ytimg.com/vi_webp/3FbD5GRf6gw/mqdefault.webp', 'qigong, qi-gong, qi, gong, Tai, Chi, Ji, Quan, taiji, tai, chi, taichi, Qigong-Harmonie in 18 Figuren, Shibashi');
INSERT INTO `fun_video` VALUES(9, 'Three Simple Qigong Exercises', 'http://www.youtube.com/watch?v=3zL4DyguWAk', 1402, '240', 'Cheyne Towers teaches three simple qigong exercises and students describe some benefits they''ve experienced. Longer, varied training sessions can be found at Cheyne''s own website http://www.heartmindtherapies.com/ and a new Qi Sensing DVD/MP3 resource pack loaded with discrete techniques, configurations and strategies for using qi awareness in daily life, taught by filmmaker Richard Coldmancan be found at: http://wp.me/pkuB3-3C', 'English', 522466, 'Tutorial', 'http://i.ytimg.com/vi/3zL4DyguWAk/mqdefault.jpg', 'cheyne towers, richard coldman, qi, chi qiong, kung, tai, taiji, chuan, tailiquan, qigong, taijiquan, qigong exercises, qi gong, chi gong exercises');
INSERT INTO `fun_video` VALUES(10, 'Kuan Yin Standing Qigong Part 1 - Sheng Zhen', 'http://www.youtube.com/watch?v=4cCD0l7COqk', 950, '480', 'Teacher Li demonstrating Kuan Yin Standing qigong. For more info on Sheng Zhen Wuji Yuan Gong visit www.shengzhen.org or www.shengzhen-americas.org/', 'English', 330748, 'Tutorial,Application', 'http://i.ytimg.com/vi/4cCD0l7COqk/mqdefault.jpg', 'Standing, kuan yin, standing, qigong, sheng, zhen');
INSERT INTO `fun_video` VALUES(11, 'Qi Gong Video (Segment 2): 10 min ', 'http://www.youtube.com/watch?v=54pdoYpqCuY', 1009, '360', 'Produced by Image Quilt Productions, http://imagequilt.com, this video focuses on Qi Gong, an exercise regiment that helps people with Hepatitis-C. This is segment 2 of the 40 minute exercise video video filmed during the Caring Ambassadors Program retreat tatthe Omega Institute in Rhinebeck, New York. ', 'English', 123368, 'Others', 'http://i.ytimg.com/vi/54pdoYpqCuY/default.jpg', 'qigong, qi gong, quilt productions');
INSERT INTO `fun_video` VALUES(12, 'Cours de Qi Gong debutant - Relaxation', 'http://www.youtube.com/watch?v=6H-x0pnuctY', 15830, '480', 'Exercices de qi gong avec BÃ©atrice Reynier. Le qi gong permet d''utiliser consciemment l''Ã©nergie vitale de corps. Le qi gong peut Ãªtre considÃ©rÃ© comme mÃ©dical car il revitalise en douceur, assouplie les articulations, optimise la circulation sanguine et Ã©nergÃ©tique et favorise les fonctions de la respiration. ', 'Non-English', 97377, 'Tutorial', 'http://i.ytimg.com/vi_webp/6H-x0pnuctY/mqdefault.webp', 'respiration, conseils, position, apprentissage, formation, Beatrice Reynier, technique, taoiste, demonstration, programme, astuces, medical');
INSERT INTO `fun_video` VALUES(13, 'Masaje Qigong Taoista', 'http://www.youtube.com/watch?v=6TcH7kMFJJY', 902, '240', 'Tradicional automasaje taoista ideal para finalizar una sesión de Qigong. Video protagonizado por Xuan Tongzi.', 'Non-English', 78526, 'Tutorial', 'http://i.ytimg.com/vi_webp/6TcH7kMFJJY/mqdefault.webp', 'xuan tongzi, taoista, qigong');
INSERT INTO `fun_video` VALUES(14, 'Ba Duan Jin Complete Demonstration 1', 'http://www.youtube.com/watch?v=6Zn_d2D15Q4', 512, '480', 'Ba Duan Jin or Eight Section Silk Brocade by The Chinese Health Qigong Association', 'English', 319386, 'Tutorial', 'http://i.ytimg.com/vi_webp/6Zn_d2D15Q4/mqdefault.webp', 'qigong, ba duan jin, demonstration, Chinese, health');
INSERT INTO `fun_video` VALUES(15, 'Chi Gong and Tai Chi (Qi Gong) Energy Healing Exer', 'http://www.youtube.com/watch?v=7MSHOulBZNs', 933, '1080', 'Chi Gong and Tai Chi are ancient Chinese healing energy exercises and techniques. These are simple movements combined with thought and intention to become healthy, increase energy, get rid of toxins, and relax the mind and body.   Shown in this video are five simple techniques that will build chi.', 'English', 181279, 'Tutorial', 'http://i.ytimg.com/vi/7MSHOulBZNs/mqdefault.jpg', 'tai chi, chakra, qigong, qigong meditation techniques, qigong video, qigong master, chi gong energy, chi gong masters, tai chi form, tai chi master, tai chi');
INSERT INTO `fun_video` VALUES(16, 'Finger Qigong - Exercises for Chi Circulation in t', 'http://www.youtube.com/watch?v=7P9EiooL3Ck', 852, '1080', 'http://www.cloudwater.com - The exercises are: 1. The Count 2. Finger Flicks 3. Touch and Brush 4. The Piano 5. The Straightener 6. Finger Massage 7. Finger Chi Washing  Three-time U.S. Martial Arts Hall of Fame inductee Al Simon shows seven simple exercises to increase Chi circulation to the fingers.  Zaphod in a comment below asked me about "masters" in Qigong and Tai Chi. I think too many people look outside themselves for masters and gurus, when what they are looking for can be found inside themselves. You don''t need masters or gurus, you just need the right guide to help you find what you are looking for. To find if I''m the right guide for you, just check my website at http://www.CloudWater.com', 'English', 203850, 'Tutorial', 'http://i.ytimg.com/vi/7P9EiooL3Ck/mqdefault.jpg', 'Qigong chi kung chi gung, finger exercises, arthritis, tendonitis, tendinitis, finger pain, circulation');
INSERT INTO `fun_video` VALUES(17, 'Qigong: Yi Jin Jing (Ching) Chi Kung', 'http://www.youtube.com/watch?v=7TWnR9acHWo', 719, '240', 'Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Master Jesse Tsao presents the most complete set, practiced in the Beijing area, and explains each posture''s healing benefits based on traditional Chinese medicine (TCM). He also includes an adopted version of Yi Jin Ching on the chair. Detailed instructions are given in English with front and back views.', 'Non-English', 215267, 'Tutorial,Application', 'http://i.ytimg.com/vi/7TWnR9acHWo/mqdefault.jpg', 'qigong,yi jin jing,tai chi,bio, energy');
INSERT INTO `fun_video` VALUES(18, 'Qi Gong 10 symbols of Longevity Exercises 1-6', 'http://www.youtube.com/watch?v=7VVTsotiIms', 915, '240', 'This rarely known in America set of Qi Gong Exercises can reduce stress and anxiety, while improving', 'English', 228186, 'Tutorial', 'http://i.ytimg.com/vi/7VVTsotiIms/mqdefault.jpg', 'water,longevity,symbols');
INSERT INTO `fun_video` VALUES(19, '18 Chi Quong Shibashi(Tai Chi Qigong 18)', 'http://www.youtube.com/watch?v=8_qwK8GykFA', 1034, '240', 'Qigong the 18 Movement', 'English', 226535, 'Application', 'http://i.ytimg.com/vi_webp/8_qwK8GykFA/mqdefault.webp', 'ChiQuong, Shibashi (Tai Chi Qigong 18), Tai, Chi, 18');
INSERT INTO `fun_video` VALUES(20, 'Wudang Five Animals Qi Gong', 'http://www.youtube.com/watch?v=8Up2Mnq7JSM', 629, '240', 'Wudang Five Animals Qigong is an ancient Taoist exercise designed to improve ones health and longevity. As the name implies, the movements of this exercise are based on the movements of five animals; the dragon, the tiger, the leopard, the snake, and the crane', 'English', 414295, 'Tutorial,Others', 'http://i.ytimg.com/vi/8Up2Mnq7JSM/mqdefault.jpg', 'demo,relaxing, five animals,five,animals,qigong,ancient,Taoist,health,longevity');
INSERT INTO `fun_video` VALUES(21, 'Meditative Exercises of Shaolin Martial Arts', 'http://www.youtube.com/watch?v=9IGj5vSj4l0', 216, '480', 'Popular qigong exercises called Eight Pieces of Brocade; learn the meditative, spiritual side of Shaolin Kung Fu in this free martial arts video series.', 'Non-English', 225211, 'Tutorial', 'http://i.ytimg.com/vi/9IGj5vSj4l0/mqdefault.jpg', 'exercise,meditative,meditate,shaolin,martial,arts,brocade,spiritual');
INSERT INTO `fun_video` VALUES(22, 'QI GONG - SHAOLIN QI GONG', 'http://www.youtube.com/watch?v=9OMH-Zm_xNE', 410, '480', 'Qi Gong in der Tradition der Shaolin, dargeboten von Shi Yan Lu, www.shaolinzentrum. An early morning exercise underneath a large tree , amidst plenty of greenery foliage surroundings and preferably near a stream or river with water flowing', 'English', 463619, 'Entertainment', 'http://i.ytimg.com/vi_webp/9OMH-Zm_xNE/mqdefault.webp', 'Qi Gong, Qigong, Shaolin, Jean-Pierre Garattoni, Edition Incontro, Incontro, Entspannung, Relax, ShaolinQiGong, shaolincenter, musicforbodyandsoul');
INSERT INTO `fun_video` VALUES(23, 'Qigong Beginning Exercises : Qigong Breathing Exer', 'http://www.youtube.com/watch?v=a2U5jaF7MJI', 500, '480', 'Breathing and meditation is one of the most relaxing exercises for all ages. Learn how to breathe and meditate in Qigong with this free video from a Qigong instructor.  Expert: Tony Nguyen Bio: Tony Nguyen has over twenty years experience. Currently, he teaches Qigong at an academy in Las Vegas. Filmmaker: Travis Waack', 'English', 100369, 'Tutorial', 'http://i.ytimg.com/vi/a2U5jaF7MJI/mqdefault.jpg', 'qigong, exercises, poses, benefits, qi, gong, fitness, health, chinese, free, how, to, Expert, Village');
INSERT INTO `fun_video` VALUES(24, 'Hidden Qi & Qigong part 1', 'http://www.youtube.com/watch?v=A5VRTl92184', 822, '360', 'Qi, qigong demonstrations on health', 'English', 96224, 'Entertainment', 'http://i.ytimg.com/vi/A5VRTl92184/mqdefault.jpg', 'qigong master, master, qigong, qi, ki, chi, chi-kung, chi gung, chinese, kung fu, gung fu, martial arts, karate');
INSERT INTO `fun_video` VALUES(25, 'Infinity Quantum Qi Gong Presentation, Ama Lia Wai', 'http://www.youtube.com/watch?v=AHQBXBHe7AY', 1034, '360', 'Infinity Quantum Qi Gong Is a set of simple yet profoundly accelerated techniques that enhance self-awareness and self-healing on a multidimensional quantum level. It is an ancient spiritual art, synthesized with modern scientific knowledge. The premise of this energy cultivation lies with Quantum Medicine and is a component of Vibrational Medicine.  This practice combines forms of breathwork, visualization and actualization of energy cultivation into noticeable somatic alignment and transformation.  This meditation in movement which recognizes that the body''s qi or energy flows in waves, is based on the sacred geometry of the Infinity symbol, 8. The consciousness of this system accesses the intelligence of the DNA matrix.  The body is trained to connect to and receive the movement of these energy impulses. The focus is on the spine. It increases the vital life force in the meridians and energy matrix for cellular rejuvenation on a physical level and in the deep psyche.   The wavelik', 'English', 271958, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/AHQBXBHe7AY/mqdefault.webp', 'qigong,presentation,healing,spiritual, Ama Lia, Wai Ching Lee');
INSERT INTO `fun_video` VALUES(26, 'Qigong: The Ancient Art of Self Healing', 'http://www.youtube.com/watch?v=ajTTYI4IdoE', 522, '360', 'A film about the powers of one of the world''s most ancient and mysterious practices', 'English', 119246, 'Others', 'http://i.ytimg.com/vi/ajTTYI4IdoE/mqdefault.jpg', 'Healing,ancient art, qigong, mysterious');
INSERT INTO `fun_video` VALUES(27, 'Kuan Yin Standing Qigong Part 2 - Sheng Zhen', 'http://www.youtube.com/watch?v=ANSNaN4x-80', 924, '240', 'Teacher Li demonstrating Kuan Yin Standing qigong. For more info on Sheng Zhen Wuji Yuan Gong visit www.shengzhen.org or www.shengzhen-americas.org/ (more)', 'English', 148778, 'Application', 'http://i.ytimg.com/vi/ANSNaN4x-80/mqdefault.jpg', 'Teacher, Li, Kuan, Yin, Standing, qigong, Sheng, Zhen, Wuji, Yuan, Gong');
INSERT INTO `fun_video` VALUES(28, 'Qigong Chi Kung: Six Healing Sounds', 'http://www.youtube.com/watch?v=BFqotaIc3Dw', 559, '240', 'http://www.taichihealthways.com offer more video views of Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Preview this best-selling instructional DVD. Master Tsao teaches this ancient Chinese Qigong practice in detail, with repetitions for each sound.', 'English', 669956, 'Application', 'http://i.ytimg.com/vi/BFqotaIc3Dw/mqdefault.jpg', 'taiji, tai, chi, kung, chuan, qigong, healing, six, sounds, meditation');
INSERT INTO `fun_video` VALUES(29, 'Understanding QiGong and Qi 2/3', 'http://www.youtube.com/watch?v=BhoVL96BjP8', 957, '360', 'Excerpt from Dr. Yang, Jwing-Ming''s DVD Qigong Massage, published by YMAA.com  http://ymaa.com/publishing/dvd/qigong', 'English', 216012, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi_webp/BhoVL96BjP8/mqdefault.webp', 'Qi, Gong, Chi, Dr, Yang');
INSERT INTO `fun_video` VALUES(30, 'How to Use Simple Qigong to Transform Your Health ', 'http://www.youtube.com/watch?v=bnWspaqJ5VY', 2756, '1080', 'Lee Holden an international instructor of Qi Gong, Meditation and Tai Chi and a household name on US and Canadian TV. He also runs his own wellness center out of Santa Cruz, California.  See incredible instructors like Lee live at Awesomeness Fest.  Awesomeness Fest is a global non-profit, transformational event that brings together people who are driven to change the world-- entrepreneurs, authors, technophiles, mavericks, artists and visionaries alike.  Like being at a festival that merges Burning Man, TED and an exotic vacation, you''ll get to dance the night (and day) away at incredible parties, go on breathtaking excursions, form life long friends and connections and learn how to take your life to the next level both personally and professionally. And it all happens in a paradise location', 'English', 162010, 'Entertainment', 'http://i.ytimg.com/vi_webp/bnWspaqJ5VY/mqdefault.webp', 'Tranformational, motivational, workshop, spirituality, self development, meditation');
INSERT INTO `fun_video` VALUES(31, '8 Brocades of Qigong', 'http://www.youtube.com/watch?v=BQbfysOBxhI', 1014, '720', '8 Brocades of Chinese Qigong sometimes also called Chi Kung or Qi Gong, and also called Ba Duan Jin! Have fun, learn all eight, and then practice everyday about 5-10 breaths per brocade or posture! I love practicing Qigong in the morning first thing or right before bed!', 'English', 200728, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/BQbfysOBxhI/mqdefault.jpg', 'Eight, Brocades, Qigong, Chinese, Chi, Kung, Qi, Gong, Jake, Mace, Tai,martial art, Yoga, Meditation, Traditional, Classical, China');
INSERT INTO `fun_video` VALUES(32, 'Qi Gong Video (Segment 1): 10 min', 'http://www.youtube.com/watch?v=bSZq78t4WMg', 939, '360', 'Produced by Image Quilt Productions. This is an exercise video with a Master instructor focused on Qi Gong (Xi Gong) exercises which help people cope with Hepatitis C. Filmed during the Caring Ambassadors Program retreat to the Omega Institute in Rhinebeck, New York', 'English', 656579, 'Tutorial', 'http://i.ytimg.com/vi/bSZq78t4WMg/mqdefault.jpg', 'qi, gong, xi, exercise, video, caring, ambassadors, program');
INSERT INTO `fun_video` VALUES(33, 'Tai Chi Qigong Shibashi (1 of 2)', 'http://www.youtube.com/watch?v=c60u6WfChmM', 1500, '360', 'Tai Chi Qigong Shibashi is a Qigong which based on the philosophy of Tai Chi and extracts some of the best movements from the Yang style Tai Chi Chuan. It places emphasis on synchronizing the 18 movements with proper breathing techniques.', 'Non-English', 454773, 'Tutorial', 'http://i.ytimg.com/vi_webp/c60u6WfChmM/mqdefault.webp', 'taichi, qigong, shibashi,best, movements, yang style, breathing');
INSERT INTO `fun_video` VALUES(34, 'Qi Gong for Upper Back and Neck Pain with Lee Hold', 'http://www.youtube.com/watch?v=CFa_rwMctmA', 153, '480', 'All that time on the cell phone and computer does a number on our necks and upper backs. Acclaimed instructor Lee Holden offers some quick relief in this preview from his popular Qi Gong series. The simple-to-do stretches release blocked tension, restore energy and work wonders to alleviate headaches, jaw pain, shoulder tightness and more.', 'English', 72180, 'Tutorial', 'http://i.ytimg.com/vi/CFa_rwMctmA/mqdefault.jpg', 'Lee, Holden, Exercise, Health, Fitness, Energy, Rejuvenate, Tai, Chi, Yoga, Qi, Gong, Upper, Back, Neck, Pain');
INSERT INTO `fun_video` VALUES(35, 'Understanding QiGong and Qi 1/3', 'http://www.youtube.com/watch?v=CPl8JNxSYIY', 957, '360', 'Excerpt from Dr. Yang, Jwing-Ming DVD Qigong Massage, published by YMAA.com. This is the first part of 3', 'English', 555204, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/CPl8JNxSYIY/mqdefault.webp', 'Qi, Gong, Chi, Dr., Yang, part');
INSERT INTO `fun_video` VALUES(36, 'Introduccion al Qi Gong', 'http://www.youtube.com/watch?v=CtDCME8phiU', 13010, '480', 'INTRODUCCION AL QI GONG comienza con los conceptos espirituales del Qi Gong. Qi Gong, pronunciado Chi Kung, es un ejercicio para fortalecer la salud, vitalidad, equilibrio interior y armonia. Desarrollado en China hace miles de anos -- algunas escuelas de Qi Gong determinan el periodo de su existencia en muchos miles de anos antes de Cristo', 'Non-English', 189585, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/CtDCME8phiU/mqdefault.webp', 'Qi Gong, espanol, introduccion, Tai Chi,qigong, equilibrio');
INSERT INTO `fun_video` VALUES(37, 'Sword Finger - amazing energy', 'http://www.youtube.com/watch?v=dFR0arLH5oY', 139, '360', 'A sample of video clips from Robert Peng''s DVD series, The Master Key. Follow along as Robert guides you step-by-step through the exercises described in the book, The Master Key.  Watch amazing animations bring the subtle energy flows to life.', 'English', 57110, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/dFR0arLH5oY/mqdefault.webp', 'Training, Robert peng, energy, sword,exercises');
INSERT INTO `fun_video` VALUES(38, 'Power of Meditation: Qigong Master Chi Energy', 'http://www.youtube.com/watch?v=dfy2Tn52sxU', 952, '240', 'This video explores the powers of meditation. This video is about person who has a true gift. If you enjoy this video, please send a link to it to all of your friends.', 'English', 184535, 'Tutorial,Application', 'http://i.ytimg.com/vi/dfy2Tn52sxU/mqdefault.jpg', 'Meditation, powers, qigong, energy');
INSERT INTO `fun_video` VALUES(39, 'QIGONG Shaolin " BaDuanJin " ( 8 pieces of Brocade', 'http://www.youtube.com/watch?v=DhsU1qLBF8s', 748, '720', 'Fanny Ng performing so stylishly , gracefully the Shaolin QIGONG, Ba Duan Jin, with a beautiful music', 'English', 105182, 'Application', 'http://i.ytimg.com/vi_webp/DhsU1qLBF8s/mqdefault.webp', 'BaDuanJin, Shaolin,Qigong,fanny, new age, music');
INSERT INTO `fun_video` VALUES(40, 'Shaolin Hard Qi-Gong (Part 4)', 'http://www.youtube.com/watch?v=dt1eEh1Diec', 648, '360', 'Shaolin Hard Qi-Gong. Nicht nachmachen!! Do no try at home!!', 'Non-English', 55033, 'Tutorial', 'http://i.ytimg.com/vi/dt1eEh1Diec/mqdefault.jpg', 'Shaolin,Qigong, demostration');
INSERT INTO `fun_video` VALUES(41, 'Wu Xing Qi Gong', 'http://www.youtube.com/watch?v=E-EA86oKkPs', 719, '360', 'Wu Xing Qi Gong (Five Element Qi Gong) as developed and performed by Master Liu De Ming.', 'Non-English', 731040, 'Tutorial', 'http://i.ytimg.com/vi/E-EA86oKkPs/mqdefault.jpg', 'qigong,xing, wu, master liu, liu de ming, de ming');
INSERT INTO `fun_video` VALUES(42, 'Daily Qigong - 4 minute exercise', 'http://www.youtube.com/watch?v=EaEZVfhn07o', 430, '480', 'TaiChiHealthProducts.org presents a 4-minute daily QIGONG exercise. Join in with Instructor Don Fiore. Stretching and breathing are important for senior and elderly health - and good for all ages. The movements come from our Easy TaiChi-Qigong DVD and can be done while sitting or standing. TaiChiHealthProducts.org has more Senior and Holistic Health Tips and Exercise Programs.  If you copy this video, you must include our entire description - and we do not allow people to make money from our videos by placing advertising on them. Copyright 2012.', 'English', 177967, 'Tutorial', 'http://i.ytimg.com/vi_webp/EaEZVfhn07o/mqdefault.webp', 'Easy Qigong, Senior Fitness DVD, Tai Chi Health Products, taichihealthproducts.org, Don Fiore, Easy Tai Chi, Easy TaiChi-Qigong dvd, Seniors, Daily Exercise');
INSERT INTO `fun_video` VALUES(43, 'Qigong Chi Kung: Five 5 Animal Frolics', 'http://www.youtube.com/watch?v=egrEfhPm5EA', 645, '240', 'Preview this best-selling instructional DVD. Master Tsao teaches this ancient Chinese Qigong practice in details with both front and back views', 'English', 308856, 'Tutorial,Application', 'http://i.ytimg.com/vi/egrEfhPm5EA/mqdefault.jpg', 'master tsao, master, Chinese, qigong, front view, view, bio, healing, shaolin, wudang, martial arts');
INSERT INTO `fun_video` VALUES(44, 'Hard Qi Gong National Geographic', 'http://www.youtube.com/watch?v=ELdYiHJkV8c', 230, '240', 'National Geographic filmed. ', 'English', 121821, 'Tutorial,Application', 'http://i.ytimg.com/vi/ELdYiHJkV8c/mqdefault.jpg', 'national geographic, qigong, hard, film');
INSERT INTO `fun_video` VALUES(45, 'Tai Chi Qigong Shibashi (2 of 2)', 'http://www.youtube.com/watch?v=F85nJdeD5tg', 1331, '480', 'Tai Chi Qigong Shibashi is a Qigong which based on the philosophy of Tai Chi and extracts some of the best movements from the Yang style Tai Chi Chuan', 'Non-English', 95538, 'Tutorial,Entertainment,Application', 'http://i.ytimg.com/vi/F85nJdeD5tg/mqdefault.jpg', 'Tai Chi,Qigong, shibashi');
INSERT INTO `fun_video` VALUES(46, 'Qigong - China ', 'http://www.youtube.com/watch?v=FXN-IZ_skBA', 934, '720', 'July 1995 Qigong is the art of harnessing the force that is said to give nature its pattern.', 'English', 248725, 'Entertainment', 'http://i.ytimg.com/vi/FXN-IZ_skBA/mqdefault.jpg', 'documentary, china, qigong');
INSERT INTO `fun_video` VALUES(47, 'Taoist Qigong Opening Exercises', 'http://www.youtube.com/watch?v=gdo4HfO2aX0', 958, '240', 'Grandmaster Chen Zheng Lei 19th Generation Successor, Chen style Taijiquan One of the Four Diamonds (Buddhas Attendants) of Chen Taiji. These movements are from silk reeling, but they can be found in most internal martial arts systems. The teacher goes in to standing post qigong afterwards', 'English', 173133, 'Application', 'http://i.ytimg.com/vi_webp/gdo4HfO2aX0/mqdefault.webp', 'Silk, Reeling, Chen, Style, Taiji, Qigong, Chikung, Chi, Opening, Warm, up, exercises, meditation, Taoist, Tao, Kung, Fu, Internal, Martial, Arts, Health');
INSERT INTO `fun_video` VALUES(48, '8 Qi- Gong Daily Exercises in Zermatt', 'http://www.youtube.com/watch?v=Go30-accQK0', 714, '360', '8 Qi- Gong Daily Exercises', 'English', 71600, 'Application', 'http://i.ytimg.com/vi/Go30-accQK0/mqdefault.jpg', 'Gi Gong, Astrid Brantschen-Schluep, matterhorn, Zermatt, Winter');
INSERT INTO `fun_video` VALUES(49, 'Qi Gong: Relax Music for Qi Gong, Yoga, Tai Chi an', 'http://www.youtube.com/watch?v=gXqTSNAd3cc', 4151, '480', 'Relaxing Music ideal for Qi Gong, Tai Chi, Tai Chi Chuan, Hatha Yoga, Kundalini Yoga, Vinyasa Yoga and Vinyasa Flow Yoga. Music for Yoga, New Age, Relaxation & Meditation. This Video Contains Coloured Pictures and Sweet Music to Help You Relax and Meditate', 'English', 273731, 'Others', 'http://i.ytimg.com/vi/gXqTSNAd3cc/mqdefault.jpg', 'music, relax, qigong, yoga, tai chi, Buddhist, meditation');
INSERT INTO `fun_video` VALUES(50, 'Balancing the Heart Qigong', 'http://www.youtube.com/watch?v=HfTqh8b1KzE', 827, '240', 'Sam Masich (Qigong - All Levels) This presentation of Shuxin Pingxue Gong details an effective and powerful Qigong routine. Designed to ''extend the blood and balance of the heart'', these 8 simple exercises are practiced in China for the treatment of hypertension, coronary disease and heart distress. 80 minutes', 'English', 69592, 'Tutorial', 'http://i.ytimg.com/vi/HfTqh8b1KzE/mqdefault.jpg', 'taichi, taiji, instructional, qigong, learning, kungfu, xingyi, chikung, sword, pushhands, sparring, martial, arts, masich, sam');
INSERT INTO `fun_video` VALUES(51, 'Qigong 18 Forms', 'http://www.youtube.com/watch?v=HN-MVpF8gkY', 902, '360', 'Tai Chi Qigong 18 forms demonstration.', 'English', 98641, 'Tutorial', 'http://i.ytimg.com/vi/HN-MVpF8gkY/mqdefault.jpg', 'forms, demonstration, tai chi, qigong');
INSERT INTO `fun_video` VALUES(52, 'Extreme Qigong Kung Fu Martial Arts Competition', 'http://www.youtube.com/watch?v=I_knyr-msTc', 2933, '240', 'Martial Arts Competition', 'English', 500549, 'Entertainment', 'http://img.youtube.com/vi/I_knyr-msTc/0.jpg', 'competition,china, qigong, extreme, martial arts, kung fu');
INSERT INTO `fun_video` VALUES(53, 'Immune Boost Qigong', 'http://www.youtube.com/watch?v=i3noqRBgxWM', 806, '480', 'Immune Boost Qigong routines stimulate the function of the Lungs and activate the Yang Qi in order to circulate the Wei Qi (defensive Qi). Performing these self-healing routines enable you to administer your own "Qigong Flu Shot" for defensive help in the upcoming cold & flu season.  Immune Boost Qigong theory and routines from the LIng Gui International Healing Qigong School, demonstrated by Master Liu He.  Master Liu He comes from a family of distinguished healers. Her grandfather treated the Last Emperor of China. Liu He began learning Qigong at four years of age from her grandfather and when she was nine, recognizing her high level of consciousness, he decided to break with the males-only tradition and train Liu He to become a Qigong master.', 'English', 77231, 'Tutorial', 'http://i.ytimg.com/vi_webp/i3noqRBgxWM/mqdefault.webp', 'qigong, master liu he, dr. liu dong, ling gui, taoist qigong, medical qigong, healing qigong, chinese medicine, qigong tuina, instructional video');
INSERT INTO `fun_video` VALUES(54, 'Qi Gong: Meditation Music for Qi Gong Classes', 'http://www.youtube.com/watch?v=idqTK_SEhAk', 2243, '360', 'Qi Gong: Meditation Music for Qi Gong Classes, Yoga, Ti Chi Chuan and Reiki, Relax and Meditation. Relaxing Music ideal for Qi Gong, Tai Chi, Tai Chi Chuan, Hatha Yoga, Kundalini Yoga, Vinyasa Yoga and Vinyasa Flow Yoga. Music for Yoga, New Age, Relaxation & Meditation. This Video Contains Coloured Pictures and Sweet Music to Help You Relax and Meditate', 'English', 74264, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/idqTK_SEhAk/mqdefault.webp', 'music,meditation,qigong, classes, relax, yoga, ti chi');
INSERT INTO `fun_video` VALUES(55, 'Meditative Exercises of Shaolin Martial Arts : Bad', 'http://www.youtube.com/watch?v=ioFSEjZ7OrM', 228, '360', 'Popular qigong exercises called Eight Pieces of Brocade; learn the meditative, spiritual side of Shaolin Kung Fu in this free martial arts video series.', 'Non-English', 146674, 'Tutorial', 'http://i.ytimg.com/vi/ioFSEjZ7OrM/mqdefault.jpg', 'Meditation, Exercise, qigong, shaolin, martial arts, baduanjin');
INSERT INTO `fun_video` VALUES(56, 'Tai Chi Nation:: Qi Gong (Tai Chi - Chi Kung/Taiji', 'http://www.youtube.com/watch?v=IVV4MW7cVqI', 554, '144', 'Qigong with Matthew Rochford. Taken from the DVD "Qigong". Available from Tai Chi Nation', 'English', 123334, 'Tutorial', 'http://i.ytimg.com/vi/IVV4MW7cVqI/mqdefault.jpg', 'Tai Chi, qigong, matthew, rochford, tai chi, chi kung, taiji');
INSERT INTO `fun_video` VALUES(57, 'Qi Gong: Calentamiento de las articulaciones ( Joi', 'http://www.youtube.com/watch?v=JDCbvdtNNwY', 433, '144', 'Calentamiento previo a la practica de Qigong. Este ejercicio conjunto es realizar un bottom-up. ', 'Non-English', 105159, 'Tutorial', 'http://i.ytimg.com/vi/JDCbvdtNNwY/mqdefault.jpg', 'music, calentamiento, ejercicio, bottom up, previo, qigong');
INSERT INTO `fun_video` VALUES(58, 'Qi Gong powerful qi emission', 'http://www.youtube.com/watch?v=jVNvzZ24JmE', 631, '360', 'Qi gong master healing qi emission', 'Non-English', 999999, 'Entertainment,Others', 'http://i.ytimg.com/vi/jVNvzZ24JmE/mqdefault.jpg', 'gigong, powerful, qi, healing, master');
INSERT INTO `fun_video` VALUES(59, 'Qigong: Eight Piece Brocades Chi Kung', 'http://www.youtube.com/watch?v=KJeyZ43i-xY', 500, '240', 'Master Jesse Tsao on Yang, Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts. Preview this instructional DVD. Master Tsao teaches this ancient Chinese Qigong practice in detail, with repetitions for each move.', 'English', 563959, 'Tutorial', 'http://i.ytimg.com/vi/KJeyZ43i-xY/mqdefault.jpg', 'qigong, brocades, chi kung, jesse tsao, jesse, tsao, master, healing, energy');
INSERT INTO `fun_video` VALUES(60, 'The Chi Center ~ Beginning Qigong Practice', 'http://www.youtube.com/watch?v=KkmQw5qMYs4', 13800, '480', 'Mingtong Gu is an internationally recognized teacher and healer who received his training from a variety of Grandmasters in China and at the world largest Qigong hospital. This "medicine-less" hospital, Zhineng Qigong Center, has treated over 200,000 patients, with over 185 different illnesses, and with a 95% effective improvement rate. He is the founder of The Chi Center and Wisdom Healing Foundation and has taught Qigong to thousands of people in the USA, China, and Europe.', 'English', 143058, 'Tutorial', 'http://i.ytimg.com/vi_webp/KkmQw5qMYs4/mqdefault.webp', 'Chi, qigong, healing, spiritual, world, peace, love, yoga, guru, teacher, chinese, master, breath, earth, energy, tai chi, tao, evolution, humanity, health');
INSERT INTO `fun_video` VALUES(61, 'Grandmaster Yuanming Zhang Qigong', 'http://www.youtube.com/watch?v=KZA1-qC_qyE', 539, '480', 'Born in 1963, into a traditional martial arts family in Sichuan province, Grandmaster Yuanming Zhangs entire life has been devoted to Internal Kung Fu, Qigong and Traditional Chinese Medicine. Mt. Qingcheng, where he grew up, has been a center for Daoism and for Masters of martial arts and Qigong.  Master Zhangs ancestors have studied, nurtured and refined Daoist Qigong practices, acquiring knowledge for improving health and longevity. He is a descendant of Zhang Daoling, the founder of Celestial Master Daoism, who began his teachings at Mt. Qingcheng. The family teachings and techniques were passed down through successive generations to Zhang Sanfeng, the founder of Daoist Taiji.  Master Zhangs Great-Grandfather began to teach him from age three. Young Yuanming showed a special gift for these practices and was singled out by his grandfather and father for early instruction in calligraphy, martial arts and Qigong. He went on to study with twenty-four different masters and hermits', 'English', 72675, 'Application', 'http://i.ytimg.com/vi_webp/KZA1-qC_qyE/mqdefault.webp', 'Yuanming Zhang, qigong, kungfu, martial, arts, chuan, quan taiji, chi, kung, fu, gongfu, master, teacher, neigong, internal, alchemy, wudang, qing, cheng');
INSERT INTO `fun_video` VALUES(62, 'A Beautiful Chinese Guzheng Music', 'http://www.youtube.com/watch?v=Mfsh-pnRNzI', 1331, '480', 'Music is slow , soothing , calming and relaxing to the mind so is suitable for doing your QIGONG practice every morning. Music has been used for Wudang Bagua as well. Uncut version...the duration is1205', 'English', 53965, 'Tutorial', 'http://i.ytimg.com/vi_webp/Mfsh-pnRNzI/mqdefault.webp', 'qigong, music, bagua, Chinese, guzheng, relax, morning');
INSERT INTO `fun_video` VALUES(63, 'Wudang Five Animal Qigong', 'http://www.youtube.com/watch?v=n5FMhYvxvPY', 553, '240', 'One of Wudang qigong is Wudang Five Animal Qigong. It is easy to learn even for beginners seeking health improvements. Wudang Five Animal Qigong is one of the most important exercises practiced by Wudang Taoists. Historically Wudang Taoists were required to practice these five forms daily. This practice is comprised of five major forms including Tortoise, Snake, Dragon, Tiger & Crane. This grouping of forms is derived from some of the most powerful & treasured creatures in traditional Chinese culture', 'English', 127085, 'Application', 'http://i.ytimg.com/vi/n5FMhYvxvPY/mqdefault.jpg', 'Wudang Five Animal Qigong, qigong for beginners, Wudang qi gong, Qigong for health, Wudang qigong, Wudang Tai Chi, qigong exercises, qi gong, learn qigong');
INSERT INTO `fun_video` VALUES(64, 'Qigong Chinese Healing Art', 'http://www.youtube.com/watch?v=ncHziAUvM8I', 322, '240', 'A gentler form of energy practice, Qigong is a beautiful, flowing combination of movements and breathing techniques that stimulate energy flow and promote your natural resiliency to stress and illnes', 'English', 329442, 'Tutorial', 'http://i.ytimg.com/vi/ncHziAUvM8I/mqdefault.jpg', 'chinese, healing, qigong, techniques, energy, resiliency, stress, illness');
INSERT INTO `fun_video` VALUES(65, 'Qigong master projecting his chi energy', 'http://www.youtube.com/watch?v=nu99GRUUN6Y', 608, '240', 'An advanced qigong master projects his chi energy through people. Some pretty wild stuff!', 'English', 1451155, 'Entertainment', 'http://i.ytimg.com/vi/nu99GRUUN6Y/mqdefault.jpg', 'chi, energy, taiji, qigong,advanced');
INSERT INTO `fun_video` VALUES(66, 'Qi Gong Demonstration by Master James Chee in Quan', 'http://www.youtube.com/watch?v=nVdANNX2zP4', 447, '720', 'At the opening ceremony of the 2010 International Shaolin Wuzuquan Federation Conference and Competition, Master James Chee, of International Shaolin Wu Chu Chuan Australia, provided a demonstration of qi application.', 'English', 1111549, 'Application', 'http://i.ytimg.com/vi_webp/nVdANNX2zP4/mqdefault.webp', 'demostration, master, james chee, james, chee, 2010, qigong, ceremony, international');
INSERT INTO `fun_video` VALUES(67, 'Qigong Warmup and Exercise', 'http://www.youtube.com/watch?v=nZ9qM6G6l6g', 1953, '480', 'Qigong Warm up and Exercise', 'English', 217676, 'Tutorial', 'http://i.ytimg.com/vi_webp/yY6L5_5IZlc/mqdefault.webp', 'warm up, qigong, exercise, practice');
INSERT INTO `fun_video` VALUES(68, 'Qigong master projecting his chi energy part 2', 'http://www.youtube.com/watch?v=oGaWhP4lbys', 129, '240', 'This is the same master as in the first video. Once again an amazing display of internal power.', 'Non-English', 607790, 'Application', 'http://i.ytimg.com/vi/oGaWhP4lbys/mqdefault.jpg', 'projecting Energy, qigong, master');
INSERT INTO `fun_video` VALUES(69, 'Sheng Zhen Healing Gong I: Movements 1-5', 'http://www.youtube.com/watch?v=p12vknxpz_o', 548, '240', 'Master Li Junfeng introducing Sheng Zhen Healing Gong I, movements 1-5 of 10. For more information, please visit www.shengzhen.org', 'English', 92131, 'Entertainment,Application', 'http://i.ytimg.com/vi/p12vknxpz_o/mqdefault.jpg', 'Sheng Zhen,healing, gong, movements, master, li junfeng');
INSERT INTO `fun_video` VALUES(70, 'Shaolin Qigong', 'http://www.youtube.com/watch?v=q8qSaW4KkPk', 507, '480', 'Grobmeister Shi Yong Dao vom Shaolintempel Berlin zeigtabungen des Shaolin-Qigong', 'Non-English', 51722, 'Tutorial', 'http://i.ytimg.com/vi/q8qSaW4KkPk/mqdefault.jpg', 'shaolin,qigong, outside');
INSERT INTO `fun_video` VALUES(71, 'Qi Gong Flow For Beginners with Lee Holden - Tease', 'http://www.youtube.com/watch?v=qdudxdtziI4', 445, '240', 'Acclaimed instructor (and PBS favorite) Lee Holden guides you through the gentle moving meditation that is QiGong. Learn how to restore energy, release tension and connect to a powerful source of inner balance in these fluid, nature-inspired moves.', 'English', 298075, 'Tutorial', 'http://i.ytimg.com/vi/qdudxdtziI4/mqdefault.jpg', 'demostration,beginners, lee holden, lee, holden, gigong, flow, teaser');
INSERT INTO `fun_video` VALUES(72, 'DEEP BREATHING MORNING QI GONG - Opening, Cleansin', 'http://www.youtube.com/watch?v=QNgWb3EDXCI', 1445, '480', '15 min Qi Gong Morning preparedness  3 parts: - Opening, Deep Breathing, Earth and Sky - Energetic Cleansing - Warming Up Performed by Bruno at Lotus Center, Ta Kmao, Cambodia Additional movements available in other video lotus.fdl@hotmail.com Made by PRM', 'English', 56734, 'Tutorial', 'http://i.ytimg.com/vi_webp/QNgWb3EDXCI/mqdefault.webp', 'qi, gong, ci, cong, cambodia, bruno, breathing, energy, Khmer, Morning, Health, Natural');
INSERT INTO `fun_video` VALUES(73, 'QI GONG part 1', 'http://www.youtube.com/watch?v=Qp95aASHI8A', 700, '144', 'Qi Gong demonstration. This is the part 1', 'Non-English', 96547, 'Application', 'http://i.ytimg.com/vi_webp/Qp95aASHI8A/mqdefault.webp', 'exercise, qigong, outdoors, group');
INSERT INTO `fun_video` VALUES(74, 'Real Qigong Defies Scientific and Medical Thinking', 'http://www.youtube.com/watch?v=QZJrQY9SuQI', 525, '1080', 'The World Congress on Qigong and Traditional Chinese Medicine is put on by Dr. Effie Chow, a pioneer in getting Traditional Chinese Medicine accepted into mainstream healthcare. She is founder of The East West Academy of Healing Arts based in SF. ', 'English', 77179, 'Entertainment', 'http://i.ytimg.com/vi_webp/QZJrQY9SuQI/mqdefault.webp', 'grandmaster, zhou ting jue, effie chow, san francisco, qigong, martial arts, tai chi, meditation, healing, healer, water, mud, sand, powder, turns mud to san...');
INSERT INTO `fun_video` VALUES(75, 'Ejercicios de Qi Gong Para el Dolor De Cuello - Po', 'http://www.youtube.com/watch?v=R707PK84SDM', 1300, '480', 'Por medio de estos ejercicios de Qi Gong Terapeutico, puedes mejorar la salud de tu cuello y en tan solo 7 dias podrias notar la diferencia en cuanto a alivio del dolor de cuello, mejora de la movilidad, desentumecimiento, agudeza de los sentidos, de la capacidad de pensar con mas claridad, etc.  Estos ejercicios practicados a diario como yo te indico en este vÃ­deo resuelven la mayorÃ­a de los problemas de cuello leves y ocasionales y mejoran muchisimo los agudos y cronicos, que en muchos casos tambien pueden llegar a desaparecer.    Gracias.  Jorge Beltran -- Terapeuta Creador del Curso: http://RecupertaTuSaludConQiGong.com', 'Non-English', 287009, 'Tutorial', 'http://i.ytimg.com/vi/R707PK84SDM/mqdefault.jpg', 'ejercicios, qi gong, chi kung,terapeutico, cuello, rehabilitacion, ejercicios');
INSERT INTO `fun_video` VALUES(76, 'Qigong Demo with Master John Chang', 'http://www.youtube.com/watch?v=RAAB0dbc3Es', 953, '240', 'Master John Chang demonstration of qigong with different instruments', 'English', 826336, 'Tutorial', 'http://i.ytimg.com/vi/RAAB0dbc3Es/mqdefault.jpg', 'demo, demonstration, qigong, master, john chang');
INSERT INTO `fun_video` VALUES(77, 'Tai Chi and Qi Gong [All 5 Chapters]', 'http://www.youtube.com/watch?v=rLxlO0zFaNc', 1525, '240', 'The following video is intended to be an educational tool that features tai chi and qi gong. These exercise therapies are generally considered safe, self-care approaches used to promote a healthy lifestyle. As always, talk to your health care provider if you are using or considering using any CAM modalities so that they can help safely coordinate your care.', 'English', 102922, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi_webp/rLxlO0zFaNc/mqdefault.webp', 'Exercise, introduction, qigong, tai chi, exercises, senior, outdoor, health');
INSERT INTO `fun_video` VALUES(78, 'Zhang Zhuang Qigong', 'http://www.youtube.com/watch?v=RSB84wv1I9E', 5, '240', 'Zhang Zhuang Gong es posiblemente la tecnica de Qigong mas facil y efectiva para aumentar nuestra energia con el fin de mejorar la salud y desarrollar nuestra conciencia. La practica de la postura estatica finalize con el tipico y terapeutico masaje qigong', 'Non-English', 57451, 'Tutorial,Others', 'http://i.ytimg.com/vi/RSB84wv1I9E/mqdefault.jpg', 'music, relax, posture, postura, qigong, tecnica, energy, energia');
INSERT INTO `fun_video` VALUES(79, 'Chinese traditional qi gong treatment for prostate', 'http://www.youtube.com/watch?v=sdJZnFccVnM', 430, '240', 'This was originally aired 2 years ago (2005) on CBC Hemispheres. A unusual story from Taipei, Taiwan about a treatment for prostate problems. I had to record it because it was just so amusing and bizarre. Its based on Qigong (Chi Gong) healing techniques and is said to shrink enlarged prostates and result in healing and improved sexual functions.', 'English', 3060492, 'Tutorial,Others', 'http://i.ytimg.com/vi/sdJZnFccVnM/mqdefault.jpg', 'news, qigong, prostate, treatment, Chinese, traditional');
INSERT INTO `fun_video` VALUES(80, 'Qigong /5 animal', 'http://www.youtube.com/watch?v=sytr0_ufm04', 1058, '480', 'wu qin xi qigong', 'English', 129312, 'Group demo', 'http://i.ytimg.com/vi_webp/sytr0_ufm04/mqdefault.webp', 'chinese, qigong');
INSERT INTO `fun_video` VALUES(81, 'Shaolin Qigong: Luohan 13 Forms Chi Kung', 'http://www.youtube.com/watch?v=tjXPpXHE2UU', 543, '240', 'Chen, Wu, Sun tai chi tyle and Tai Chi sword, broadsword, qigong (Chi gong)for internal energy healing, bio-energy, Shaolin and Wudang Kung-fu martial arts.', 'Non-English', 159485, 'Tutorial,Application', 'http://i.ytimg.com/vi/tjXPpXHE2UU/mqdefault.jpg', 'Shaolin Qigong, luohan, forms, chi kung');
INSERT INTO `fun_video` VALUES(82, 'Master Zhou - Healing Qi Gong', 'http://www.youtube.com/watch?v=Tu7afd2AiDo', 834, '480', 'Qi Gong video with cupping. Filmed on location in Mainland China. Special thanks to the amazing TC Swartz', 'English', 109684, 'Tutorial', 'http://i.ytimg.com/vi_webp/Tu7afd2AiDo/mqdefault.webp', 'Healing,qi gong, qigong, cupping, china, zhou hong');
INSERT INTO `fun_video` VALUES(83, 'Shaolin Monks - Qi Gong', 'http://www.youtube.com/watch?v=tX8mGt0K_JI', 500, '240', 'Amazing acts done by Shaolin Monks with Qi Gong training and experience', 'English', 1487043, 'Entertainment', 'http://i.ytimg.com/vi_webp/tX8mGt0K_JI/mqdefault.webp', 'Kung Fu, National Geographic, Shaolin Monks, China, Martial Arts, Spiritual Practice');
INSERT INTO `fun_video` VALUES(84, 'Understanding QiGong and Qi 3/3', 'http://www.youtube.com/watch?v=tYdX5IP7lOE', 900, '360', '"Excerpt from Dr. Yang, Jwing-Ming''s DVD Qigong Massage, published by YMAA.com  http://ymaa.com/publishing/dvd/qigong...', 'English', 423064, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/tYdX5IP7lOE/mqdefault.webp', 'Qi, Gong, Chi, Dr., Yang');
INSERT INTO `fun_video` VALUES(85, 'Qigong Training Spirit Qi 8 pieces of Silk Brocade', 'http://www.youtube.com/watch?v=U0Z2Np_yhTI', 909, '360', 'Awaken Your Natural Living Energy with Spirit Qi Qigong. Full Mind, Body & Spirit Development. Visit www.spiritqi.com', 'English', 91668, 'Tutorial,Application', 'http://i.ytimg.com/vi/U0Z2Np_yhTI/mqdefault.jpg', 'energy, spirit, qigong, full mind, body, development, group');
INSERT INTO `fun_video` VALUES(86, 'Secret of qigong - part 1', 'http://www.youtube.com/watch?v=uQEL5mWU_Vg', 748, '240', 'http://sevenreview.com  Secret of qigong meditation, healing, health, fast cure remedy, traditional Chinese healing with acupuncture, energy such as reiki also known as Nei gong and qigong. Healing brain tumors, cancers, back pain. The untold secrets are now being revealed from ancient masters and found here http://healthchants.com/ must-see!  7 part series about the source of qigong & the mystic healing energy. Enjoy!', 'English', 114903, 'Entertainment', 'http://i.ytimg.com/vi_webp/uQEL5mWU_Vg/mqdefault.webp', 'Qigong, healing, tai, chi, taiji, acupuncture, health, qigong, neigong, meditation, healthchants.com, chans, spirit, Taoist, secret, exercise');
INSERT INTO `fun_video` VALUES(87, 'Qi Gong, Qigong - Die Grundlagen', 'http://www.youtube.com/watch?v=vKukL9W-Auo', 646, '240', 'Lehr-DVD: - "Qigong-Harmonie in 18 Figuren (Shibashi)" - "Die 8 Brokate Qigong  -Spiel der fÃ¼nf Tiere ( Wu Qin Xi )', 'Non-English', 273610, 'Tutorial,Group demo', 'http://i.ytimg.com/vi_webp/vKukL9W-Auo/mqdefault.webp', 'die, grundlagen, qigong, qi, gong, brokate, group');
INSERT INTO `fun_video` VALUES(88, 'Qigong demonstration', 'http://www.youtube.com/watch?v=WGab9Ux34A4', 143, '480', 'shaolin qigong demonstration, the shaolin monks showing how the qigong works in your body, my teacher shifu Yanxiu Shi and hes shaolin brothers in performance', 'English', 337419, 'Entertainment', 'http://i.ytimg.com/vi_webp/WGab9Ux34A4/mqdefault.webp', 'Yanxiu Shi, shaolin temple, shaolin wheel of life, kungfu masters, karate, qigong, wushu, kungfu, shaolin monks');
INSERT INTO `fun_video` VALUES(89, 'Qigong Beginning Exercises : Qigong Exercises: Gat', 'http://www.youtube.com/watch?v=Wm0T584_Raw', 307, '480', 'Breathing naturally and reaching toward the heavens, learn how to gather chi in Qigong with this free exercise video from a Qigong instructor.', 'English', 225892, 'Tutorial,Application', 'http://i.ytimg.com/vi/Wm0T584_Raw/mqdefault.jpg', 'Exercise, beginning, qigong, heaven, chi,class,classes');
INSERT INTO `fun_video` VALUES(90, 'Qi Gong Part.II', 'http://www.youtube.com/watch?v=x0_pqbrq64g', 420, '480', 'Qi Gong in der Tradition der Shaolin, dargeboten von Shi Yan Lu, www.shaolinzentrum.de, Music by Jean-Pierre Garattoni, music from the album "Qi Gong - Gentle Movements and Ambient Relaxation', 'Non-English', 61127, 'Entertainment', 'http://i.ytimg.com/vi_webp/x0_pqbrq64g/mqdefault.webp', 'Qi Gong, Shi Yan Lu, Jean-Pierre Garattoni, Wellness, Ambient Relaxation, Shaolin, shaolincenter, chillout, chill, relax, Zen, religion');
INSERT INTO `fun_video` VALUES(91, 'How to Practice Qigong Exercises : The Eight Key E', 'http://www.youtube.com/watch?v=xdL09WKBb0Y', 132, '240', 'Learn about the eight key elements of Qigong in this free online video series on practicing Qigong exercises.', 'English', 63144, 'Tutorial,Others', 'http://i.ytimg.com/vi/xdL09WKBb0Y/mqdefault.jpg', 'class,basic,elements,qigong,explanation,exercises');
INSERT INTO `fun_video` VALUES(92, 'Qi Gong for Seniors with Lee Holden', 'http://www.youtube.com/watch?v=Xyip2ZNZYI8', 153, '360', 'Add years to your life AND life to your years with the ancient art of Qi Gong! This unique program is specifically designed to restore youthful vigor, energy and overall well-being.', 'English', 106815, 'Tutorial,Application', 'http://i.ytimg.com/vi/Xyip2ZNZYI8/mqdefault.jpg', 'Senior, Exercise, qigong, outdoor');
INSERT INTO `fun_video` VALUES(93, 'Hidden Qi & Qigong part 4', 'http://www.youtube.com/watch?v=xYX64VWGJgk', 829, '360', 'Qi gong inside view', 'English', 58160, 'Entertainment,Application', 'http://i.ytimg.com/vi_webp/xYX64VWGJgk/mqdefault.webp', 'qigong, china, practice, prostate, treatment, health,class');
INSERT INTO `fun_video` VALUES(94, 'The Best Tutorial to learn Taichi Qigong', 'http://www.youtube.com/watch?v=yK8QmMbCpiY', 2605, '1080', 'Learn Chen Style Taichi Qigong in an easy way', 'English', 65793, 'Tutorial', 'http://i.ytimg.com/vi/yK8QmMbCpiY/mqdefault.jpg', 'wushu, kung fu, martial arts, Karate, tai chi, wing chun, ip man, ninga, parkour, samurai, Free, wooden dummy, fast, shaolin, temple, jet li, jacki chan');
INSERT INTO `fun_video` VALUES(95, 'Taiji Qigong 18', 'http://www.youtube.com/watch?v=ymO7ybqMQkU', 1750, '360', 'Nancy demonstrating by Cottage Lake. Learn more about this form at www.linhousheng.com/articles.php .', 'Non-English', 108339, 'Tutorial', 'http://i.ytimg.com/vi_webp/ymO7ybqMQkU/mqdefault.webp', 'taiji, qigong, Nancy Lucero, relax, outdoors, class');
INSERT INTO `fun_video` VALUES(96, 'Qigong Distant Healing', 'http://www.youtube.com/watch?v=yp_5CRXYL9I', 348, '720', 'http://jisin.jp', 'Non-English', 103743, 'Tutorial', 'http://i.ytimg.com/vi/yp_5CRXYL9I/mqdefault.jpg', 'music,demo, class, solo, performance');
INSERT INTO `fun_video` VALUES(97, 'Ajahn Suthep teaching Qi Gong', 'http://www.youtube.com/watch?v=yY6L5_5IZlc', 4732, '480', 'Ajahn Suthep teaching Qi Gong or Standing Meditation at Vivekavana Solitude Grove, Penang in June, 2011. Ajahn runs through a whole repetoire of movements designed to help balance the body.', 'English', 382542, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/yY6L5_5IZlc/mqdefault.webp', 'class, classes, qigong, ajahn suthep, ajahn,suthep, meditation, group');
INSERT INTO `fun_video` VALUES(98, 'Qi Gong - Medicina Chinesa Tradicional', 'http://www.youtube.com/watch?v=Z2n4WfwIXnk', 1221, '240', 'O Qi Gong e uma tecnica milenar com exercicios que combinam alongamentos, respiracao coordenada, concentracao e posturas facilitadoras da captacao, circulacao e transformacao do Qì (energia ou sopro vital) no corpo. A pratica regular do Qi Gong beneficia a saude e a vitalidade', 'Non-English', 326704, 'Tutorial', 'http://i.ytimg.com/vi_webp/Z2n4WfwIXnk/mqdefault.webp', 'portuguese,medicina,chinesa,tradicional,basic, health, meditation, qigong');
INSERT INTO `fun_video` VALUES(99, 'Qigong Therapy for Neck, Upper Back and Shoulders', 'http://www.youtube.com/watch?v=ZA5f9rYXZTo', 1330, '480', 'Chinese Qigong remedies for pain and rehabilitation of problem areas', 'English', 51457, 'Tutorial', 'https://yt3.ggpht.com/-8Ik6pnMNulM/AAAAAAAAAAI/AAAAAAAAAAA/V_7DMrElJk8/s100-c-k-no/photo.jpg', 'session,lesson,therapy, qigong, benefits, shoulders, neck,upper back');
INSERT INTO `fun_video` VALUES(100, 'Daily 17 min Qi Gong practice with Mingtong', 'http://www.youtube.com/watch?v=ZgRsoPlYHvY', 1712, '360', 'Qi (Chi) means life energy and gong means "cultivation and its benefits. Qigong, an ancient technology and revitalized science of energy healing, has developed through more than 5000 years of Chinese history. Through gentle movement, visualization, sound, breathing and conscious intention, the ancient practice of Qigong energy healing dynamically restores the life energy and creative power within oneself. As the underlying causes of lifes challenges are released, you reconnect with the universal source and bring new and vital energy streams into the flow of life. With this practice, you amplify a web of positive changes for you, your loved ones, and planet Earth.  Mingtong Gu is an internationally recognized teacher and healer who received his training from a variety of Grandmasters in China and at the worlds largest Qigong hospital. This "medicine-less hospital, Zhineng Qigong Center, has treated over 200,000 patients, with over 185 different illnesses, and with a 95% effective ', 'English', 99197, 'Application', 'http://i.ytimg.com/vi_webp/ZgRsoPlYHvY/mqdefault.webp', 'qi, gong, mingtong, daily, practice, lilou, juicy, living, tour');
INSERT INTO `fun_video` VALUES(101, 'Chen Style Tai Chi Silk Reeling Qigong with Jose F', 'http://www.youtube.com/watch?v=zx8E8RdKwag', 832, '480', 'Chen Style Tai Chi Progressive Silk Reeling with Jose Figueroa, DVD ', 'English', 59016, 'Tutorial', 'http://i.ytimg.com/vi/zx8E8RdKwag/mqdefault.jpg', 'introduction, tai chi, qigong, jose Figueroa, jose, figueroa');
INSERT INTO `fun_video` VALUES(102, 'Between Heaven and Earth - Full Qigong Practice', 'http://www.youtube.com/watch?v=zzD4svzG9js', 2051, '1080', 'This video is part of a comprehensive 12 week online qigong training course. See the full course here: http://longwhitecloudqigong.com/onlin... This course has been offered on a ''give freely, receive freely'' (GFRF) basis. You can make a voluntary payment in appreciation for the benefit you receive for this course on the Long White Cloud Qigong website. You can read more about GFRF here: http://www.givefreelyreceivefreely.com/ In this course you will learn:  - To activate the eight extraordinary meridians - Microcosmic and macrocosmic circulation - To connect to the power of Heaven and Earth - Awareness and cleansing of energy fields  I hope you enjoy the course!', 'English', 162390, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/zzD4svzG9js/mqdefault.webp', 'Qigong, Chi, Kung, health, course, online, video, givefreelyreceivefreely, give, freely, receive, John, Munro, Meridians, instructions, breathing, meditation');
