-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Nov 21, 2014 at 07:08 AM
-- Server version: 5.6.20
-- PHP Version: 5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `youthcyb_martialarts`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE IF NOT EXISTS `fun_video` (
  `id` int(11) NOT NULL,
  `title` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080','9999') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` (`id`, `title`, `videolink`, `videolength`, `highestresolution`, `description`, `language`, `viewcount`, `videotype`, `iconimage`, `tag`) VALUES
(1, ' shaolin power', 'http://www.youtube.com/watch?v=_g4vZnGwAac', 1, '240', 'LEARN THE ART ofKUNGFU : http://www.vlawac.com/ ', 'Non-English', 5478242, 'Group demo', 'https://i.ytimg.com/vi/J6Z-ekyyK8o/default.jpg', 'kung fu, art, shaolin Art, Martial Art, Karate, Lesson'),
(2, 'Alexander Lou in Guards of Shaolin [full movie]', 'http://www.youtube.com/watch?v=_vBJtGojKmE', 87, '240', 'Alexander Lou in Guards of Shaolin 1984', 'English', 185625, 'Entertainment', 'http://i.ytimg.com/vi_webp/_vBJtGojKmE/mqdefault.webp', 'Movie, Alexander, Lou, Guards, Shaolin, 1984'),
(3, 'shaolin kung fu Connotation', 'http://www.youtube.com/watch?v=-hCWEcPQ7g0', 3, '144', 'shaolin kung fu Connotation , welcome to shaolin kung fu school , Practicing Shaolin Kung fu, To car', 'Non-English', 76065, 'Group demo', 'http://img.youtube.com/vi/-hCWEcPQ7g0/1.jpg', 'Education, Kung Fu, Shaolin, Connotation, Practice, Kung fu, Shaolin Kung fu, China, Techniques'),
(4, '18 Weapons Of Shaolin', 'http://www.youtube.com/watch?v=-wERr4oge1Y', 3, '480', '18 most commonly used weapons of the shaolin temple. Rare Footage of demonstrations at the Temple Of', 'English', 78746, 'Weapon', 'http://i.ytimg.com/vi/-wERr4oge1Y/mqdefault.jpg', 'Education, 18 Weapons Of Shaolin, Weapons, Temple Of Wu Tang'),
(5, 'Shaolin Kung Fu Techniques : Learn Shaolin Kung Fu', 'http://www.youtube.com/watch?v=0K4Ar8h0yJw', 2, '480', 'Learn Shaolin kung fu stances and how to become a Shaolin Master in this free martial arts instructi', 'English', 875144, 'Tutorial', 'http://i.ytimg.com/vi/0K4Ar8h0yJw/mqdefault.jpg', 'Sports, Education, Techniques, Learn Shaolin Kung Fun Stances, Shaolin Master, Martial Arts, Bruce Wen'),
(6, 'Shaolin Warriors ', 'http://www.youtube.com/watch?v=0klNDWnO-Ks', 3, '240', 'A glimpse of the Stage Show Shaolin Warriors featuring performances by the martial monks of Shaolin', 'English', 186234, 'Entertainment', 'http://i.ytimg.com/vi/0klNDWnO-Ks/mqdefault.jpg', 'Education, Shaolin Warriors, Performance, Martial Monks of Shaolin, LA, Classes'),
(7, 'Shaolin basic kung fu 3: drills, stretching, acrob', 'http://www.youtube.com/watch?v=1lBJZZc1DJM', 37, '360', 'instructor: Shi Deci, from Shaolin temple', 'Non-English', 118680, 'Tutorial', 'http://img.youtube.com/vi/1lBJZZc1DJM/1.jpg', 'Traditional, martial arts, Shaolin'),
(8, 'Shaolin Ex Monk', 'http://www.youtube.com/watch?v=29pcsw7EIsQ', 96, '240', 'Please subscribe if you like the content!!!  Shaolin Ex Monk (1978)  AKA: Renegade Monk Action | Dra', 'English', 722667, 'Entertainment', 'http://i.ytimg.com/vi/29pcsw7EIsQ/mqdefault.jpg', 'Movie, Shaolin Ex Monk, 1978, Suspense'),
(9, 'Action Movies 2014 Full Movie | Shaolin Kids | Com', 'http://www.youtube.com/watch?v=5NVQC3B3804', 87, '480', 'Comedy Movies 2014 ,New Comedy Movies 2014 Full Movie, New comedy movies 2014 full movie english,New', 'Non-English', 86496, 'Entertainment', 'http://i.ytimg.com/vi/5NVQC3B3804/mqdefault.jpg', 'Movie, Shaolin Kids, Comedy, English, Hollywood, Action, Kung Fu, Kung Fu Kids'),
(10, 'Shaolin Kickers - Best of Final', 'http://www.youtube.com/watch?v=5nxxWzPSXso', 5, '240', 'Shaolin Kickers Best Soccer Movie ever ;) Matrix-Special Effekte aus dem Final-Match vom Film Shaoli', 'English', 4791396, 'Entertainment', 'http://i.ytimg.com/vi/5nxxWzPSXso/mqdefault.jpg', 'Movie, Shaolin Kickers, Matrix Effects'),
(11, 'Shaolin Vs. Manchu (1984) - Kung Fu movie starring', 'http://www.youtube.com/watch?v=5xLpaXHueVc', 92, '480', 'Shaolin Vs. Manchu (1984). Kung Fu movie starring Ling Man Hoi, Andy Tam, Suen Kwok-Ming, Lee Gin-Hi', 'English', 54301, 'Entertainment', 'http://i.ytimg.com/vi_webp/5xLpaXHueVc/mqdefault.webp', 'Movie, Shaolin, Manchu, Ling Man Hoi, Andy Tam, Suen Kwok Ming'),
(12, 'Shaolin Kung Fu Stretches & Moves : No Hand Cartwh', 'http://www.youtube.com/watch?v=6fQe14Q7HV4', 2, '480', 'A no-handed cartwheel in the style of Shaolin Kung Fu can stun any audience; learn Kung Fu moves tau', 'English', 990218, 'Tutorial', 'http://i.ytimg.com/vi/6fQe14Q7HV4/mqdefault.jpg', 'Sports, No Hand Cartwheel, Shaolin Kung Fu, Stretches'),
(13, 'Shaolin Monk Balances On 2 Fingers', 'http://www.youtube.com/watch?v=7LkhVeW7VV0', 1, '720', 'There are only two people in the world who can do this stunt. And here''s one of them.\r\n\r\nDon''t forge', 'English', 4180029, 'Entertainment', 'http://i.ytimg.com/vi/i-0I2onmfLM/mqdefault.jpg', 'Balances, 2 Fingers, Shaolin Monk, Stunt'),

(15, 'true power of shaolin kung fu', 'http://www.youtube.com/watch?v=7qHL2PSpecI', 6, '240', 'shaolin kung fu ppl do their thing', 'English', 11924951, 'Group demo', 'http://img.youtube.com/vi/7qHL2PSpecI/1.jpg', 'Sports, Kung Fu, Martial Arts'),
(16, 'The Rebel Of Shaolin (1977)', 'http://www.youtube.com/watch?v=8nja7mlOTC4', 91, '360', 'Two Champions of Shaolin https://www.youtube.com/watch?v=J4eOg...  Sleeping Fist - Opening Credits h', 'English', 147960, 'Entertainment', 'http://i.ytimg.com/vi_webp/8nja7mlOTC4/mqdefault.webp', 'Movie, 1977, Rebel of Shaolin'),
(17, 'Shaolin Strength & Body Conditioning', 'http://www.youtube.com/watch?v=8sF4ru4WGFY', 9, '480', 'For more info on Shifu Yan Lei''s DVDs http://www.shifuyanlei.co.uk/dvd_shao...', 'English', 99811, 'Tutorial', 'http://i.ytimg.com/vi/8sF4ru4WGFY/mqdefault.jpg', 'Tutorial, Strength, Body, Conditioning, Training, Shifu Yan Lei'),
(18, 'Greatest Chinese Kung Fu Weapon: Nunchucks', 'http://www.youtube.com/watch?v=8YezY3SnflQ', 7, '720', 'Greatest Chinese Kung Fu Weapon: Nunchucks also called Nunchaku, Nunchuck, Numchucks, or Er Jie Gun.', 'English', 82614, 'Weapon', 'http://i.ytimg.com/vi/8YezY3SnflQ/mqdefault.jpg', 'Weapon, Nunchucks, Chinese Kung Fu, Nunchaku'),
(19, 'Shaolin kung fu basic movements', 'http://www.youtube.com/watch?v=9f8zb_QKZEo', 47, '360', 'instructor: Shi Deyang, from Shaolin temple', 'Non-English', 1211681, 'Tutorial', 'http://img.youtube.com/vi/9f8zb_QKZEo/1.jpg', 'Shaolin, Kungfu, Movements, Basic, Shi Deyang, Shaolin Temple'),
(20, 'Meditative Exercises of Shaolin Martial Arts : Bad', 'http://www.youtube.com/watch?v=9IGj5vSj4l0', 3, '480', 'Popular qigong exercises called Eight Pieces of Brocade; learn the meditative, spiritual side of Sha', 'English', 224225, 'Tutorial', 'http://i.ytimg.com/vi/9IGj5vSj4l0/mqdefault.jpg', 'Sports, Badauanjin Qigong, Exercises, Meditative, 1, 2'),
(21, 'American Shaolin German Full Movie', 'http://www.youtube.com/watch?v=9rbLGhm9ld8', 101, '360', 'American Shaolin   Drew Carson ist ein typischer amerikanischer Teenager, bis sein größter Rivale Tr', 'Non-English', 348790, 'Entertainment', 'http://i.ytimg.com/vi_webp/9rbLGhm9ld8/mqdefault.webp', 'Movie, German, Shaolin, American, Drew Carson'),
(22, 'Shaolin street fight skills', 'http://www.youtube.com/watch?v=9TajusIENTs', 2, '240', 'a shaolin master,Shi DeJian demonstrate a few practical fighting techniques, here are several links ', 'English', 4660988, 'Tutorial', 'http://i.ytimg.com/vi/9TajusIENTs/mqdefault.jpg', 'Tutorial, Skills, Shi DeJian, Demonstration, Techniques'),
(23, 'Shaolin Warriors - China ', 'http://www.youtube.com/watch?v=a7X_iEfvWho', 2, '240', 'Shaolin Warriors is more than a Kung-fu show. The four scenes of summer, autumn, winter and spring d', 'English', 420680, 'Entertainment', 'http://i.ytimg.com/vi/a7X_iEfvWho/mqdefault.jpg', 'Entertainment, Comedy, Shaolin'),
(24, 'Shaolin Soccer - First Rounds of the Tournament - ', 'http://www.youtube.com/watch?v=AhKhp8l6EFM', 5, '480', 'The first rounds of the Tournament before the Final Match.', 'English', 3649405, 'Entertainment', 'http://i.ytimg.com/vi/AhKhp8l6EFM/mqdefault.jpg', 'Movie, Tournament, Shaolin, Soccer, Final Match'),
(25, 'shaolin breaking power ', 'http://www.youtube.com/watch?v=apiT5vSJ6eM', 1, '240', 'Zhang Li Peng breaks staff on his belly', 'English', 6015761, 'Entertainment,Application', 'http://i.ytimg.com/vi/apiT5vSJ6eM/mqdefault.jpg', 'Sports, breaking power, Zhang Li Peng, Belly, Staff'),
(26, 'Real ShaoLin kungfu unbelievable!', 'http://www.youtube.com/watch?v=Boc8SI2ADJ0', 16, '360', 'Shaolin kung fu demonstration', 'English', 1094247, 'Others', 'http://img.youtube.com/vi/Boc8SI2ADJ0/1.jpg', 'Shaolin, Kung Fu, Demonstration, Real Shaolin, Techniques'),
(27, 'Shaolin Temple 4', 'http://www.youtube.com/watch?v=CsMVEoEEfWQ', 87, '240', 'Please subscribe if you like the content!!!  Shaolin Temple 4 (1981) AKA: He Nan Song Shan Shao Lin ', 'English', 641134, 'Entertainment', 'http://i.ytimg.com/vi_webp/CsMVEoEEfWQ/mqdefault.webp', 'Movie, Shaolin Temple, 4, 1981'),
(28, 'Shaolin Iron Skill Kung Fu : Bar Breaking with Kun', 'http://www.youtube.com/watch?v=D24w5xA19-0', 3, '480', 'Breaking bars with the Iron Head technique is an advanced Kung Fu skill; learn the Iron Head Shaolin', 'English', 134149, 'Tutorial', 'http://i.ytimg.com/vi/D24w5xA19-0/mqdefault.jpg', 'Sports, Bar Breaking, Kung Fu, Iron Head, Iron Skill'),
(29, 'shaolin monks demonstration', 'http://www.youtube.com/watch?v=DV5AB317oBs', 10, '480', 'Shaolin Monks performing a routine', 'English', 248111, 'Group demo', 'http://img.youtube.com/vi/DV5AB317oBs/1.jpg', 'Kung Fu, Shaolin, Martial Arts, Monks, Demonstration, Routine'),
(30, 'Shaolin warrior training ', 'http://www.youtube.com/watch?v=EMkz7lTGzQ8', 81, '240', '', 'Non-English', 8534386, 'Entertainment', 'http://i.ytimg.com/vi/EMkz7lTGzQ8/mqdefault.jpg', 'Education, Technique, Training'),
(31, 'Shaolin Kung Fu (exploding the meat myth)', 'http://www.youtube.com/watch?v=eZwmluSn_T0', 8, '480', 'Think you need meat to be fit and strong? You can explode that myth with two words: Shaolin Monk!', 'English', 1633911, 'Group demo', 'http://img.youtube.com/vi/eZwmluSn_T0/1.jpg', 'Shaolin, Monks, Kung Fu, Meat Myth, Fit, Strong, Monk'),
(32, 'Shaolin (Pelicula completa)', 'http://www.youtube.com/watch?v=F_3ThjPuLsE', 132, '360', 'Un señor de la guerra que se refugia en un monasterio Shaolin para protegerse del ataque de un rival', 'Non-English', 246014, 'Entertainment', 'http://i.ytimg.com/vi/F_3ThjPuLsE/mqdefault.jpg', 'Movie, Shaolin, Spanish, Family'),
(33, 'Shaolin Kung Fu Master', 'http://www.youtube.com/watch?v=Fbvo3p1kLwA', 87, '240', 'Attack the points and joints technique. Phoenix eye Wang Kwan Hsung, snake Chang Yi.', 'English', 69292, 'Entertainment', 'http://i.ytimg.com/vi_webp/Fbvo3p1kLwA/mqdefault.webp', 'Movie, Shaolin Kung Fu, Master, Phoenix, Wang, Kawn, Hsung, Chang Yi'),
(34, 'National Geographic Documentary Myths Logic Of Sha', 'http://www.youtube.com/watch?v=FPVUn6rQfPo', 48, '240', 'National Geographic Documentary Myths Logic Of Shaolin Kung', 'English', 165537, 'Entertainment', 'http://i.ytimg.com/vi/FPVUn6rQfPo/mqdefault.jpg', 'Education, Myths Logic of Shaloing Kung Fu, Buddhist, Srilanka'),
(35, 'Fight Quest S01E01 KungFu Full', 'http://www.youtube.com/watch?v=fWEuWXEZepU', 48, '480', 'Osu  In each episode, Jimmy and Doug will explore a new location identified with a style of fighting', 'English', 449363, 'Entertainment', 'http://i.ytimg.com/vi/fWEuWXEZepU/mqdefault.jpg', 'Entertainment, Fight Quest, Kung Fu, Jimmy, Doug, Style of Fighting'),
(36, 'La Furia de Shaolín (Elton Chong, Eagle Han Ying)', 'http://www.youtube.com/watch?v=GiMUYI8fjy0', 85, '720', 'TO, The Shaolin Drunk Monkey.  Starring, Elton Chong, Eagle Han Ying.  Blog: http://suciotatami.com/', 'Non-English', 677162, 'Entertainment', 'http://i.ytimg.com/vi/GiMUYI8fjy0/mqdefault.jpg', 'Movie, La Furia De Shaolin, Elton Chong, Eagle Han Ying'),
(37, 'The Shaolin Temple FULL MOVIE 1982 (Jet Li)', 'http://www.youtube.com/watch?v=gqagZNrKSgs', 61, '360', 'The Tang emperor is betrayed by one of his generals, who installs himself as emperor in the East Cap', 'English', 4813792, 'Entertainment', 'http://img.youtube.com/vi/gqagZNrKSgs/1.jpg', 'Shaolin, movie, martial arts, 1982, Jet Li,Temple'),
(38, 'Shaolin 3-section staff (san jie gun)', 'http://www.youtube.com/watch?v=h6B9ac7MSHk', 52, '360', 'instructor: Shi Deci, from Shaolin temple', 'Non-English', 70833, 'Tutorial', 'http://img.youtube.com/vi/h6B9ac7MSHk/1.jpg', 'Traditional, Martial Arts, Shaolin Kung Fu, 3-Section Staff, San Jie Gun'),

(40, 'JET- Li Shaolin Temple ( Kids from Shaolin 1984) F', 'http://www.youtube.com/watch?v=HsjMzgCIru8', 103, '360', 'Shaolin kung fu movie', 'English', 76771, 'Entertainment', 'http://img.youtube.com/vi/HsjMzgCIru8/1.jpg', 'Shaolin, Movie, Comedy, 1984, Marial Arts, Jet Li'),
(41, 'totally realistic shaolin kung fu fighting', 'http://www.youtube.com/watch?v=i-0I2onmfLM', 3, '240', 'everybody was kung fu fighting XD  ok heres a exerpt from a shaolin kung fu documentary ;P', 'Non-English', 4252319, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/i-0I2onmfLM/mqdefault.jpg', 'Entertainment, Realistic, Fighting, Shaolin'),
(42, 'Shaolin Super Dragon (1982)', 'http://www.youtube.com/watch?v=I8j6Xq2B5ys&noredirect=1', 88, '480', 'We do not own the copyrights to this movie, they belong to © 2010 Baseline and © 2010 All Media Guid', 'English', 419505, 'Entertainment', 'http://i.ytimg.com/vi_webp/I8j6Xq2B5ys/mqdefault.webp', 'Movie, 1982, Shaolin Super Dragon'),
(43, 'Shi Baohua in The Young Hero of Shaolin (1984) eng', 'http://www.youtube.com/watch?v=iGNC2NQiK_w', 101, '360', 'Fong Sai-Yuk (Mandarin: Fang Shiyu) is one of those Chinese folk heroes who has gotten almost as muc', 'English', 82593, 'Entertainment', 'http://i.ytimg.com/vi/iGNC2NQiK_w/mqdefault.jpg', 'Movie, Shi Baohua, Hero of Shaolin, 1984, English'),
(44, 'Shaolin finger hand functional grip strength Stron', 'http://www.youtube.com/watch?v=j26rnqGvtMk', 1, '480', 'Building finger, grip and functional hand strength can be easily done with two simple things. Bucket', 'English', 164653, 'Tutorial', 'http://img.youtube.com/vi/j26rnqGvtMk/1.jpg', 'Shaolin Kung Fu, Kung Fu Grip, Building Finger, Shaolin Finger'),
(45, '[1976]Shaolin Chamber Of Death', 'http://www.youtube.com/watch?v=jTj0tjnXDJM', 107, '360', '', 'English', 55934, 'Entertainment', 'http://i.ytimg.com/vi_webp/jTj0tjnXDJM/mqdefault.webp', 'Movie, 1976, Shaolin Chamber of Death, China'),
(46, 'Kung Fu Weapon Training & Meihuaquan : Rotating Bo', 'http://www.youtube.com/watch?v=Keyp-nYY8lE', 2, '480', 'Practice the art of the rotating bo staff in Shaolin Kung Fu; learn Shaolin weapon training and Kung', 'English', 251549, 'Tutorial', 'http://i.ytimg.com/vi/Keyp-nYY8lE/mqdefault.jpg', 'Sports, Shaolin Kung Fu, Weapon, Meihuaquan, Rotation Bo Staff'),
(47, 'Shaolin Masters', 'http://www.youtube.com/watch?v=kG2OdAKz9ew', 22, '1080', 'Shaolin Masters give a demonstration of their skill at Ngong Ping Village.', 'Non-English', 101569, 'Weapon,Group demo', 'http://img.youtube.com/vi/kG2OdAKz9ew/1.jpg', 'Martial, Arts, Shaolin, Masters, Ngong Ping Village, Demonstration'),
(48, 'Shaw Brothers Kung Fu Shaolin Challenges Ninja', 'http://www.youtube.com/watch?v=kNRo28nTEvw', 103, '240', 'Shaolin vs ninja', 'English', 255208, 'Entertainment', 'http://i.ytimg.com/vi_webp/kNRo28nTEvw/mqdefault.webp', 'Movie, Shaw Brothers, Kung Fu, Challeges Ninja'),
(49, 'Shaolin Warrior', 'http://www.youtube.com/watch?v=LeP_AcmIzqU', 2, '480', 'If you want to win a fight or defend yourself against an attacker then your punches and kicks need t', 'English', 855756, 'Tutorial,Others', 'http://i.ytimg.com/vi/LeP_AcmIzqU/mqdefault.jpg', 'Sports, Shifu Yan Lei, 34th Generation, China, Shaolin Warriro'),
(50, 'The Empty Mind - Shaolin Temple Warrior Monks', 'http://www.youtube.com/watch?v=Llqup1Uir6k', 4, '240', 'This is a clip of the Shaolin Temple scene from The Empty Mind Documentary. These warrior monks are ', 'English', 1008166, 'Entertainment', 'http://i.ytimg.com/vi/Llqup1Uir6k/mqdefault.jpg', 'Sports, Empty Mind, Shaolin Temple, Warrior, Monks'),

(52, 'Shaolin Kung fu - Shaolin monks Documentary', 'http://www.youtube.com/watch?v=mk7Em455ao8', 49, '240', 'A documentary about the life at the Shaolin Temple', 'English', 63052, 'Entertainment', 'http://img.youtube.com/vi/mk7Em455ao8/1.jpg', 'Kung Fu, Martial Arts, Shaolin, Documentary, Monks, Shaolin'),
(53, 'Shaolin Kung Fu Stretches & Moves : Butterfly Kick', 'http://www.youtube.com/watch?v=mO2Skxg_GLQ', 2, '480', 'The butterfly kick is a spectacular Kung Fu move seen in many films; learn Kung Fu moves taught at r', 'English', 4738343, 'Tutorial', 'http://i.ytimg.com/vi/mO2Skxg_GLQ/mqdefault.jpg', 'Sports, Stretches, Moves, Butterfly Kick, Shaolin Kung Fu'),
(54, 'Shaolin kung fu 18 basic combat methods', 'http://www.youtube.com/watch?v=N0ylNz9qLhM', 41, '360', 'instructor: Shi Decheng, from Shaolin temple', 'English', 518316, 'Tutorial', 'http://img.youtube.com/vi/N0ylNz9qLhM/1.jpg', 'Sport, Shaolin, Kung Fu, 18 Basic Combat, Techniques, Shi Decheng'),
(55, 'The real Shaolin warrior training', 'http://www.youtube.com/watch?v=NAzOVV5oRRk', 81, '240', '  http://youtu.be/XhHM2nBEEuo  https://www.facebook.com/romaindesboi...', 'Non-English', 154520, 'Entertainment', 'http://i.ytimg.com/vi/NAzOVV5oRRk/mqdefault.jpg', 'How to & Style, Training, Warrior, Real Shaolin'),
(56, 'Shaolin Training', 'http://www.youtube.com/watch?v=nHIc9nm7vB4', 7, '480', 'Shaolin kids in training. The song playing is Fearless from Jay Chou', 'English', 1094947, 'Entertainment', 'http://i.ytimg.com/vi/nHIc9nm7vB4/mqdefault.jpg', 'Sports, Shaolin, Los Angeles, Feerless, Jay Chou'),
(57, 'Deadliest Warrior, Maori Vs Shaolin Monk hawaiian ', 'http://www.youtube.com/watch?v=NrNqGuylAno', 5, '240', 'This is a short intro for myself, I am an actor as well as a special fx artist. In this clip Im givi', 'English', 88362, 'Entertainment', 'http://i.ytimg.com/vi/NrNqGuylAno/mqdefault.jpg', 'Deadliest Warrior, Maori, Shaolin Monk, Hawaiian, Weapon maker'),
(58, '5 tecniche shaolin kung fu', 'http://www.youtube.com/watch?v=P-bnC4iaslg', 5, '240', 'gli antichi monaci shaolin,osservando gli animali,presero spunto per perfezionare le loro tecniche d', 'Non-English', 4467500, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/P-bnC4iaslg/mqdefault.jpg', 'Tutorial, techniche, Shaolin, Kung Fu'),
(59, 'Master Moves of Kung Fu : Human Weapon', 'http://www.youtube.com/watch?v=P0ZZvslACPc', 4, '360', 'History Channel : Human Weapon', 'English', 167396, 'Entertainment,Weapon', 'http://i.ytimg.com/vi_webp/P0ZZvslACPc/mqdefault.webp', 'Weapon, Deadly, 1962'),
(60, 'Shaolin Warrior - Fighting Punches And Kicks ', 'http://www.youtube.com/watch?v=pvndcA3-wlQ', 2, '240', 'If you want to win a fight or defend yourself against an attacker then your punches and kicks need t', 'English', 110404, 'Entertainment', 'http://i.ytimg.com/vi/pvndcA3-wlQ/mqdefault.jpg', 'Sports, Martial Arts, Techniques, Fighting'),
(61, 'Meditative Exercises of Shaolin Martial Arts : Sea', 'http://www.youtube.com/watch?v=QUF8tNJ-Z6s', 2, '480', 'Shaolin monks practice a seated meditation based on buddhist traditions; learn the meditative, spiri', 'English', 89370, 'Tutorial', 'http://i.ytimg.com/vi/QUF8tNJ-Z6s/mqdefault.jpg', 'Sports, Shaolin, Martial Arts. Seated Buddhist. Meditation'),
(62, 'Top Ten Kungfu Weapons', 'http://www.youtube.com/watch?v=RKDD_EIw7kU', 47, '360', 'a video by National Geographic showing the top 10 deadly Kungfu weapons ! Caution !......... Never t', 'English', 103259, 'Entertainment', 'http://i.ytimg.com/vi_webp/RKDD_EIw7kU/mqdefault.webp', 'Entertainment, Kung Fu, Weapons, 10 Deadly, National Geographic'),
(63, 'Chiang Sheng in Five Fighters from Shaolin [1982]', 'http://www.youtube.com/watch?v=Sn1c_i5wXPY', 86, '360', '&#23436;&#20840;&#12394;&#20013;&#22269;&#12398;&#26144;&#30011; ----- &#20013;&#22269;&#12398;&#203', 'English', 217374, 'Entertainment', 'http://i.ytimg.com/vi/Sn1c_i5wXPY/mqdefault.jpg', 'Movie, 1982, Chiang Sheng, Five Fighters, Shaolin'),
(64, 'Shaolin meteor hammer (liu xing chui)', 'http://www.youtube.com/watch?v=SxPO6nwQvxY', 41, '360', 'instructor: Shi Deyang, from Shaolin temple', 'Non-English', 95003, 'Tutorial', 'http://img.youtube.com/vi/SxPO6nwQvxY/1.jpg', 'Shaolin, Weapon, Training'),
(65, 'Shaolin Iron Skill Kung Fu : Training for Kung Fu ', 'http://www.youtube.com/watch?v=TGK-OYlX6Es&list=PLfWVsBrYUZKwr2Fj7VMKzmoWtkIOfVsXK', 1, '480', 'Training for Iron Body in Kung Fu is hard work with serious results; learn the Iron Body Shaolin Kun', 'English', 230134, 'Tutorial', 'http://img.youtube.com/vi/TGK-OYlX6Es/1.jpg', 'Martial, Arts, Shaolin, Iron, Training'),
(66, 'Shaolin Iron Skill Kung Fu : Leg Training for Iron', 'http://www.youtube.com/watch?v=Ua3jXKIycSk', 2, '480', 'The Iron Body skill strengthens legs for Kung Fu readiness and power; learn the Iron Body Shaolin Ku', 'English', 354682, 'Tutorial', 'http://i.ytimg.com/vi/Ua3jXKIycSk/mqdefault.jpg', 'Sports, Iron Skill Kung Fu, Leg Trainning, Body, School. Techniques'),
(67, 'Real Shaolin Kung Fu Master', 'http://www.youtube.com/watch?v=VFzYRuuxPLk', 2, '480', 'Shaolin Kung Fu Master show many acrobatics, like summer sault, jumps and more, cooooool', 'English', 3966238, 'Entertainment', 'http://i.ytimg.com/vi/VFzYRuuxPLk/mqdefault.jpg', 'Shaolin Kung Fu, Master, Acrobatics, Sault, Jumps'),
(68, 'BBC: Extreme Pilgrim - Shaolin Monastery', 'http://www.youtube.com/watch?v=vIAVx5KHHZ0', 59, '360', 'COPYRIGHT TO BBC. FOR INFORMATIVE REASONS ONLY. I AM NOT THE OWNER OF THIS VIDEO. NO INFRINGEMENT IN', 'English', 213893, 'Entertainment', 'http://i.ytimg.com/vi_webp/vIAVx5KHHZ0/mqdefault.webp', 'Movie, Extreme Pilgrim, Monastery, Shaolin'),
(69, 'Man punches Shaolin Monk ', 'http://www.youtube.com/watch?v=w26-BwJ9QcQ', 1, '480', 'Shaolin Martial Arts School near Hong Kong China, Man from USA and another from England both punch S', 'Non-English', 10297768, 'Entertainment,Application', 'http://i.ytimg.com/vi/w26-BwJ9QcQ/mqdefault.jpg', 'People &amp; Blogs, Man Punches, Shaolin, Monk, Martial Arts School, Hong Kong'),
(70, 'Very rare fight shaolin kung fu vs. Korean tae kwo', 'http://www.youtube.com/watch?v=wMJ_b9uV1Lo', 3, '240', 'rare fight a shaolin ight vs. a Korean tae kwon do master', 'English', 10340695, 'Entertainment', 'http://i.ytimg.com/vi/wMJ_b9uV1Lo/mqdefault.jpg', 'Sports, KOrean Tae Kwon Do, Kung Fu, Fight, Master'),
(71, 'Shaolin kung fu acupressure combat (dian xue)', 'http://www.youtube.com/watch?v=y5q4dtP6BpU', 52, '360', 'Instructor: Shi Deyang, from Shaolin temple', 'Non-English', 565789, 'Tutorial,Group demo', 'http://img.youtube.com/vi/y5q4dtP6BpU/1.jpg', 'Traditional, Martial arts, Shaolin kung fu, Combat, Dian Sue, Shaoin temple'),
(72, 'Les Pouvoirs Mysterieux Des Moines Shaolin', 'http://www.youtube.com/watch?v=yuD9yEI7lKo', 133, '360', 'Les Pouvoirs Mysterieux Des Moines Shaolin documentaire complet en français  arts martiaux, art mart', 'Non-English', 127981, 'Entertainment', 'http://i.ytimg.com/vi_webp/yuD9yEI7lKo/mqdefault.webp', 'Education, Les Pouvoirs, Des Moiness Shaolin, France'),
(73, 'Shaolin Kung Fu Training', 'http://www.youtube.com/watch?v=Z4-s8TBB6dw', 5, '240', 'This is a video about training shaolin monks.', 'English', 945961, 'Tutorial,Group demo', 'http://img.youtube.com/vi/Z4-s8TBB6dw/1.jpg', 'Shaolin, kungfu, Training, Monks'),
(74, 'South Shaolin Vs. North Shaolin', 'http://www.youtube.com/watch?v=ZDMKRH5Nmx4', 86, '144', 'South Shaolin Vs. North Shaolin (1984)', 'English', 149101, 'Entertainment', 'http://img.youtube.com/vi/ZDMKRH5Nmx4/1.jpg', 'Shaolin, movie, South Shaolin, North Shaolin, 1984'),
(75, 'Yin Shou Gun (Shaolin Stick Fighting)', 'http://www.youtube.com/watch?v=ZHvvEKpkLw4', 6, '720', 'This is a short documentary about the history of shaolin stick fighting and in-particular the Yin Sh', 'English', 263625, 'Weapon, Entertainment, Shaolin, Stick Fighting, Yin Shou Gun', 'http://i.ytimg.com/vi_webp/ZHvvEKpkLw4/mqdefault.webp', 'Weapon, Entertainment'),
(76, 'Shaolin monk KO world Taekwondo champion Monje Sha', 'http://www.youtube.com/watch?v=ZPAn2AIZFj8', 8, '360', 'Shaolin monk KO world Taekwondo champion Monje Shaolin vs Campeón taekwondo', 'Non-English', 1361504, 'EEntertainment, KO, Shaolin monk, Taekwondo, Monje, Champeo', 'http://i.ytimg.com/vi/ZPAn2AIZFj8/mqdefault.jpg', 'Entertainment');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
