-- phpMyAdmin SQL Dump
-- version 2.11.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Dec 10, 2014 at 12:45 AM
-- Server version: 5.5.40
-- PHP Version: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `youthcyb_schumann`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE `fun_video` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=61 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` VALUES(1, 'Wing Chun - The Ultimate Demonstration', 'http://www.youtube.com/watch?v=_Ui6rj58DA0', 2, '360', ' Here''s a video demonstration in florida of my Sifu, doing Wing Chun. Just the most incredible wing chun demonstration ever. Literally demonstrating a ton of advance techniques, and for those of you who''ve never seen it, there''s more to wing chun then doing lousy low level chain punches.', 'English', 2746943, 'Application', 'http://i.ytimg.com/vi/_Ui6rj58DA0/mqdefault.jpg', 'incredible, demonstration, legendary');
INSERT INTO `fun_video` VALUES(2, 'Wing Chun and Grandmaster IP Man', 'http://www.youtube.com/watch?v=-0QOjzAsUDg', 4, '480', 'A clip showing the grandmaster IP man performing wing chun moves.', 'Non-English', 1405939, 'Application', 'https://i.ytimg.com/vi/-0QOjzAsUDg/mqdefault.jpg', 'wing chun, fight, ip man, grandmaster');
INSERT INTO `fun_video` VALUES(3, 'Wing Chun Dummy - FAST!', 'http://www.youtube.com/watch?v=0xxHGCSjejE', 1, '240', ' One of Shifu Ripski''s Wing Chun teachers freestyling on the wooden dummy.', 'English', 1066089, 'Tutorial', 'http://i.ytimg.com/vi/0xxHGCSjejE/mqdefault.jpg', 'Shifu Ripski, freestyle, wooden dummy');
INSERT INTO `fun_video` VALUES(4, 'Wing Chun Training inch punch', 'http://www.youtube.com/watch?v=1f7td8Hc-V4', 2, '360', ' A Wing Chun Practitioner goes to a Karate school to challenge them and test his abilities.', 'Non-English', 1184602, 'Entertainment', 'https://i.ytimg.com/vi/uCv70BHtDf0/mqdefault.jpg', 'A Wing Chun Practitioner goes to a Karate school to challenge them and test his abilities.');
INSERT INTO `fun_video` VALUES(5, 'Wing Chun vs TKD HARD CORE FULL CONTACT)', 'http://www.youtube.com/watch?v=1uG2hBcfVTQ', 1, '360', ' a 3 mths WC student vs a TKD 1 mth student', 'Non-English', 734919, 'Group demo', 'http://i.ytimg.com/vi/1uG2hBcfVTQ/mqdefault.jpg', 'fight, demonstration, students');
INSERT INTO `fun_video` VALUES(6, 'Wing Chun Lesson 2: basic leg exercise with twist', 'http://www.youtube.com/watch?v=2isLXQ-Gi70', 2, '360', 'You''ve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online.', 'English', 736299, 'Tutorial', 'http://i.ytimg.com/vi/2isLXQ-Gi70/mqdefault.jpg', 'learn, how to, wing Chun, techniques, modern world');
INSERT INTO `fun_video` VALUES(7, 'Wing Chun-techniques', 'http://www.youtube.com/watch?v=4N4Iyl-Efx4', 1, '240', ' That is great video I very like that', 'English', 609296, 'Group demo', 'http://i.ytimg.com/vi/4N4Iyl-Efx4/mqdefault.jpg', 'great, like, awesome');
INSERT INTO `fun_video` VALUES(8, 'BOXING champion VS WING CHUN MASTER', 'http://www.youtube.com/watch?v=5AKFNCIJdvA', 3, '360', 'The Ving Tsun guy claimed that he will punish me by his "Scientific Ving Tsun" and show me the "right way" of fighting. He was also proud of winning the competition of Sanda as follow', 'Non-English', 769794, 'Group demo', 'http://i.ytimg.com/vi/5AKFNCIJdvA/mqdefault.jpg', 'The fight, science, Sanda');
INSERT INTO `fun_video` VALUES(9, 'Wing Chun: Finishing Quickly', 'http://www.youtube.com/watch?v=6JoJbEghpbc', 6, '480', '  A quick look at finsihing a fight quickly', 'English', 1338852, 'Tutorial', 'https://i.ytimg.com/vi/6JoJbEghpbc/mqdefault.jpg', 'quick, finish, submission');
INSERT INTO `fun_video` VALUES(10, 'Bruce Lee - Wing Chun', 'http://www.youtube.com/watch?v=6LhRIk_yCQU', 1, '480', ' The young Bruce Lee and the Wing Chun.', 'Non-English', 618964, 'Group demo', 'http://i.ytimg.com/vi/6LhRIk_yCQU/mqdefault.jpg', 'young, Bruce Lee, history');
INSERT INTO `fun_video` VALUES(11, 'Wing Chun Basic Techniques part 1', 'http://www.youtube.com/watch?v=7ic3Y9Jh3VE', 10, '480', 'Basic theory of how to perform wing chun moves.', 'English', 1351812, 'Tutorial', 'https://i.ytimg.com/vi/7ic3Y9Jh3VE/mqdefault.jpg', 'wing chun, theory, demo, techniques');
INSERT INTO `fun_video` VALUES(12, 'Wing Chun Training - Lesson 1 Punch Drill', 'http://www.youtube.com/watch?v=8jMRT98sWIQ', 4, '480', 'You''ve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online. Click here http://wingchunmaster.tv.', 'English', 553060, 'Tutorial', 'https://i.ytimg.com/vi/8jMRT98sWIQ/mqdefault.jpg', ' techniques, modern world');
INSERT INTO `fun_video` VALUES(13, 'Wing Chun Lesson 1:Basic leg excercise', 'http://www.youtube.com/watch?v=8w9tKNWIqyM', 2, '360', ' You ve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online. Click here ', 'English', 1400039, 'Application', 'https://i.ytimg.com/vi/8w9tKNWIqyM/mqdefault.jpg', 'full contact, Muay Thai, boxing, karate, anyone');
INSERT INTO `fun_video` VALUES(14, 'Wing Chun Training YouTube - With Master Wong EPS ', 'http://www.youtube.com/watch?v=A8fxnQGfXiQ', 5, '480', ' You''ve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online.\r\n', 'English', 968339, 'Tutorial', 'http://i.ytimg.com/vi/A8fxnQGfXiQ/mqdefault.jpg', 'learn how to use wing Chun techniques in the modern world.');
INSERT INTO `fun_video` VALUES(15, 'Shawn Obasi Wing Chun VS Wrestler', 'http://www.youtube.com/watch?v=B2Nt2YSTNNA', 3, '480', ' Wing Chun/ BJJ Fighter VS Wrestler- In this fight I wasn''t allowed to throw knees,elbows or kicks.', 'English', 1146505, 'Entertainment', 'http://i.ytimg.com/vi/B2Nt2YSTNNA/mqdefault.jpg', 'fight, throw knees,elbows, kicks');
INSERT INTO `fun_video` VALUES(17, 'MMA vs. Wing Chun', 'http://www.youtube.com/watch?v=DhETnNWajrA', 2, '480', ' Daze and be amazed by this incredibly fair, dead even, totally equal match up. Wing Chun fighter David Levicki defeats Japanese Shooto fighter Kazuhiro Kusayamagi and proves beyond a shadow of doubt WC', 'Non-English', 904454, 'Entertainment', 'http://i.ytimg.com/vi/DhETnNWajrA/mqdefault.jpg', 'fight, David Levicki, Japanese');
INSERT INTO `fun_video` VALUES(18, 'BLOODY Muay Tai Wing Chun', 'http://www.youtube.com/watch?v=dTGeH5Fr8p0', 2, '240', ' Insane Fights Pure Explosive Bone Breaking Fighting Muay Tai with Wing Chun Jiu Jitsu Jujutsu Hapkido', 'English', 1318158, 'Group demo', 'http://i.ytimg.com/vi/dTGeH5Fr8p0/mqdefault.jpg', 'Insane Fights, Pure, Explosive, Bone Breaking, Fighting, bloody');
INSERT INTO `fun_video` VALUES(19, 'Wing Chun Dummy 116', 'http://www.youtube.com/watch?v=eBUmyrp0-QU', 2, '240', ' You''ve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online.', 'English', 1441384, 'Application', 'http://i.ytimg.com/vi/eBUmyrp0-QU/mqdefault.jpg', 'techniques, modern world');
INSERT INTO `fun_video` VALUES(20, 'Ip Man ( Wing Chun ) - Final Fight', 'http://www.youtube.com/watch?v=g4fKTwi1F_o', 4, '480', ' Ip Man is a 2008 Hong Kong semi biographical martial arts film very loosely based on the life of Ip Man, a grandmaster of the martial art Wing Chun and master of Bruce Lee. The film focuses on events in Ip', 'English', 3584220, 'Entertainment', 'https://i.ytimg.com/vi/g4fKTwi1F_o/mqdefault.jpg', 'Ip Man,2008, film, Hong Kong, semi biographical');
INSERT INTO `fun_video` VALUES(21, 'Donnie Yen Wing Chun and Tai Chi performance', 'http://www.youtube.com/watch?v=Gd2A8L87v2I', 4, '360', ' Donnie Yen performs during the grand variety show as part of the ceremony on the 15th anniversary of Hong Kong, June 30, 2012.', 'Non-English', 2467485, 'Entertainment', 'http://i.ytimg.com/vi/Gd2A8L87v2I/mqdefault.jpg', 'Donnie Yen, performing, grand variety show');
INSERT INTO `fun_video` VALUES(22, 'Wing Chun - Chi Sao fast and slow mo', 'http://www.youtube.com/watch?v=GiQRlr5NCwk', 2, '240', ' Here you have chi sao demonstrated in both regular speed and slow mo', 'English', 891323, 'Tutorial', 'http://i.ytimg.com/vi/GiQRlr5NCwk/mqdefault.jpg', 'chi sao, demonstrated, regular, speed, slow motion');
INSERT INTO `fun_video` VALUES(23, 'Bruce lee''s wing chun (high quality) ', 'http://www.youtube.com/watch?v=hBxqptNa6-8', 4, '480', 'clip starts out with bruce doing some fancy stuff to titillate the ladies. The remainder of the clip shows you Bruce''s great wing chun skill.  Its rumored that for the camera, he had to slow himself down so if whats in the clip is considered slow then....what was his fastest speed?', 'Non-English', 5603746, 'Entertainment', 'https://i.ytimg.com/vi/hBxqptNa6-8/mqdefault.jpg', 'way of the dragon, fist of fury, enter the dragon');
INSERT INTO `fun_video` VALUES(24, 'Ip Man Cup 2012 - Wing Chun open competition: Wing', 'http://www.youtube.com/watch?v=HEH3kzYCEDs', 31, '480', 'Ip Man Cup 2012 - Foshan ( China ) Wing Chun open competition. Free fight - Wing Chun vs Sanda ( by sanda rules) Video # 1  International Wing Chun Organization www.iwco.info www.wing-chun.ru  Russian Wing Chun Federation www.rwcf.ru', 'Non-English', 1068864, 'Entertainment', 'https://i.ytimg.com/vi/HEH3kzYCEDs/mqdefault.jpg', 'Free fight, Sanda');
INSERT INTO `fun_video` VALUES(25, 'the best wing chun & Jeetkunedo Trapping technique', 'http://www.youtube.com/watch?v=hfDLXYOcOcc', 43, '240', ' the best tutorial of sifu Paul Vunak Jeetkunedo Trapping', 'English', 719251, 'Tutorial', 'http://i.ytimg.com/vi/hfDLXYOcOcc/mqdefault.jpg', 'best tutorial, sifu, Paul Vunak, Jeetkunedo, Trapping');
INSERT INTO `fun_video` VALUES(26, '8-form Tai Chi Demo (Back)', 'https://www.youtube.com/watch?v=MhWIIdVyWVs', 4, '360', 'Demonstrates the different forms of Tai Chi and the correct way to perform them. ', 'Non-English', 199319, 'Entertainment', 'https://i.ytimg.com/vi/MhWIIdVyWVs/mqdefault.jpg', '8 form, back, demo');
INSERT INTO `fun_video` VALUES(27, 'Human Weapon Kung Fu - Wing Chun Punch', 'http://www.youtube.com/watch?v=HRu0UaZTbVI', 1, '240', 'This is a Technique Shown on an Episode of ''Human Weapon'' on the History Channel Fridays !! Check your Local Listings. This Move is From the Kung Fu Episode', 'English', 3520863, 'Application', 'http://i.ytimg.com/vi/HRu0UaZTbVI/mqdefault.jpg', 'display, technique');
INSERT INTO `fun_video` VALUES(28, 'Descendants of Wing Chun', 'http://www.youtube.com/watch?v=Iq4IdP1YiL8', 90, '480', ' Descendants of Wing Chun full movie', 'Non-English', 940350, 'Entertainment', 'https://i.ytimg.com/vi/Iq4IdP1YiL8/mqdefault.jpg', 'Descendants of Wing Chun, full movie');
INSERT INTO `fun_video` VALUES(29, 'Wing Chun (red shirt) vs Muay Thai Sparring', 'http://www.youtube.com/watch?v=jF5BKSivkS8', 2, '480', ' This is a friendly sparring session and folks are not here to prove a point, but to learn from each other.', 'English', 846309, 'Group demo', 'https://i.ytimg.com/vi/jF5BKSivkS8/mqdefault.jpg', 'friendly, sparring, session');
INSERT INTO `fun_video` VALUES(30, 'Wing Chun Vs Muay Thai', 'http://www.youtube.com/watch?v=jU8B6eNm2zs', 1, '360', ' A Wing Chun Practitioner goes to a Muay Thai school to challenge them and test his abilities.', 'Non-English', 1536158, 'Application', 'https://i.ytimg.com/vi/jU8B6eNm2zs/mqdefault.jpg', 'Wing Chun Practitioner, Muay Thai, challenge, test, abilities');
INSERT INTO `fun_video` VALUES(31, 'Samuel Kwok Wing Chun fighting applications DEMO', 'http://www.youtube.com/watch?v=kDnm0YiNfcA', 5, '480', ' This video aims to show techniques clearly, hence one person has head gear the other gloves.', 'English', 866383, 'Tutorial', 'https://i.ytimg.com/vi/kDnm0YiNfcA/mqdefault.jpg', 'Master, Samuel Kwok, application');
INSERT INTO `fun_video` VALUES(32, 'Wing chun and Aikido (Kormushin and Mikhailov)', 'http://www.youtube.com/watch?v=KOJdxaOHJ1w', 13, '480', 'Tutorial on wing chun and akido. Demonstration between an instructor and student.', 'Non-English', 851302, 'Tutorial', 'https://i.ytimg.com/vi/KOJdxaOHJ1w/mqdefault.jpg', 'wing chun, fight, tutorial, demo, akido');
INSERT INTO `fun_video` VALUES(33, 'Takedown vs. Wing Chun', 'http://www.youtube.com/watch?v=LkLTxwATgbs', 2, '480', ' Takedown vs. Wing Chun', 'English', 750843, 'Group demo', 'https://i.ytimg.com/vi/LkLTxwATgbs/mqdefault.jpg', 'submission, finish');
INSERT INTO `fun_video` VALUES(34, 'Wing Chun Kung Fu vs. Karate', 'http://www.youtube.com/watch?v=msM6oXWBqXE', 3, '360', ' Donnie Yen (Kung Fu estilo Wing Chun) vs Karate', 'Non-English', 542659, 'Entertainment', 'https://i.ytimg.com/vi/msM6oXWBqXE/mqdefault.jpg', 'Donnie Yen, Kung Fu, Karate');
INSERT INTO `fun_video` VALUES(35, 'Wing Chun & Ju Jitsu - Samuel Kwok & Carlson Graci', 'http://www.youtube.com/watch?v=n3jJ-lb7N8A', 7, '240', ' Two great masters demonstrate their styles.', 'Non-English', 928338, 'Tutorial', 'http://i.ytimg.com/vi/n3jJ-lb7N8A/mqdefault.jpg', 'Two great masters, demonstration, individual, style');
INSERT INTO `fun_video` VALUES(36, 'Wing Chun Lesson 3: basic leg exercise/moving forw', 'http://www.youtube.com/watch?v=nTky4vOOy3A', 2, '360', ' Youve seen the hit movie Ip man, now learn how to use wing Chun techniques in the modern world. Master Wong wing Chun training makes it possible for you to use Wing Chun in full contact for real vs. Muay Thai, vs. boxing, vs. karate, vs. anyone! Available in Ipswich Suffolk and online.', 'English', 560490, 'Tutorial', 'http://i.ytimg.com/vi/nTky4vOOy3A/mqdefault.jpg', 'modern, technique');
INSERT INTO `fun_video` VALUES(37, 'kung fu (wing chun) vs karate', 'http://www.youtube.com/watch?v=NUOjnf8dc_w', 6, '240', 'Comparision between wing chun and karate. Demonstrated inside a school.', 'Non-English', 605753, 'Group demo', 'https://i.ytimg.com/vi/NUOjnf8dc_w/mqdefault.jpg', 'wing chun, karate, school, display, fight');
INSERT INTO `fun_video` VALUES(38, 'Wing tsun guy vs karate guy', 'http://www.youtube.com/watch?v=NZ3-Hi-kMNo', 1, '480', ' 1 grado de wing tsun contra karateka.pant negro wt, blanco karate', 'Non-English', 2597526, 'Entertainment', 'http://i.ytimg.com/vi/NZ3-Hi-kMNo/mqdefault.jpg', 'first grade, 1st grade, wing tsun, karateka,pant, negro, wt, blanco karate');
INSERT INTO `fun_video` VALUES(39, 'Wing Chun vs Boxing - How to bridge a Jab', 'http://www.youtube.com/watch?v=orG1d0d7gq8', 17, '360', ' This is an instructional clip with some basic ideas (for Wing Chun) of closing the distance on a punch that retracts quickly. These concepts may help a Wing Chun student get into range to apply their Wing Chun Chi Sao skills against an alive attacker who moves freely like a boxer. ', 'English', 1603741, 'Application', 'https://i.ytimg.com/vi/orG1d0d7gq8/mqdefault.jpg', 'Master, teacher, Mark Phillips, students, contact');
INSERT INTO `fun_video` VALUES(40, 'Superb Wing Tsun Chi Sao demonstration', 'http://www.youtube.com/watch?v=qaP1X-lEtgc', 2, '240', ' Sifu Emin Boztepe doin Chi Sao with Michael Casey.', 'English', 2560640, 'Application', 'http://i.ytimg.com/vi/qaP1X-lEtgc/mqdefault.jpg', 'Sifu, Emin Boztepe, Chi Sao, Michael Casey');
INSERT INTO `fun_video` VALUES(41, 'Kyokushin Karate vs Wing Chun', 'http://www.youtube.com/watch?v=QH13kYFzfFk', 1, '240', 'The purpose of this video is not a "style vs style" comparison, as many claim it to be. Rather it clearly shows how one martial artist (the karateka) is actually training to fight, while the other (the WC fighter) is like most martial artists in which he thinks he knows how to fight but does not train to actually fight.', 'Non-English', 1365803, 'Tutorial', 'http://i.ytimg.com/vi/QH13kYFzfFk/mqdefault.jpg', '1st World Tournament, styles');
INSERT INTO `fun_video` VALUES(42, 'Wing Chun', 'http://www.youtube.com/watch?v=Qs3BGC4tiPk', 3, '360', 'A scene from Sherlock Holmes. Shows Holmes performing wing chun moves', 'English', 590510, 'Entertainment', 'https://i.ytimg.com/vi/Qs3BGC4tiPk/mqdefault.jpg', 'wing chun, film clip, fight');
INSERT INTO `fun_video` VALUES(43, 'Orange County Wing Chun | The Legend is Born: Ip M', 'http://www.youtube.com/watch?v=Ramwk_AkhgA', 3, '360', ' Orange County Wing Chun school, The Dragon Institute, presents the movie trailer for THE LEGEND IS BORN: IP MAN.Directing by Herman Yau and produced by Sin Kwok Lam, Ip Man', 'Non-English', 2218321, 'Entertainment', 'https://i.ytimg.com/vi/Ramwk_AkhgA/mqdefault.jpg', 'movie, trailer, THE LEGEND IS BORN');
INSERT INTO `fun_video` VALUES(44, 'Wing Chun, Ip Man', 'http://www.youtube.com/watch?v=RYivNC62Plo', 4, '480', ' A compilation of videos including Ip Man, Ip Ching, Ip Chung, Bruce Lee, and Samuel Kwok. all descendents of Ip Man Wing Chun. the music is a few songs from the last samurai-please dont ask.', 'English', 3462160, 'Group demo', 'https://i.ytimg.com/vi/RYivNC62Plo/mqdefault.jpg', 'compilation, videos, Ip Man, Ip Ching, Ip Chung, Bruce Lee, Samuel Kwok');
INSERT INTO `fun_video` VALUES(45, 'Sparring Wing Chun vs Pencasilat', 'http://www.youtube.com/watch?v=sRAhsIpZjjg', 2, '480', ' A national champion of pencasilat came to Saigon to have a friendly exchange with Pierre Francois Flores after his defeat with master Tuan.Due to the rumors around this fight in Hanoi of cheating by using unclean ways, he wanted to check of Flores', 'Non-English', 719671, 'Group demo', 'https://i.ytimg.com/vi/sRAhsIpZjjg/mqdefault.jpg', 'national champion, pencasilat');
INSERT INTO `fun_video` VALUES(46, 'Wing Chun: The Legacy of Ip Man', 'http://www.youtube.com/watch?v=tEB3NEdfLRA', 7, '480', ' In this mini-documentary, a seven minute cut of the original 36 minute presentation of ', 'English', 780561, 'Entertainment', 'http://i.ytimg.com/vi/tEB3NEdfLRA/mqdefault.jpg', 'instructor, David Peterson, overview, history, methods, Gung-fu, system');
INSERT INTO `fun_video` VALUES(47, 'Must See: Wing chun vs kickboxing', 'http://www.youtube.com/watch?v=TH0cjMNVbfs', 3, '480', ' "NMAL Free Style martial arts competition. Wing chun (white singlet ) has 17 years wing chun experience has only fought in his own style tournament and has no other external tournament experience, The Kickboxer has 6 years experience and has tournament experience. This is modified rules. Full contact to the body, semi to the head and legs, Sweeps are allowed, No Knees or elbows. Belts are used for Judging only, the belts do not represent the fights experience.Street combat is different to sport. Please respect the fighters as both are giving it a go.. Thank you for watching."', 'English', 4210756, 'Entertainment', 'https://i.ytimg.com/vi/TH0cjMNVbfs/mqdefault.jpg', 'Full contact, body, semi, head, legs, Sweeps allowed');
INSERT INTO `fun_video` VALUES(48, 'Karate Vs Wing Chun', 'http://www.youtube.com/watch?v=uCv70BHtDf0', 1, '480', 'A Wing Chun Practitioner goes to a Karate school to challenge them and test his abilities.', 'Non-English', 1232470, 'Entertainment', 'http://i.ytimg.com/vi/uCv70BHtDf0/mqdefault.jpg', 'wing chun, karate, school, ability test');
INSERT INTO `fun_video` VALUES(49, 'Wing Chun vs Karate Black Belt', 'http://www.youtube.com/watch?v=ufq_BaiRYoY', 3, '480', ' During a seminar that Sifu Shannon Moore was conducting on Wing Chun ,Chi-Sao and contact reflexes on April 13, 2012.. The gentleman wanted to see if Wing Chun could close the gap from the outside against a kicking opponent. His assumption was the Wing Chun could only work from close range. His Assumption was that Wing Chun fighting was Chi Sao even though it was explained that Chi Sao is not fighting but a tool used to sharpen contact reflexes used in fighting.. Thus FROM ANY RANGE that there is contact, be it sustained or not , a contact reflex can be developed. Answer: Wing Chun can work from all ranges AND EXCELS at close range were the fight is most imminent. Ultimately, someone is going to bridge the gap to end the fight.', 'English', 1385283, 'Group demo', 'https://i.ytimg.com/vi/ufq_BaiRYoY/mqdefault.jpg', 'During a seminar that Sifu Shannon Moore was conducting on Wing Chun ,Chi-Sao and contact reflexes on April 13, 2012.');
INSERT INTO `fun_video` VALUES(50, 'Ip Man Wing Chun Against 10 Karate Black Belts', 'http://www.youtube.com/watch?v=upwyWKzozII', 3, '480', ' A hard Wing Chun demonstration from the terrific movie Ip Man (2008) loosely based on the life of Grandmaster Yip Man, the well-known master of Wing Chun (or Wing Tsun/Ving Tsun) fighting style and the teacher of Bruce Lee.', 'Non-English', 1501113, 'Entertainment', 'https://i.ytimg.com/vi/upwyWKzozII/mqdefault.jpg', 'hard, demonstration, terrific, movie');
INSERT INTO `fun_video` VALUES(51, '"Wing Chun" Documentary ', 'http://www.youtube.com/watch?v=uVkjj8568d8', 36, '360', '"Wing Chun" - a documentary sponsored by Shui On Land. The film shows how we can use Wing Chun and its philosophy to improve our daily life, as well as investigating its claims to be scientifically based.', 'Non-English', 1339168, 'Entertainment', 'https://i.ytimg.com/vi/uVkjj8568d8/mqdefault.jpg', 'life improvement, docu, history, Lui Ming Fai, Hong Kong');
INSERT INTO `fun_video` VALUES(52, 'Wing Tsun Training', 'http://www.youtube.com/watch?v=vTZUibPr6kU', 4, '240', '  Wing Tsun training led by Sifu Bernd Wagner. Tragically in April 2008 he passed away at only 40.', 'English', 2033736, 'Application', 'http://i.ytimg.com/vi/vTZUibPr6kU/mqdefault.jpg', 'training, Sifu, Bernd Wagner ');
INSERT INTO `fun_video` VALUES(53, 'Wing Chun Techniques Applications - How To Improve', 'http://www.youtube.com/watch?v=W_tybgcDUio', 8, '360', ' Here Sifu Mark Phillips takes you on another interesting journey into skillset training within the UK Wing Chun Assoc', 'English', 573848, 'Tutorial', 'https://i.ytimg.com/vi/W_tybgcDUio/mqdefault.jpg', 'short excerpt, Sifu Phillips');
INSERT INTO `fun_video` VALUES(54, 'Wing Chun VS Kick boxer', 'http://www.youtube.com/watch?v=xtQdCuxuWXw', 2, '360', ' my student Ishaq (ZIG SHORT / LITTLE YIP MAN) Sloan. fighting for the very first time..ever! @ the "Man Up Stand Up" tournament 2009.(Sifu Novell Bell gave him the nickname "Little Ip Man" after watching this fight.) although Ishaq did not win this match, he shows great potential, and is very dynamic with his wing chun.', 'English', 2128350, 'Entertainment', 'https://i.ytimg.com/vi/xtQdCuxuWXw/mqdefault.jpg', 'my student Ishaq (ZIG SHORT / LITTLE YIP MAN) Sloan. fighting for the very first time..ever');
INSERT INTO `fun_video` VALUES(55, 'Ip Chun (è‘‰æº–), 84yo wing chun legend', 'http://www.youtube.com/watch?v=y6oPgV0tJrM', 4, '480', 'Following the success of this year''s action blockbuster Ip Man, biopic of the legendary Wing Chun grandmaster and mentor to Bruce Lee, a revival of the Chinese martial art has taken Hong Kong by storm. In this video we meet sifu Ip Chun, son and successor of none other than Ip Man. He currently teaches classes at the humble Ving Tsun Athletic Association''s headquarters in Mong Kok which was established in 1967. Ip Chun prefers to see Wing Chun as a health regimen rather than just a form of combat. The spry 84-year-old tells us about all things Wing Chun and his thoughts on the future of the martial art in today\\''s society. ä»Šå¹´æŽ¨å‡ºçš„å‹•ä½œé‰…ç‰‡ã€Šè‘‰å•ã€‹ä»¥è© æ˜¥å®—å¸«å…¼æŽå°é¾å¸«å‚…è‘‰å•çš„å‚³å¥‡ä¸€ç”Ÿç‚ºé¡Œæï¼Œå¤§æ”¶æ—ºå ´ä¹‹Â­é¤˜ï¼Œä¹Ÿåœ¨é¦™æ¸¯æŽ€èµ·ä¸€è‚¡è© æ˜¥ç†±ã€‚ æœ¬è¦–é »é€ä¸Šè‘‰å•ä¹‹å­è‘‰æº–å¸«å‚…çš„å°ˆè¨ªã€‚è‘‰å¸«å‚…ç¾æ–¼æœ‰å››åäºŒå¹´æ­·å²çš„æ—ºè§’è© æ˜¥é«”è‚²æœƒä»»æ•™ã€‚Â­å°ä»–ä¾†èªªï¼Œè© æ˜¥ä¸¦éžç”¨ä»¥ææ“Šï¼Œè€Œæ˜¯å¼·èº«å¥é«”ä¹‹é“ã€‚ ç¾å¹´å…«', 'English', 8926284, 'Others', 'http://i.ytimg.com/vi/y6oPgV0tJrM/mqdefault.jpg', 'Ip Chun (è‘‰æº–), 84yo wing chun legend');
INSERT INTO `fun_video` VALUES(56, 'Yip Man (Donnie Yen) vs Twister (Darren Shahlavi) ', 'http://www.youtube.com/watch?v=yAzFc3UJrf4', 10, '720', ' After the end of World War II master Ip Man arrives in Hong Kong, where there are several martial arts schools. Despite this, he manages to get a group of students and thanks to have money to support his family. After some time, must accept the challenge of other masters, to be able to continue to run their own school. One of the struggles is unresolved, and in the meantime the British authorities of Hong Kong organized a struggle in which it participates as yet undefeated boxer.', 'English', 2189679, 'Entertainment', 'https://i.ytimg.com/vi/yAzFc3UJrf4/mqdefault.jpg', 'World War II, Hong Kong');
INSERT INTO `fun_video` VALUES(58, 'Best Wing Chun ever', 'http://www.youtube.com/watch?v=YWQKA18ADLs', 4, '480', ' This was the largest ever organized seminar. 200 people came to learn Koviljac wing chun.', 'English', 896563, 'Tutorial', 'https://i.ytimg.com/vi/YWQKA18ADLs/mqdefault.jpg', 'display, fight');
INSERT INTO `fun_video` VALUES(59, 'Wing Tsun, Karate, Kung Fu - victor_gutierrez', 'http://www.youtube.com/watch?v=ZM676yGD_5w', 4, '144', ' Wing Tsun, Wing Chun - Victor Gutierrez\r\n', 'Non-English', 1008315, 'Tutorial', 'http://i.ytimg.com/vi/ZM676yGD_5w/mqdefault.jpg', 'Wing Tsun, Wing Chun - Victor Gutierrez');
INSERT INTO `fun_video` VALUES(60, 'Muay Thai Vs Wing Chun Real Fight', 'http://www.youtube.com/watch?v=zpRWtYC9HOI', 2, '360', ' Brutal fight', 'Non-English', 1036323, 'Group demo', 'https://i.ytimg.com/vi/zpRWtYC9HOI/mqdefault.jpg', 'Brutal fight');
