-- phpMyAdmin SQL Dump
-- version 2.11.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Dec 09, 2014 at 06:13 PM
-- Server version: 5.5.40
-- PHP Version: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `youthcyb_wilman`
--

-- --------------------------------------------------------

--
-- Table structure for table `fun_video`
--

CREATE TABLE `fun_video` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `videolink` text COLLATE utf8_unicode_ci NOT NULL,
  `videolength` int(6) NOT NULL,
  `highestresolution` enum('144','240','360','480','720','1080') COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
  `language` enum('English','Non-English') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'English',
  `viewcount` int(8) NOT NULL,
  `videotype` set('Tutorial','Entertainment','Application','Weapon','Group demo','Others') COLLATE utf8_unicode_ci NOT NULL,
  `iconimage` text COLLATE utf8_unicode_ci NOT NULL,
  `tag` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=115 ;

--
-- Dumping data for table `fun_video`
--

INSERT INTO `fun_video` VALUES(2, '4th Kyu Techniques & Test Requirements Part 1', 'http://www.youtube.com/watch?v=--S-w3L-rRs', 10, '480', 'Yoshimitsu Yamada, a direct student of O Sensei for more than ten years, is an 8th dan and the chief instructor at the New York Aikikai. Currently, he is Chairman of the Board of the United States Aikido Federation and the Latin America Aikido Federation. He is the author of Aikido Complete and has made multiple aikido training tapes.\r\n\r\nYamada Sensei is well known for his clear and strong basic technique. He teaches seminars all over the world where thousands of students attend his classes.', 'Non-English', 80087, 'Tutorial,Application', 'http://i.ytimg.com/vi/--S-w3L-rRs/mqdefault.jpg', 'aikido, techniques, kyu, test, requirements');
INSERT INTO `fun_video` VALUES(3, 'Real aikido highlights', 'http://www.youtube.com/watch?v=-ked1M-nwAg', 5, '480', 'Serbian Self-Defense Martial Art - "REAL AIKIDO"', 'English', 88872, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/-ked1M-nwAg/mqdefault.webp', 'aikido, self, defense, real, highlight');
INSERT INTO `fun_video` VALUES(4, 'Aikido Demostration', 'http://www.youtube.com/watch?v=-RaUpEMpxuY', 7, '240', 'Aikido', 'Non-English', 870873, 'Tutorial', 'http://i.ytimg.com/vi/-RaUpEMpxuY/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament, History');
INSERT INTO `fun_video` VALUES(5, 'How to Do Kubishime | Aikido Lessons', 'http://www.youtube.com/watch?v=05hBVD0tHgg', 3, '1080', ' Learn how to do kubishime from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 60794, 'Tutorial', 'http://i.ytimg.com/vi/05hBVD0tHgg/mqdefault.jpg', 'howto, style, kubishime, kyokushin, nagay, shirp kyokushin, ikito, choke');
INSERT INTO `fun_video` VALUES(6, 'AIKIDO STUDENT vs. JIU-JITSU INSTRUCTOR', 'http://www.youtube.com/watch?v=0UwD4Y3dCpY', 3, '480', 'A challenge match called out by a brazilian jiu-jitsu instructor against an aikido student. AIKIDO DOMINATES!', 'English', 133892, 'Others', 'http://i.ytimg.com/vi/0UwD4Y3dCpY/mqdefault.jpg', 'sports, sparring, aikido, jiu-jitsu');
INSERT INTO `fun_video` VALUES(7, 'Morihei Ueshiba - Rare Aikido Demonstration (1957)', 'http://www.youtube.com/watch?v=30Sa0PLquFg', 14, '720', 'This is a rare demonstration held at the Self-Defense Ministry in Tokyo''s Akasaka circa 1957. This s', 'English', 1294259, 'Entertainment', 'http://i.ytimg.com/vi/30Sa0PLquFg/mqdefault.jpg', 'Sports, Demonstration, Fighting, History, Practice');
INSERT INTO `fun_video` VALUES(8, 'Morihei Ueshiba The Founder Of Aikido', 'http://www.youtube.com/watch?v=4GT9qe1DSgw', 26, '480', 'Morihei Ueshiba The Founder Of Aikido', 'English', 478, 'Others', 'http://i.ytimg.com/vi/4GT9qe1DSgw/mqdefault.jpg', 'founder, Morihei, Ueshiba, documentary');
INSERT INTO `fun_video` VALUES(10, 'Aikido JAPAN - SportAccord World Combat Games 2013', 'http://www.youtube.com/watch?v=63ENGr82p0o', 6, '720', 'SportAccord World Combat Games 2013 AIKIDO-JAPAN demonstration\r\n\r\nTeam from Japan is\r\n\r\nShirakawa Ryuji - Abe toshiharu\r\nHatayama Hiroshi - Suzuki takaki', 'English', 422570, 'Entertainment', 'http://i.ytimg.com/vi/63ENGr82p0o/mqdefault.jpg', 'aikido, japan, sportaccord, world combat, 2013');
INSERT INTO `fun_video` VALUES(11, 'Steven Segal (Aikido) VS Jun Lee (Taekwondo WTF)', 'http://www.youtube.com/watch?v=66NcQjqQXVg', 2, '240', 'FILM CLEMENTINE : Steven Seagal (japain martial art : AIKIDO) VS Jun Lee (korean fight sport : Taekw', 'Non-English', 881033, 'Entertainment', 'http://i.ytimg.com/vi/66NcQjqQXVg/mqdefault.jpg', 'Sports, Demonstration, Fighting, History');
INSERT INTO `fun_video` VALUES(12, 'Mixed Martial Arts Tips : How to Defend Against a ', 'http://www.youtube.com/watch?v=673XP4Fmdk4', 1, '480', 'Defending against a bear hug in MMA or aikido means raising the arms and dropping one"s own body weight. Defend against a bear hug with tips from a mixed martial arts instructor in this free video on MMA tips.', 'English', 140582, 'Tutorial', 'http://i.ytimg.com/vi/673XP4Fmdk4/mqdefault.jpg', 'sports, bear hug, MMA, tips');
INSERT INTO `fun_video` VALUES(13, 'REAL AIKIDO "Masters"', 'http://www.youtube.com/watch?v=69wdPhI01jU', 1, '240', 'Igor Petrovic (5 Dan Black Belt) Dusan Mitrovic (3 Dan Black Belt) https://www.facebook.com/igor.pet', 'English', 1271337, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/69wdPhI01jU/mqdefault.jpg', 'Demonstration, Fighting, Training, Igor Petrovic, Dusan Mitrovic');
INSERT INTO `fun_video` VALUES(14, 'Aikido techniques basic aikido 1 part', 'http://www.youtube.com/watch?v=7fSS9STi6Yc', 45, '360', 'Aikido - YouTube channel of Aikido\r\n', 'English', 163284, 'Tutorial', 'http://i.ytimg.com/vi/7fSS9STi6Yc/mqdefault.jpg', 'aikido, techniques, demo, basic');
INSERT INTO `fun_video` VALUES(15, 'REAL AIKIDO', 'http://www.youtube.com/watch?v=7hQtg1_erAA', 2, '480', 'REAL AIKIDO', 'English', 1688898, 'Entertainment,Weapon', 'http://i.ytimg.com/vi/7hQtg1_erAA/mqdefault.jpg', 'Sports, Demonstration, Fighting, defend, techniques');
INSERT INTO `fun_video` VALUES(16, 'Aikido Forward Roll Tutorial', 'http://www.youtube.com/watch?v=7wV49Q9mpUI', 2, '480', 'A video explaining the forward roll as used in Aikido"s ukemi waza. For more videos like this please go to www.aikidostudent.com', 'English', 94225, 'Tutorial', 'http://i.ytimg.com/vi/7wV49Q9mpUI/mqdefault.jpg', 'education, forward roll, ukemi waza, zenpo kaiten, how-to');
INSERT INTO `fun_video` VALUES(17, 'REAL AIKIDO STREET PRESENTATION', 'http://www.youtube.com/watch?v=99FBkMOJKeo', 4, '480', 'Real Aikido presentation by club IRIMI-NAGE, Marjan Trajkovski master 3th DAN.', 'English', 1029800, 'Tutorial,Weapon,Group demo', 'http://i.ytimg.com/vi/99FBkMOJKeo/mqdefault.jpg', 'Real Life, Demonstartion, Robber, Attacker');
INSERT INTO `fun_video` VALUES(18, 'Aikido vs Special police', 'http://www.youtube.com/watch?v=9CKxhkxPGms', 1, '480', 'Aikido master Dankovic Nenad 2 dan aikikai, Aikido club "Timok" Zajecar,Serbia vs Special police', 'English', 2042190, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/9CKxhkxPGms/mqdefault.jpg', 'Sports, Demonstration, Fighting, Dankovic Nenad');
INSERT INTO `fun_video` VALUES(19, 'Cours Aikido : les bases', 'http://www.youtube.com/watch?v=a4Yi5XMRbEk', 2, '360', ' Chutes arrières et avant, déplacements applications, pivots et projections', 'Non-English', 173616, 'Others', 'http://i.ytimg.com/vi/a4Yi5XMRbEk/mqdefault.jpg', 'education, demonstration, kendo stick, applications');
INSERT INTO `fun_video` VALUES(20, 'JUNKYARD AIKIDO: A Practical Guide To Joint Locks,', 'http://www.youtube.com/watch?v=A9sckwLbSCg', 10, '1080', ' JUNKYARD AIKIDO\r\nA Practical Guide To Joint Locks, Breaks, And Manipulations\r\nFeaturing Michael D. Janich', 'English', 433262, 'Tutorial', 'http://i.ytimg.com/vi/A9sckwLbSCg/mqdefault.jpg', 'education, guide, joint locks, breaks, manipilations, Michael Janich');
INSERT INTO `fun_video` VALUES(21, 'Excellent Aikido Demonstration', 'http://www.youtube.com/watch?v=aicHsMC6rxM', 1, '240', 'Excellent Aikido Demonstration. This is Mr. Anthony Yates, 6th Dan Aikido Yoshinkan.', 'Non-English', 4132127, 'Entertainment', 'http://i.ytimg.com/vi/aicHsMC6rxM/mqdefault.jpg', 'sports, demonstration, Anthony Yates, flips');
INSERT INTO `fun_video` VALUES(22, 'Aikido vs Muay Thai', 'http://www.youtube.com/watch?v=aj8xH_aiCtg', 5, '240', 'Please do not compare styles with each other . Only idiots do that . Instead , compare the fighters ', 'English', 1984108, 'Entertainment', 'http://i.ytimg.com/vi/aj8xH_aiCtg/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament');
INSERT INTO `fun_video` VALUES(23, 'FIRST DVD YOSHINKAN AIKIDO TECHNIQUES GUIDE', 'http://www.youtube.com/watch?v=AoqWF3Sdbxk', 59, '360', ' YOSHINKAN AIKIDO TECHNIQUES GUIDE PART 1 (GOZO SHIODA SOKE) CONTACTS IN BRAZIL:', 'Non-English', 248630, 'Tutorial', 'http://i.ytimg.com/vi/AoqWF3Sdbxk/mqdefault.jpg', 'sports, technigues, yoshinkan, Gozo Shioda Soke');
INSERT INTO `fun_video` VALUES(24, 'Aikido Vs Boxing', 'http://www.youtube.com/watch?v=APgF-DZ8nBM', 2, '480', 'Aikido Vs Boxing, Kick Boxing', 'Non-English', 153585, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/nJWrOa-jkCU/default.jpg', 'Boxing, Fighting, Demonstation, kick boxing, differences');
INSERT INTO `fun_video` VALUES(25, 'Judo vs. Aikido', 'http://www.youtube.com/watch?v=AssByvGVx6s', 4, '720', 'Staniszewski (Judo) X Barry B. (Aikido).....friendly randori', 'Non-English', 869993, 'Tutorial,Application', 'http://i.ytimg.com/vi/AssByvGVx6s/mqdefault.jpg', 'Judo, Fighting, Demonstration, differences, Staniszewski, Barry B., randori');
INSERT INTO `fun_video` VALUES(26, 'Aikido Basics: Wrist Lock Twist : Aikido Sankyo Re', 'http://www.youtube.com/watch?v=AYtfnqy3zTk', 2, '480', 'Aikido is a martial art that uses the opponent"s momentum to defend against an attack. Watch this free video clip as an Aikido expert shows how to defend against a rear wrist grab.', 'English', 1315000, 'Tutorial', 'http://i.ytimg.com/vi/AYtfnqy3zTk/mqdefault.jpg', 'sports, basics, wrist lock twist, defend');
INSERT INTO `fun_video` VALUES(27, 'How to Do Gokyo | Aikido Lessons', 'http://www.youtube.com/watch?v=b3MGSYIzUFw', 3, '1080', 'Learn how to do gokyo from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 62935, 'Tutorial', 'http://i.ytimg.com/vi/b3MGSYIzUFw/mqdefault.jpg', 'howto, style, gokyo, new york aikikai');
INSERT INTO `fun_video` VALUES(28, 'Aikido vs Karate Demonstration', 'http://www.youtube.com/watch?v=bhXp9qkf8zo', 1, '360', 'Demonstration of Christian Tissier, aikidoka, vs Christophe Pinna, karateka. Broadcasted on Eurosport sportschannel in 1998.', 'Non-English', 705788, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/bhXp9qkf8zo/mqdefault.jpg', 'aikido combat, Christian Tissier, aikidoka, Christophe Pinna, karateka, 1998');
INSERT INTO `fun_video` VALUES(29, 'REAL AIKIDO - BEST SELF DEFENSE - MASTERS', 'http://www.youtube.com/watch?v=BsVmnFAcFB4', 9, '360', 'Real Aikido\r\n', 'English', 464155, 'Entertainment,Others', 'http://i.ytimg.com/vi_webp/BsVmnFAcFB4/mqdefault.webp', 'real, aikido, masters, defense');
INSERT INTO `fun_video` VALUES(30, 'Aikido Techniques & Exercises : Uke Nagashi Tenkan', 'http://www.youtube.com/watch?v=bT846dqleq0', 2, '480', 'Uke Nagashi Tenkan, an Aikido technique, trains an Aikido student to deflect an opponents motion and control the line of attack. Learn the important Aikido arm deflection Uke Nagashi in this free Aikido video featuring a 4th degree black belt Aikido instructor.\r\n\r\nExpert: Gary Boaz\r\nBio: Gary Boaz has been training in Aikido for 17 years, he is a 4th degree black belt under Fred Mastision Sensei of Aikido of Phoenix. Gary teaches Aikido, Kyusho-Jitsu, Brazilian Jiu-Jitsu.\r\nFilmmaker: Dustin Daniels', 'English', 493558, 'Tutorial,Application', 'http://i.ytimg.com/vi/bT846dqleq0/mqdefault.jpg', 'aikido, techniques, uke nagashi tenkan, exercises');
INSERT INTO `fun_video` VALUES(31, 'Steven Segal Kicking real life ASS! Aikido Martial', 'http://www.youtube.com/watch?v=Bu7aauJuQHY', 3, '240', 'Martial Arts - Steven Segal Old Footage - Aikido Throwing Techniques, who new he could really kick a', 'English', 2638506, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/Bu7aauJuQHY/mqdefault.jpg', 'History, Demonstration, Fighting, Steven Segal, throwing, ');
INSERT INTO `fun_video` VALUES(32, 'Fake Aikido Master vs MMA', 'http://www.youtube.com/watch?v=bxb0PCBV0vk', 3, '144', 'Fake Aikido Master vs MMA(BJJ,Karate)', 'Non-English', 1239164, 'Entertainment', 'http://i.ytimg.com/vi/bxb0PCBV0vk/mqdefault.jpg', 'Fighting, Tournament, MMA, Fake');
INSERT INTO `fun_video` VALUES(33, 'Aikido para militares', 'http://www.youtube.com/watch?v=BxvgMHezVt8', 7, '360', 'En algunos paises se enseña Aikido a militares y policias. Lamentablemente en nuestro pais aun no se dieron cuenta de lo efectivo que puede ser esta arte en las fuerzas de seguridad. Como miembro de una de estas fuerzas me causa gracia que busquen una policia no violenta y le enseñen a los aspirantes artes de ataque. Pero bue es lo que hay.', 'Non-English', 456622, 'Group demo,Others', 'http://i.ytimg.com/vi_webp/BxvgMHezVt8/mqdefault.webp', 'aikido, paramilitary, demo, group');
INSERT INTO `fun_video` VALUES(34, 'Aikido Exercises & Stretches : Reversed Wrist Aiki', 'http://www.youtube.com/watch?v=c6nS7F8ospQ', 2, '480', 'Stretching is very important in all martial arts including Aikido. Learn how to do the reversed wrist stretch from an Aikido expert in this free martial arts video clip.', 'English', 65764, 'Tutorial', 'http://i.ytimg.com/vi/c6nS7F8ospQ/mqdefault.jpg', 'sports, stretching, reversed wrist stretch, how-to');
INSERT INTO `fun_video` VALUES(35, 'World Combat Games 2013 - Aikido', 'http://www.youtube.com/watch?v=CDRkhJKaDkI', 98, '720', 'World Combat Games 2013 - Aikido', 'English', 203565, 'Entertainment', 'http://i.ytimg.com/vi/CDRkhJKaDkI/mqdefault.jpg', 'world, combat, games, 2013, aikido');
INSERT INTO `fun_video` VALUES(36, 'AIKIDO', 'http://www.youtube.com/watch?v=CtYIbXYU4VY', 8, '240', 'Aikido training of UNDSS (United Nations Department of Safety and Security) personnel at the regiona', 'Non-English', 4079604, 'Entertainment', 'http://i.ytimg.com/vi/CtYIbXYU4VY/mqdefault.jpg', 'News, Training, United Nations, Chile');
INSERT INTO `fun_video` VALUES(37, 'Aikido Moves for Beginners : Aikido Turning Wrist ', 'http://www.youtube.com/watch?v=d67BLDAUb1A', 2, '240', 'Learn tenkai kote hineri, an aikido turning wrist lock technique, from an aikido expert in this free martial arts video.', 'English', 222621, 'Tutorial,Application', 'http://i.ytimg.com/vi/d67BLDAUb1A/mqdefault.jpg', 'aikido, beginner, turning wrist lock, technique');
INSERT INTO `fun_video` VALUES(38, 'Aikido Women - never underestimate her :-)', 'http://www.youtube.com/watch?v=DTsdeazg0tE', 1, '480', 'a Bambang Ali amateur aikido movie making conducted in Sebelas Maret University in Solo, Indonesia, ', 'English', 960532, 'Entertainment,Application', 'http://i.ytimg.com/vi/DTsdeazg0tE/mqdefault.jpg', 'Self Defense, Tutorial, Educational, Woman Defense');
INSERT INTO `fun_video` VALUES(39, 'Karate vs. Aikido', 'http://www.youtube.com/watch?v=e_YMYhuADd8', 3, '480', 'this is a video about martial arts, in specific karate and aikido.... leave a comment please', 'English', 2884397, 'Entertainment,Application', 'http://i.ytimg.com/vi/e_YMYhuADd8/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament, History');
INSERT INTO `fun_video` VALUES(41, 'Aikido master - Shihan Tissier - Iriminage', 'http://www.youtube.com/watch?v=F3NmaYu2Kvc', 4, '240', 'Do you know, which technique is my favorite? :)  I made this video from Tissier''s videos from 1983 t', 'English', 1256114, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/F3NmaYu2Kvc/mqdefault.jpg', 'History, Fighting, Tournament, Demo');
INSERT INTO `fun_video` VALUES(42, 'Aikido � Grandes Maestros � Great Masters', 'http://www.youtube.com/watch?v=fCrAu8Zya_w', 3, '144', 'Classic video of the Greats Masters of the Aikido: Morihei Ueshiba, Gozo Shioda, Koishi Tohei, Kisshomaru Ueshiba and Morihiro Saito.', 'English', 948291, 'Entertainment', 'http://i.ytimg.com/vi/fCrAu8Zya_w/mqdefault.jpg', 'aikido combat, Morihei Ueshiba, Gozo Shioda, Koishi Tohei, Kisshomaru Ueshiba, Morihiro Saito');
INSERT INTO `fun_video` VALUES(43, 'Steven Seagal - Master Of The Aikido', 'http://www.youtube.com/watch?v=fH6HtkySiCQ', 9, '480', ' Steven Seagal demonstrates all his knowledge aikido.', 'English', 1135846, 'Entertainment', 'http://i.ytimg.com/vi/fH6HtkySiCQ/mqdefault.jpg', 'entertainment, Steven Seagal, Randori, kendo stick');
INSERT INTO `fun_video` VALUES(44, 'Aikido instruction: jo suburi 1 thru 20', 'http://www.youtube.com/watch?v=G2KAa4bYIL8', 5, '480', 'Aikido instruction: jo suburi 1thru 20\r\n\r\nThis video shows the 20 jo suburi. The exercises are executed by Lewis Bernaldo de Quiros (rokudan), chief instructor of TAKN.\r\n\r\nThis is an instructional video made by Takemusu Aikido Kyokai Nederland. TAKN chief instructor, Lewis Bernaldo de Quiros (rokudan) was a permanent soto deshi in Iwama under Morihiro Saito shihan from 1986 until 1993. \r\nThe purpose of this video is to support the training of TAKN students and their preparation for tests. It is not meant to replace instruction by a teacher. Since guidance by a senior instructor is vital to proper understanding of the techniques, we do not advise anyone to try and learn the techniques based on videos. \r\n', 'English', 141306, 'Tutorial,Application,Others', 'http://i.ytimg.com/vi_webp/G2KAa4bYIL8/mqdefault.webp', 'aikido, instruction, jo, suburi');
INSERT INTO `fun_video` VALUES(45, 'Doshu Moriteru Ueshiba - 50th All Japan Aikido Emb', 'http://www.youtube.com/watch?v=gXjSmq_tbHQ', 7, '720', 'Demonstration of Aikido Doshu Moriteru Ueshiba at the 50th All Japan Aikido Embukai on the 26th of may 2012 at the Nippon Budokan, Tokyo.', 'English', 273276, 'Entertainment,Others', 'http://i.ytimg.com/vi/gXjSmq_tbHQ/mqdefault.jpg', 'aikido, five steps, demo');
INSERT INTO `fun_video` VALUES(46, 'jujitsu vs aikido', 'http://www.youtube.com/watch?v=GXO9FrZ1N9s', 2, '360', 'freddy ahi esta tu profe!!!', 'Non-English', 2183070, 'Tutorial,Entertainment,Group demo', 'http://i.ytimg.com/vi/GXO9FrZ1N9s/mqdefault.jpg', 'Sports, Demonstration, Fighting, jujitsu, aikido, difference');
INSERT INTO `fun_video` VALUES(47, 'Aikido Basic Techniques : Munetsuki Kotegaeshi', 'http://www.youtube.com/watch?v=HB01hhonf8Q', 2, '480', ' Aikido technique Munetsuki Kotegaeshi allows the Aikido martial artist to block an opponents punch and re-route the energy. Learn the Munetsuki Kotegaeshi Aikido technique in this free video.', 'English', 986866, 'Tutorial', 'http://i.ytimg.com/vi/HB01hhonf8Q/mqdefault.jpg', 'sports, Munetsuki Kotegaeshi, basic techniques, demonstration, block, duo');
INSERT INTO `fun_video` VALUES(48, 'Aikido - This Will Blow Your Mind', 'http://www.youtube.com/watch?v=HcrThLIYvhw', 1, '144', 'Aikido - This Will Blow Your Mind', 'English', 4917955, 'Entertainment', 'http://i.ytimg.com/vi/HcrThLIYvhw/mqdefault.jpg', 'Sports, combat, competition, demonstration');
INSERT INTO `fun_video` VALUES(49, 'aikido training video', 'http://www.youtube.com/watch?v=HpHsguvHdfY', 18, '480', 'you find here some information about aikido s philosophiy and technics..it is in arabic language presented by said elharda and diffused on moroccan tv channel', 'Non-English', 52100, 'Entertainment', 'http://i.ytimg.com/vi/HpHsguvHdfY/mqdefault.jpg', 'people, blogs, techniques, training, ');
INSERT INTO `fun_video` VALUES(50, 'How to Do Tanto Tori | Aikido Lessons', 'http://www.youtube.com/watch?v=iLU5Q5vt2QQ', 4, '1080', 'Learn tanto tori -- how to defend an attack with a tanto, or knife -- from the instructors at The New York ', 'English', 93186, 'Tutorial', 'http://i.ytimg.com/vi/iLU5Q5vt2QQ/mqdefault.jpg', 'howto,style, Tanto Tori, Lessons, demonstrations, defend, instructors');
INSERT INTO `fun_video` VALUES(51, 'Aikido vs Kickboxing: a Study - Kankukan Aiki - At', 'http://www.youtube.com/watch?v=Ip4VYuLm0Qw', 15, '360', 'No description', 'Non-English', 443874, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/Ip4VYuLm0Qw/mqdefault.jpg', 'aikido vs kickboxing, Kankukan Aiki, Atemi Waza, Dai Sankyo, duo, comparison');
INSERT INTO `fun_video` VALUES(52, 'Aikido VS Karate', 'http://www.youtube.com/watch?v=J_K6LOFBBCc', 3, '240', 'DEMONSTRATION.', 'Non-English', 2907660, 'Entertainment', 'http://i.ytimg.com/vi/J_K6LOFBBCc/mqdefault.jpg', 'karate, aikido, japan, demo');
INSERT INTO `fun_video` VALUES(53, 'TRADITIONAL AIKIDO KURILLA DOJO', 'http://www.youtube.com/watch?v=Jca0hcNvlHI', 7, '360', 'Traditional Aikido Kurilla dojo demonstration 2010, children, teenagers, women, men, professionals, Slovakia, Bratislava', 'English', 80300, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/Jca0hcNvlHI/mqdefault.jpg', 'aikido, demonstration, Slovakia, Bratislava, teenagers, women, men, professionals, Kurilla dojo');
INSERT INTO `fun_video` VALUES(54, 'Aikido Dim Mak Felony Fights', 'http://www.youtube.com/watch?v=Jk9eWREBa9U', 3, '240', 'Wing Chun and Aikido RioHeroes Dim Mak Felony Fights Kimbo Slice Mercer Spratt Florian Abbott Tank R', 'Non-English', 1767910, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/Jk9eWREBa9U/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament');
INSERT INTO `fun_video` VALUES(55, 'Aikido Nikyo Wrist Lock Defenses : Aikido Single W', 'http://www.youtube.com/watch?v=Jp8LvwfhQkM', 1, '480', 'A single wrist grab in Aikido is easily defended against with the Nikyo technique. Learn this ancient Aikido self defense move from a martial arts expert in this free video clip and be prepared.', 'English', 173196, 'Tutorial,Application', 'http://i.ytimg.com/vi/Jp8LvwfhQkM/mqdefault.jpg', 'aikido, wrist lock, nikyo, self, defense, grab');
INSERT INTO `fun_video` VALUES(57, 'How to Do Irimi Nage | Aikido Lessons', 'http://www.youtube.com/watch?v=KihiVy0in4E', 2, '1080', ' Learn how to do irimi nage from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 152134, 'Tutorial', 'http://i.ytimg.com/vi/KihiVy0in4E/mqdefault.jpg', 'howto,style, Irimi Nage, instructor, Ai Hanmi Katate Dori, duo, demonstration, Aikido Lessons');
INSERT INTO `fun_video` VALUES(58, 'judo vs aikido', 'http://www.youtube.com/watch?v=KLJPcChg1T4', 1, '240', 'pelea de un disque judoka con un aikidoka. aunque para mi que el judoka esta solo de uke y no pelea ', 'Non-English', 1949349, 'Tutorial,Entertainment,Group demo', 'http://i.ytimg.com/vi/P73mcY3g5ZE/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament');
INSERT INTO `fun_video` VALUES(59, 'Aikido - Ueshiba Moriteru & Ueshiba Mitsuteru demo', 'http://www.youtube.com/watch?v=kOhjG9ClCVk', 9, '720', 'Demonstration of Doshu Moriteru Ueshiba and Waka Sensei Mitsuteru Ueshiba at the Aiki-jinja Taisai 2013 in Iwama (Ibaraki), Japan.', 'English', 314132, 'Entertainment', 'http://i.ytimg.com/vi/kOhjG9ClCVk/mqdefault.jpg', 'aikido, ueshiba, moriteru, demo, japan');
INSERT INTO `fun_video` VALUES(60, 'Wing chun and Aikido (Kormushin and Mikhailov)', 'http://www.youtube.com/watch?v=KOJdxaOHJ1w', 13, '480', '&#1042;&#1072;&#1088;&#1080;&#1072;&#1085;&#1090;&#1099; &#1087;&#1088;&#1080;&#1084;&#1077;&#1085;&', 'Non-English', 849259, 'Tutorial,Application,Weapon,Group demo', 'http://i.ytimg.com/vi/KOJdxaOHJ1w/mqdefault.jpg', 'Russian, Demonstration, Tutorial, Kormushin, Mikhailov');
INSERT INTO `fun_video` VALUES(61, 'THIRD DVD YOSHINKAN AIKIDO TECHNIQUES GUIDE', 'http://www.youtube.com/watch?v=KRjoqIhl7Ms', 180, '360', 'YOSHINKAN AIKIDO TECHNIQUES GUIDE PART 3 (GOZO SHIODA SOKE)', 'English', 533, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/KRjoqIhl7Ms/mqdefault.jpg', 'technique, demonstration, DVD, Third, Iriminage, Hijishime, Hiji Ate Kokyu Nage, Kotegaeshi, Kokyuho, Jiyuwaza');
INSERT INTO `fun_video` VALUES(62, 'How to Do Yonkyo | Aikido Lessons', 'http://www.youtube.com/watch?v=ksGerDJYcc8', 2, '720', 'Learn how to do yonkyo from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 94110, 'Tutorial', 'http://i.ytimg.com/vi/ksGerDJYcc8/mqdefault.jpg', 'aikido, Yonkyo, how to, lesson, instruction, fitness, new york');
INSERT INTO `fun_video` VALUES(63, 'Aikido real street attack', 'http://www.youtube.com/watch?v=kvTxSZ9Y7D4', 3, '480', 'in this video clip you can see the reality of Aikido..', 'English', 888632, 'Entertainment,Application,Group demo', 'http://i.ytimg.com/vi/kvTxSZ9Y7D4/mqdefault.jpg', 'Myth, History, Fighting, Combat');
INSERT INTO `fun_video` VALUES(64, 'Tamaris - Real Aikido 1', 'http://www.youtube.com/watch?v=l-MAX1TQ7DQ', 7, '480', 'Srbija, Beograd, Polaganje za braon pojas_2006 god.  Tamaris Real Aikido 2 Video here:', 'English', 1714014, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/l-MAX1TQ7DQ/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament');
INSERT INTO `fun_video` VALUES(65, 'Rick Mirandette Aikido Self Defense Moves', 'http://www.youtube.com/watch?v=lHX65S_fnFU', 2, '480', ' Shot at Rick Mirandette"s school, in Kentwood, Michigan, in 1995. Rick Mirandette demonstrates two basic aikido self defense moves. Part of the Michigan Martial Arts Project. www.michiganmartialartsproject.com', 'English', 1118526, 'Tutorial', 'http://i.ytimg.com/vi/lHX65S_fnFU/mqdefault.jpg', 'sports, self defense, duo, demonstration, Rick Mirandette');
INSERT INTO `fun_video` VALUES(66, 'How to Do Kotegaeshi | Aikido Lessons', 'http://www.youtube.com/watch?v=ll1GCzl4Bxg', 2, '1080', 'Learn how to do kotegaeshi from the instructors at The New York Aikikai in this Howcast aikido video.\r\n\r\n\r\nKotegaeshi is the next technique were going to take a look at. It literally means wrist twist. If you start with kakataetori. I want to step offline and away from the attack. Ten kon. Bring the hand in front of me. The free hand is going to rest right on top of my partners. Take a look. Ive got my thumb right in between the ring and pinkie finger. My fingers inside the palm. As I step back and my partner turns to face me, I want to match my fingers right on top of my partners and point all of this at the floor as I move. Turn the hips. Fingers down to the floor. Make sure Ive got the hand position. Ten Kon. Then I take one more step back and match fingers to fingers, when all of that is right at the floor. Down. We can also see this from ski. Same movement. Same movement. Yokomunushi will change things a little bit, but the basic technique, still there. Kotegaeshi. Wrist twist.', 'English', 139537, 'Tutorial,Application', 'http://i.ytimg.com/vi/ll1GCzl4Bxg/mqdefault.jpg', 'aikido, techniques, kotegaeshi, lesson');
INSERT INTO `fun_video` VALUES(68, 'aikido vs jiu jitsu', 'http://www.youtube.com/watch?v=LPx7IAlRj_A', 3, '240', 'aikido vs jiu jitsu demostraci�n', 'Non-English', 6058126, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/LPx7IAlRj_A/mqdefault.jpg', 'Sports, Jiu Jitsu, vs, aikido, competition, duo');
INSERT INTO `fun_video` VALUES(69, 'How to Do Hiji Waza | Aikido Lessons', 'http://www.youtube.com/watch?v=mjbZDCkIZeU', 3, '1080', ' Learn how to do hiji waza from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 110429, 'Tutorial', 'http://i.ytimg.com/vi/mjbZDCkIZeU/mqdefault.jpg', 'how to, style, Hiji Waza, Lessons, demonstration');
INSERT INTO `fun_video` VALUES(70, 'Artes Letales - Aikido (Parte 1)', 'http://www.youtube.com/watch?v=mplh3HXfAfM', 14, '240', 'Documental sobre Aikido emitido en National Geographic\r\n', 'Non-English', 88042, 'Entertainment,Others', 'http://i.ytimg.com/vi/mplh3HXfAfM/mqdefault.jpg', 'aikido, combat, documentary, national geographic');
INSERT INTO `fun_video` VALUES(71, 'Aikido Vs Tae Kwon Do - Kuro Tai Shiro', 'http://www.youtube.com/watch?v=n5RXzu0OrRM', 4, '240', 'Playing with camera angles and fight choreography during pre-production of ''Land of the Kami''.', 'English', 1537116, 'Entertainment', 'http://i.ytimg.com/vi/n5RXzu0OrRM/mqdefault.jpg', 'Sports, Demonstration, Fighting, Tournament');
INSERT INTO `fun_video` VALUES(72, 'Advanced Aikido: Principles of Motion : Advanced A', 'http://www.youtube.com/watch?v=NEZMCaiIJME', 2, '480', 'Always assume multiple attackers and multiple strikes from attackers when self defense training. Learn how to defend yourself from a kick and punch combination attack in this free Aikido training video featuring a 4th degree black belt.', 'English', 127333, 'Tutorial', 'http://i.ytimg.com/vi/NEZMCaiIJME/mqdefault.jpg', 'sports, advanced, techniques, combo, part 1, motion, deomstration');
INSERT INTO `fun_video` VALUES(73, 'Aikido VS Taekwondo', 'http://www.youtube.com/watch?v=NinO0vGum38', 3, '480', 'Hello everyone, thank you for your comments for this performance video. This is Nakamura who is showing as a Aikido fighter . \r\nRecently, there is a video has been UP without our permission almost the same contents with BGM plaintive　of our video , but It is different from our intention. So let me say our opinion about pirated Video.\r\nFirst, Don’t laugh at Mr. C of Taekwondo guy. He is a very nice and brave man, even though his taekwondo shill is not so high level.\r\nBecause Korea is hateful, writing rude comments to him , but don’t do that.　He is proud Challenger.', 'Non-English', 5196644, 'Entertainment', 'http://i.ytimg.com/vi_webp/NinO0vGum38/mqdefault.webp', 'korea, japan, aikido, taekwondo');
INSERT INTO `fun_video` VALUES(74, 'Advanced Aikido Techniques Part 1', 'http://www.youtube.com/watch?v=NmIuiuaREpk', 10, '480', ' Yoshimitsu Yamada, a direct student of O Sensei for more than ten years, is an 8th dan and the chief instructor at the New York Aikikai. Currently, he is Chairman of the Board of the United States Aikido Federation and the Latin America Aikido Federation. He is the author of Aikido Complete and has made multiple aikido training tapes.', 'English', 606944, 'Others', 'http://i.ytimg.com/vi/NmIuiuaREpk/mqdefault.jpg', 'advanced, techniques, part 1, demonstration, duo');
INSERT INTO `fun_video` VALUES(75, 'Aikido Ukemi: Ushiro Otoshi', 'http://www.youtube.com/watch?v=ogDN0ZghdQs', 2, '480', 'Aikido Ukemi: Ushiro Otoshi\r\n\r\nDonovan Waite Sensei started practicing Aikido in 1969, at a very young age. As a 14 year old, he received his 1st Degree Black Belt from Ralph Reynolds Sensei who was under the direction of T.K. Chiba Sensei in Birmingham, England. Since then Waite Sensei has spent the last 37 years persuing a deeper understanding of Aikido. Along that path, Waite Sensei has had the opportunity to train under many of Aikidos foremost instructors. In 1984 he apprenticed himself to Yoshimitsu Yamada Sensei, chairman of the United States Aikido Federation and chief instructor of the New York Aikikai. For over ten years he was Uchi Deshi, or live-in student, under Yamada Sensei and he still holds a weekly teaching position at the New York Aikikai. Since 1997 Donovan Waite Sensei has been the chief instructor of Aikido of Center City.', 'English', 139328, 'Tutorial,Entertainment,Application,Others', 'http://i.ytimg.com/vi/ogDN0ZghdQs/mqdefault.jpg', 'aikido,ushiro, otoshi, ukemi');
INSERT INTO `fun_video` VALUES(76, 'How to Do Tai Sabaki | Aikido Lessons', 'http://www.youtube.com/watch?v=OQ7e-8yKfI4', 3, '1080', 'Learn how to do tai sabaki from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 143157, 'Tutorial', 'http://i.ytimg.com/vi/OQ7e-8yKfI4/mqdefault.jpg', 'how to,style, Sabaki, lessons, demonstration, duo');
INSERT INTO `fun_video` VALUES(77, 'REAL AIKIDO - 10. Dan', 'http://www.youtube.com/watch?v=P0PL2iV4UK4', 4, '480', 'CONTACT NUMBER: +99450 313 33 33 Grandmaster Ljubomir Vracarevic explains a Real Aikido technique to', 'Non-English', 1205664, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/P0PL2iV4UK4/mqdefault.jpg', 'Teaching, Demonstartion, Ljubomir Vracarevic, Azerbaijan, WCRA');
INSERT INTO `fun_video` VALUES(78, 'Aggressive Aikido techniques demonstration', 'http://www.youtube.com/watch?v=P73mcY3g5ZE', 4, '360', 'Description', 'English', 1942641, 'Entertainment,Weapon', 'http://i.ytimg.com/vi/P73mcY3g5ZE/mqdefault.jpg', 'Sports, Demonstration, Fighting, History, Tournament');
INSERT INTO `fun_video` VALUES(79, 'Muay Thai vs Aikido', 'http://www.youtube.com/watch?v=pbya7nEL0MQ', 3, '720', 'This is a friendly sparring session and folks are not here to prove a point, but to learn from each other.\r\n\r\nIf you are in the Orange County, California area, you are welcome to attend our meetups. We just ask that you leave your EGOs at home, come with an open mind, and have fun!', 'English', 953711, 'Entertainment', 'http://i.ytimg.com/vi/pbya7nEL0MQ/mqdefault.jpg', 'aikido, muay thai, demo, differences');
INSERT INTO `fun_video` VALUES(80, 'Aikido Vs. MMA Real Fight Part 1', 'http://www.youtube.com/watch?v=pLqovX4G8Z0', 3, '240', 'This is a video of an Aikido black belt taking on a Mixed Martial Artist in an MMA tournament. The fight goes into overtime, so be sure to check out the second part!', 'Non-English', 2930985, 'Entertainment', 'http://i.ytimg.com/vi/pLqovX4G8Z0/mqdefault.jpg', 'sports, MMA fighter, competition, duo, vs');
INSERT INTO `fun_video` VALUES(81, 'Aikido Highlight - Shirakawa Ryuji sensei', 'http://www.youtube.com/watch?v=pme6jdPvusw', 13, '144', '&#12304;Aikido Highlight&#12305; Shirakawa Ryuji sensei ', 'Non-English', 118186, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/pme6jdPvusw/mqdefault.jpg', 'aikido combat, Shirakawa Ryuji, demonstration, duo, ');
INSERT INTO `fun_video` VALUES(82, 'Real Aikido Street Fighting. Real Street Fight & A', 'http://www.youtube.com/watch?v=pqxNV0MMKXc', 5, '360', 'Real Aikido mixed with Street Fighting skills Video with Slo-mo so you can see what is happening! WATCH THEIR FEET! Some people really know these skills', 'English', 96737, 'Entertainment,Group demo', 'http://i.ytimg.com/vi/pqxNV0MMKXc/mqdefault.jpg', 'aikido, street fight, application, skills');
INSERT INTO `fun_video` VALUES(83, 'Aikido', 'http://www.youtube.com/watch?v=qAc-gQIeAaI', 4, '240', 'Seagal, Tissier, Morihiro and other', 'English', 2039928, 'Entertainment,Others', 'http://i.ytimg.com/i/ZUzZaW1Q0PmAwKT87WRDSA/1.jpg', 'Sports, steven seagal, demonstration, duo, ');
INSERT INTO `fun_video` VALUES(84, 'Aikido from scratch to perfection', 'http://www.youtube.com/watch?v=QHbfP1pPAAY', 53, '240', ' complete video of techniques', 'English', 389815, 'Tutorial', 'http://i.ytimg.com/vi/QHbfP1pPAAY/mqdefault.jpg', 'sports, compilation, techniques, demonstration, ');
INSERT INTO `fun_video` VALUES(85, 'Pro Fighter vs Aikido Master', 'http://www.youtube.com/watch?v=QWpVUMCcSys', 9, '480', ' 格闘家VS合気道家', 'English', 2716527, 'Others', 'http://i.ytimg.com/vi/QWpVUMCcSys/mqdefault.jpg', 'sports, fighter, pro, master, spar, duo');
INSERT INTO `fun_video` VALUES(86, 'Aikido vs Karate', 'http://www.youtube.com/watch?v=R797LamA3Vw', 1, '480', 'Shigeo Tsujitani(karate) vs Tetsu Yamazaki(Aikido) in Bujinhai''95. Bujinhai is Japanese open tournam', 'English', 3909776, 'Entertainment', 'http://i.ytimg.com/vi/R797LamA3Vw/mqdefault.jpg', 'Sports, aikido, vs, karate, tournament, MMA, ');
INSERT INTO `fun_video` VALUES(87, 'Combat Aikido ', 'http://www.youtube.com/watch?v=R7HiR9hr7V0', 4, '720', 'I know many of you have already watched Sensei Gordon Muller''s Aikido videos, this is a re-upload of some of his older videos updated to HD for viewing purposes. My apologies to those who were looking for newer material from him.', 'English', 246244, 'Tutorial,Application,Weapon', 'http://i.ytimg.com/vi_webp/R7HiR9hr7V0/mqdefault.webp', 'combat, aikido, demo, Gordon Muller, compilation');
INSERT INTO `fun_video` VALUES(88, 'Muay Thai vs AikidoAikido Aikijujutsu - Street Def', 'http://www.youtube.com/watch?v=RBswNtDZoME', 40, '240', 'DISCLAIMER: I am not claiming any rights to this or any other videos that I upload nor do I wish to profit from it/them; everything I post is for education-information purposes only.', 'English', 75744, 'Application', 'http://i.ytimg.com/vi_webp/RBswNtDZoME/mqdefault.webp', 'aikido, aikijujutsu, street defense, demonstration, duo, ');
INSERT INTO `fun_video` VALUES(89, 'Aikido National Geographic', 'http://www.youtube.com/watch?v=RCeOedrW-AM', 47, '480', 'n/a', 'English', 149974, 'Entertainment', 'http://i.ytimg.com/vi_webp/RCeOedrW-AM/mqdefault.webp', 'aikido, national geographic, documentary, history, demonstration');
INSERT INTO `fun_video` VALUES(90, 'Harald Ross, Aikikan: Aikido vs. Tango', 'http://www.youtube.com/watch?v=rG_tnefyOcc', 4, '480', 'Harald and Stefan show how well aikido and tango moves mix', 'English', 209987, 'Entertainment', 'http://i.ytimg.com/vi/rG_tnefyOcc/mqdefault.jpg', 'harald, ross, aikikan, tango');
INSERT INTO `fun_video` VALUES(91, 'aikido v jujitsu training', 'http://www.youtube.com/watch?v=RkQWEi8XbII', 22, '480', 'international seminar, aikido & jujitsu intsructors demonstrate there skills that are very effective when combined.', 'English', 63684, 'Tutorial,Application,Group demo', 'http://i.ytimg.com/vi_webp/RkQWEi8XbII/mqdefault.webp', 'aikido, vs, jujitsu, instruction, demo');
INSERT INTO `fun_video` VALUES(92, 'Atemi: Aikido Techniques : Atemi from a Hook Punch', 'http://www.youtube.com/watch?v=rNu4qOrThhE', 1, '480', 'Iremi, an Aikido Atemi, allows the Aikido student to close with the opponent and block a hook punch before the enemy has any power behind it. Learn Atemi from a hook strike, from a 5th degree Aikido black belt and United States martial arts hall of fame inductee in this free Aikido video.', 'English', 61428, 'Tutorial', 'http://i.ytimg.com/vi/rNu4qOrThhE/mqdefault.jpg', 'sports, technique, atemi, hook punch, demonstration, ');
INSERT INTO `fun_video` VALUES(93, 'Aikido, The Samurai Spirit', 'http://www.youtube.com/watch?v=rs4gTZjSqJc', 44, '360', 'Good, very well explained. The translation is normal, I hope you like it!', 'English', 1969484, 'Entertainment,Group demo', 'http://i.ytimg.com/vi_webp/rs4gTZjSqJc/mqdefault.webp', 'aikido, samurai, demo, documentary, group');
INSERT INTO `fun_video` VALUES(94, 'How to Do Ikkyo | Aikido Lessons', 'http://www.youtube.com/watch?v=SVdY3AwlH_w', 2, '1080', 'Watch more How to Do Aikido videos: http://www.howcast.com/videos/505835-...\r\n\r\nLearn how to do ikkyo from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 110981, 'Tutorial,Application', 'http://i.ytimg.com/vi/SVdY3AwlH_w/mqdefault.jpg', 'ikkyo, aikido, lesson, how to, style, ');
INSERT INTO `fun_video` VALUES(95, 'Aikido: OKAMOTO Yoko Sensei - Seminar in Offenbach', 'http://www.youtube.com/watch?v=Tv7BTKQzn50', 9, '144', 'No description', 'Non-English', 291320, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/Tv7BTKQzn50/mqdefault.jpg', 'aikido techniques, aikido,aikido fight, aikido street fight, aikido master, aikido demonstration, steven seagal aikido, aikido training lessons');
INSERT INTO `fun_video` VALUES(97, 'How to Do Aiki Otoshi | Aikido Lessons', 'http://www.youtube.com/watch?v=uEEV-ZzoWgo', 2, '1080', 'Learn how to do aiki otoshi from the instructors at The New York Aikikai in this Howcast aikido video.', 'English', 98295, 'Tutorial', 'http://i.ytimg.com/vi/uEEV-ZzoWgo/mqdefault.jpg', 'howto,style, Aiki Otoshi, New York, demonstration, duo');
INSERT INTO `fun_video` VALUES(98, 'Excellent Aikido Demonstration Mori Shihan', 'http://www.youtube.com/watch?v=ugsS2_Z0wpA', 20, '720', 'This is Sensei Mori, Yoshinkan Aikido.', 'English', 1506467, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/ugsS2_Z0wpA/mqdefault.webp', 'aikido, demonstration, mori, shihan');
INSERT INTO `fun_video` VALUES(99, 'Aikido: Christian Tissier - Belgium 2013', 'http://www.youtube.com/watch?v=ulmZRoASiTk', 12, '1080', 'Summercamp in Cerfontaine', 'English', 290443, 'Tutorial,Application,Group demo', 'http://i.ytimg.com/vi/ulmZRoASiTk/mqdefault.jpg', 'christian tissier, aikido, belgium, 2013');
INSERT INTO `fun_video` VALUES(100, 'BOXING vs. AIKIDO (Effectiveness of aikido)', 'http://www.youtube.com/watch?v=wCSDrqbD8UM', 1, '480', 'how effective is aikido against boxing?', 'English', 1225073, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/wCSDrqbD8UM/mqdefault.jpg', 'Demonstration, Boxing, Aikido, spar, effectiveness');
INSERT INTO `fun_video` VALUES(101, 'steven seagal aikido tribute', 'http://www.youtube.com/watch?v=wH6OXZ9Dsz0', 7, '720', ' made this a while ago on my old youtube channel which doesn"t exist any more.  I do not own the rights to any of the material used. this video is only for entertainment.', 'English', 428419, 'Entertainment', 'http://i.ytimg.com/vi/wH6OXZ9Dsz0/mqdefault.jpg', 'sports, steven seagal, documentary, group, weapon, hand to hand');
INSERT INTO `fun_video` VALUES(102, 'Deadly Aikido', 'http://www.youtube.com/watch?v=WM58bXR9MYg', 7, '240', ' I,ve been sick of certain people dissin aikido so I made this Now I don"t do aikido but I respect It. Wow, almost 500,000 views this video is doing better than I Thought and make sure to check out my ', 'English', 669643, 'Entertainment', 'http://i.ytimg.com/vi/WM58bXR9MYg/mqdefault.jpg', 'sports, demonstration, deadly, duo, weapon');
INSERT INTO `fun_video` VALUES(103, 'Aikido - Morihei Ueshiba - Way of Harmony - 04', 'http://www.youtube.com/watch?v=Ws2Iczref5U', 10, '240', 'Way of Harmony. Colección de videos de O Sensei. 4/4', 'Non-English', 1371089, 'Application,Others', 'http://i.ytimg.com/vi_webp/Ws2Iczref5U/mqdefault.webp', 'aikido, morihei, ueshiba, harmony');
INSERT INTO `fun_video` VALUES(105, 'Karate vs. Aikido', 'http://www.youtube.com/watch?v=XEQGlLuoEDQ', 2, '480', 'Just a fun clip I put together, basically practicing different camera angles & cuts to a make a sequ', 'English', 1757924, 'Entertainment,Application', 'http://i.ytimg.com/vi/XEQGlLuoEDQ/mqdefault.jpg', 'Sports, Demonstration, Fighting, Practice');
INSERT INTO `fun_video` VALUES(106, 'The Five Aikido Steps', 'http://www.youtube.com/watch?v=xL_YLYdrEAE', 2, '240', 'n/a', 'English', 224545, 'Tutorial,Application,Others', 'http://i.ytimg.com/vi_webp/xL_YLYdrEAE/mqdefault.webp', 'aikido, five steps, demo, okuriashi, ayumi ashi, tentai, okuri ashi, tenkan');
INSERT INTO `fun_video` VALUES(107, 'o sensei morihei ueshiba', 'http://www.youtube.com/watch?v=XoDK3XuvZWw', 4, '240', 'o sensei morihei ueshiba, Aikido last public demonstration, January 1969 at the age of 85. later par', 'Non-English', 971156, 'Tutorial,Weapon,Group demo', 'http://i.ytimg.com/vi/XoDK3XuvZWw/mqdefault.jpg', 'History, Educational, morihei ueshiba, public, demonstration');
INSERT INTO `fun_video` VALUES(108, '48th All Japan Aikido - Ueshiba Moriteru Doshu', 'http://www.youtube.com/watch?v=xOZ3dVh5I6I', 8, '1080', 'Demonstration during the 48th All Japan Aikido Demonstration (2010) at Budokan.', 'English', 357164, 'Entertainment', 'http://i.ytimg.com/vi_webp/xOZ3dVh5I6I/mqdefault.webp', 'aikido, japan, demo, ueshiba, moriteru, doshu');
INSERT INTO `fun_video` VALUES(109, 'Koichi Tohei - ki aikido 1/5 Fundamental Concept P', 'http://www.youtube.com/watch?v=XuuhW9t11e0', 11, '240', 'Ki aikido fossombrone - Koichi Tohei - Fundamental Concept Principle And Elementary Course1 - Shin shin toitsu Aikido - www.kiaikidojo.it', 'English', 196078, 'Entertainment,Application', 'http://i.ytimg.com/vi/XuuhW9t11e0/mqdefault.jpg', 'kochi, tohei, ki, aikido, fundamentals, principle, concept');
INSERT INTO `fun_video` VALUES(110, 'Aikido with Steven Seagal', 'http://www.youtube.com/watch?v=y5dDwzwb3-8', 2, '240', 'Young Steven Seagal performs rondori, multiple attackers and defence against weapons', 'English', 1023880, 'Tutorial,Application,Others', 'http://i.ytimg.com/vi/y5dDwzwb3-8/mqdefault.jpg', 'Entertainment, History, Training, Steven Seagal, instructional, rondori, multiple attackers, defence against weapons');
INSERT INTO `fun_video` VALUES(111, 'Myanmar Aikido - ukemi practice', 'http://www.youtube.com/watch?v=YMpBpM38TMg', 3, '240', 'Incredible low impact and silent ukemi. Step by step instruction on how to high fall by Maung Maung Thant (San dan).', 'English', 457055, 'Tutorial', 'http://i.ytimg.com/vi/YMpBpM38TMg/mqdefault.jpg', 'sports, high fall, how to, Myanmar Aikido, Maung Maung Thant');
INSERT INTO `fun_video` VALUES(112, 'Steven Seagal AIKIDO Master YouTube', 'http://www.youtube.com/watch?v=yRhdKEGrTCo', 3, '144', 'Steven Seagal AIKIDO Master YouTube', 'English', 2111148, 'Tutorial,Entertainment', 'http://i.ytimg.com/vi/yRhdKEGrTCo/mqdefault.jpg', 'Sports, Demonstration, Fighting, Steven Seagal, instructional, master');
INSERT INTO `fun_video` VALUES(113, 'Mysterious Martial Arts Aikido', 'http://www.youtube.com/watch?v=zCEAx-tH6Nk', 13, '480', 'n/a', 'Non-English', 211415, 'Tutorial,Application', 'http://i.ytimg.com/vi_webp/zCEAx-tH6Nk/mqdefault.webp', 'mysterious, martial arts, aikido, demonstration, instructional, documentary');
INSERT INTO `fun_video` VALUES(114, 'How to Do Sankyo | Aikido Lessons', 'http://youtu.be/u71nroaAXnM', 3, '1080', 'Watch more How to Do Aikido videos: http://www.howcast.com/videos/505837-...\r\n\r\nLearn how to do sankyo from the instructors at The New York Aikikai in this Howcast aikido video.\r\n\r\n\r\nOkay. This technique is called sankyo. Or number three in the series of techniques that O''Sensei established. And again, this whole series, one through five, is going to start with ikkyo. So if we look at shomenuchi, ikkyo, you meet and down. Again, I want to lift the hand so that I''m looking at the palm of my partner''s hand. Reach underneath. I''m going to wrap my fingers right around the inside of the palm. And the fingers are another aspect that I have. I''m going to step back. And think about pointing all of this directly at your partner as they turn and cut. Again, this is very similar to the sword work that we do in aikido. Again, I don''t want to point the fingers down and cut with the butt of the sword. I want to try to cut out with the tip and the elbow of the sword. And I''m going to continue to move', 'English', 444962, 'Tutorial,Group demo', 'http://i.ytimg.com/vi/u71nroaAXnM/mqdefault.jpg', 'How to, Sankyo, demonstration, lessons, style\r\n');
